### ISSUE TITLE
Possible error of doc on namespace?

### ISSUE THREAD

**Issue by arthurtea** [cult-of-coders/redis-oplog#101]
In [this section](https://github.com/cult-of-coders/redis-oplog#namespacing), should
```
Users.insert(data, {
    namespace: companyId
})
```
instead be this?:
```
Users.insert(data, {
    namespace: 'company::' + companyId
})
```
Otherwise how the `.insert` knows about the 'company::' prefix?

**Comment by theodorDiaconu** [comment]
@arthurtea that's the diff between namespace and channels. I don't know how to make it less confusing, but the need for namespace arises for multi-tenant systems.
 
If you use namespace then it autoprefixes the string/strings with collection name, in your case "users::"
```
Users.insert(data, {
    namespace: 'company::' + companyId
})
```

Will push to users::company::companyId channel.

**Comment by arthurtea** [comment]
Hi. But this is contrary to what the doc says here: https://github.com/cult-of-coders/redis-oplog#namespacing

The doc says that the collection name `users` will be _suffixed_, not prefixed:
> Users.insert(data, { namespace: companyId })
> The channel to which redis will push is: company::${companyId}::users

**Comment by theodorDiaconu** [comment]
@arthurtea it's written badly. will fix!

**Comment by theodorDiaconu** [comment]
got fixed
