### ISSUE TITLE
Cause of empty list view after update is IP and PORT issue?

### ISSUE THREAD

**Issue by juvyc** [cult-of-coders/redis-oplog#103]
Hi,

I've a weird issue integrating of this add-on on our meteor app. I think I've configured the IP and PORT correctly because at first I got a logs regarding the Publication and Subcription and no error. However, when I tried to update the data from the list view we have on the front end, the list got empty, it removes all data. Then... after a couple of minutes (I think 2-3 minuts) it displays back and on the console log I got the error below.

```
W20170109-00:29:13.206(0)? (STDERR) events.js:141
W20170109-00:29:13.207(0)? (STDERR)       throw er; // Unhandled 'error' event
W20170109-00:29:13.212(0)? (STDERR)       ^
W20170109-00:29:13.215(0)? (STDERR) 
W20170109-00:29:13.215(0)? (STDERR) Error: Redis connection to 104.197.33.159:3000 failed - connect ETIMEDOUT 104.197.33.159:3000
W20170109-00:29:13.216(0)? (STDERR)     at Object.exports._errnoException (util.js:907:11)
W20170109-00:29:13.216(0)? (STDERR)     at exports._exceptionWithHostPort (util.js:930:20)
W20170109-00:29:13.217(0)? (STDERR)     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
```

Any solution to fix this problem? Maybe I'm pointing to a wrong IP and PORT that used by the redis?

Thanks!

**Comment by ramezrafla** [comment]
Did you turn on debug mode in redis-oplog?

**Comment by juvyc** [comment]
Yes I did. Seems like the refresh time takes to 2-3 minutes?

**Comment by ramezrafla** [comment]
It shouldn't, it's almost real-time. Maybe you can monitor from the command line to see if redis server is having issues.
```redis-cli monitor```

**Comment by juvyc** [comment]
I'm running that and it says...

`Could not connect to Redis at 127.0.0.1:6379: Connection refused`

Is it necessarily to work that IP and PORT on the server? Because on the codes I'm using different IP and PORT, it is 104.197.33.159:3000

:-(

**Comment by juvyc** [comment]
Here's on how I configured it.

```
 RedisOplog.init({
      redis: {
          port: 3000,          // Redis port
          host: '104.155.229.222' //|| "0.0.0.0"   // Redis host
      },
      debug: true, // default is false,
      overridePublishFunction: true // replaces .publish with .publishWithRedis, leave false if you don't want to override it
  });
```

I'm not sure what else need to do to make it working.

**Comment by ramezrafla** [comment]
Please look at the options for redis-cli to connect to the right redis server. Also, are you sure port 3000 is for redis? Aren't you developing on the standard port 3000 of meteor, and the default port of redis is 6379 (as per the error your are getting). You may want to go through the redis walkthrough first.

**Comment by ramezrafla** [comment]
You need to make sure redis is working as expected. e.g. telnet to the redis server and see if it responds. Use redis-cli as above to connect to it. Until that step is done, we can't confirm that the bug is from redis-oplog.

**Comment by juvyc** [comment]
I used '6379' port but still got the same issue. Let me try your suggestion using 'redis-cli'. Will post here the update.

**Comment by juvyc** [comment]
Ok how do I check if the port is for redis or not? And the IP should be the same with the IP of my domain name?

I have a feeling that this is the issue.

Thanks!

**Comment by juvyc** [comment]
I've fixed it, I need to run on different port. So I have to do:

`echo "port 4000" | redis-server -`

Thanks for the help anyway. :-)

**Comment by ramezrafla** [comment]
Right, your problem was not related to redis-oplog, this is why I directed you to resources that help you debug redis itself. Happy it was useful. Make sure to secure your ports in production. Good luck!
