### ISSUE TITLE
Using Validated Publications with RedisOplog

### ISSUE THREAD

**Issue by raphaelarias** [cult-of-coders/redis-oplog#104]
Hello, I'm sorry, I tried to find more info about it, but I couldn't.

Is it possible to use this package with the Validated Publications package?

Thank you very much,

**Comment by theodorDiaconu** [comment]
@raphaelarias yes, did you try it ? we override the .publish function.
So validated publications would most likely use Meteor.publish
=> It should work.

Did you try it and it did not work ?
