### ISSUE TITLE
Error in 1.1.6 with Collection that has "connection: null"

### ISSUE THREAD

**Issue by jamesgibson14** [cult-of-coders/redis-oplog#105]
Exception from sub meteor_autoupdate_clientVersions id fhm5Tp4pAMR8xeAut TypeError: Cannot read
property 'disableOplog' of undefined
  at packages/cultofcoders:redis-oplog/lib/utils/shouldPublicationBeWithPolling.js:11:29

https://github.com/meteor/meteor/blob/87681c8f166641c6c3e34958032a5a070aa2d11a/packages/autoupdate/autoupdate_server.js#L39

**Comment by theodorDiaconu** [comment]
excellent catch
