### ISSUE TITLE
Error on 1.1.6 with { '$set': { 'passengers.2.phone': '5555551456' } }

### ISSUE THREAD

**Issue by jamesgibson14** [cult-of-coders/redis-oplog#106]
The update works and other meteor servers get the update just fine, but the server that made the changes comes back with a null value to the client. Maybe because it can't get the topLevelField, because of the array index?

**Comment by theodorDiaconu** [comment]
@jamesgibson14 very strange behavior, they should be acting the same.

**Comment by theodorDiaconu** [comment]
anyway it's fixed. still don't know why it worked on other instances :)

**Comment by jamesgibson14** [comment]
Awesome, thanks you.
