### ISSUE TITLE
My "redis-oplog-test" repo don't work

### ISSUE THREAD

**Issue by thearabbit** [cult-of-coders/redis-oplog#107]
My [redis-oplog-test](https://github.com/thearabbit/redis-oplog-test) don't work.
(don't react data from pub/sub)
Please help me.

**Comment by theodorDiaconu** [comment]
@thearabbit are you sure redis is opened, check redis-cli, are you sure it works ?

**Comment by thearabbit** [comment]
Redis is OK with `$ redis-server`.
It don't work for react/realtime.
When I refresh page, it can get data.

**Comment by theodorDiaconu** [comment]
Do you have any errors ? Do you see any traffic to mongo ? What cursor you have ? What updates/changes are you making ?

**Comment by thearabbit** [comment]
Don't get error. I try to `add and remove` data.
For example: 
- the first time I click on `add message`one (in mongo have one record). 
- but it don't show anything on browser
![image](https://cloud.githubusercontent.com/assets/4495160/21930598/77213b96-d9c9-11e6-8c16-a9ddbf3bfb86.png)

- And then I click on `refresh page`, it show
![image](https://cloud.githubusercontent.com/assets/4495160/21930753/39f60d04-d9ca-11e6-90da-0da1376c40d7.png)

**Comment by thearabbit** [comment]
The cursor return when I refresh page in template helper
```js
LocalCollection.Cursor
_projectionFn
:
(obj)
_selectorId
:
undefined
_transform
:
null
collection
:
LocalCollection
fields
:
undefined
limit
:
undefined
matcher
:
Minimongo.Matcher
reactive
:
true
skip
:
undefined
sorter
:
null
__proto__
:
Object
```

**Comment by theodorDiaconu** [comment]
@thearabbit I don't see in your repo the functionality to add the message. If you do the insert from mongodb it won't work.

**Comment by thearabbit** [comment]
I do in `client`.
```js
// client/main.js

Template.hello.events({
    'click button'(event, instance) {
        Messages.insert({name: `My Message : ${new Date()}`});
    },
    'click .js-destroy'(event, instance) {
        Messages.remove(this._id);
    },
});
```

**Comment by thearabbit** [comment]
Have any solve for me.

**Comment by theodorDiaconu** [comment]
I will check it out, no worries.

**Comment by theodorDiaconu** [comment]
worked fine for me.

**Comment by thearabbit** [comment]
Thanks for your reply.
Could you check the [`redis-oplog-test`](https://github.com/thearabbit/redis-oplog-test) agin? It still don't work.
Or have any `example repo`?
Please help me.

**Comment by theodorDiaconu** [comment]
@thearabbit try again with a new repo, put redis-oplog, make sure 100% you have redis running on the configured port. I think that's the issue here. You do not have redis running ?

**Comment by thearabbit** [comment]
could you see this [gif](http://recordit.co/x5LEac6cPw)?

**Comment by theodorDiaconu** [comment]
@thearabbit that is so weird. your redis isn't receiving anything... I will take a look again.

**Comment by thearabbit** [comment]
Thanks again, waiting you...

**Comment by JanMP** [comment]
After having similar problems with my own project, I tried thearabbit's repo. It does not work for me either. Redis is definitely working and on the right port (redis-cli works fine and the prompt reads 127.0.0.1:6379> ). Also, when quit the redis server the app will crash. So it can't be a missing redis that's causing the problems, right?

And the problem is not in any other parts of thearabbit's code. When I remove the packages and the RedisOblog.init() and change 'publishWithRedis' back to 'publish' then everything works as it should.

**Comment by theodorDiaconu** [comment]
@JanMP @thearabbit 
Sorry for delayed response.
Does not work with 'insecure'. If you put Collection.allow({ insert: () => true }); It will work.

Cheers. 

Sorry but we cannot support insecure

**Comment by thearabbit** [comment]
Thanks, I will try again soon.

**Comment by thearabbit** [comment]
OK, now work fine.
👍
