### ISSUE TITLE
Error: Reactive publication bug

### ISSUE THREAD

**Issue by ramezrafla** [cult-of-coders/redis-oplog#110]
`Exception in queued task: Error: Removed nonexistent document TPsFhHaknugJSyzZM
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
    at Session.removed (packages/ddp-server/livedata_server.js:391:10)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1273:19)
    at Object.removed (packages/mongo/collection.js:352:11)
    at Object.removed (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:94:26)
    at packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:88:13
    at Array.forEach (native)
    at PublicationEntry.send (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:87:24)
    at ObservableCollection.send (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:115:9)
    at ObservableCollection.remove (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:227:18)
    at handleRemove (packages/cultofcoders:redis-oplog/lib/processors/direct.js:52:26)
    at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/processors/direct.js:14:13)
    at Object.task (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:55:28)
    at [object Object]._.extend._run (packages/meteor.js:807:18)
    at packages/meteor.js:785:14`

This happens when I remove content server-side. Without redis-oplog the same action does not trigger error. Note that we are using Ground:DB client-side and autorun in the publication server-side. We'll run some more tests without these two to see if they contribute to this issue.

**Comment by theodorDiaconu** [comment]
maybe a race-condition happening ?

**Comment by ramezrafla** [comment]
Any ideas what steps to debug this is what is happening?

**Comment by theodorDiaconu** [comment]
use redis debug true

**Comment by ramezrafla** [comment]
I traced it down to a race condition from a publish autorun (triggers a bug I raised before about non-existent element)

Here is the simplified publish
```
Meteor.publish('content', function() {
  if (!this.userId) return;  
  this.autorun(function() {
    var user = Meteor.users.findOne(this.userId,{fields:{'profile.content':1}});
    var content = user.profile.content;
    if (content) {
      return self.collection.find({_id:{$in:content}});
    }
  });
});
```

So when we remove the object from the collection THEN we remove it from the user's `profile.content`, we get these errors (there is a race-condition where `profile.content` has id's that are NOT in the collection).

We can get around it by modifying user's `profile.content` first, but other users will face this and won't understand where these errors come from.

**Comment by ramezrafla** [comment]
Race condition still persists sometimes after we alter `profile.content` first, strange .. but it's perceivable that the order of the changes can be out of sync when the reactive publish is triggered

**Comment by ramezrafla** [comment]
To properly document this issue in case someone else faces this, we created a repo to show how reactive publishing has issues with redis-oplog

https://github.com/ramezrafla/redisoplog-autorun-bug

**Comment by theodorDiaconu** [comment]
@ramezrafla tried your repo, called 'remove' from client-side a gazilion times. I could not get it to trigger on my end, anything special ?

**Comment by ramezrafla** [comment]
Should work out of the box - I am on the road will try it again tonight. No server or client logs?

**Comment by theodorDiaconu** [comment]
nothing, just redis debug, using 1.1.6

**Comment by ramezrafla** [comment]
Just relooked at the repo code - super simple method in server/main.js -- can't imagine what is wrong

**Comment by theodorDiaconu** [comment]
@ramezrafla it tells me "Method remove called", but exception isn't triggering

**Comment by ramezrafla** [comment]
There is no exception. It's a bug in output. I detailed in the repo readme. Is it not clear?

**Comment by theodorDiaconu** [comment]
@ramezrafla apologies, I only assumed it's for triggering exceptions, did not look at the readme, which indeed is very well explained. will investigate and solve today. thank you

**Comment by theodorDiaconu** [comment]
![screenshot from 2017-01-26 09-47-49](https://cloud.githubusercontent.com/assets/1814863/22323600/a9e22e22-e3ac-11e6-9998-e4047acde183.png)

**Comment by ramezrafla** [comment]
Beautiful! You are the best! Will test ASAP.
