### ISSUE TITLE
Strange issue on client with live data (Optimistic UI).

### ISSUE THREAD

**Issue by jamesgibson14** [cult-of-coders/redis-oplog#111]
Field1 = 'aaa'
When I run `Collection.update(id, {$set:{field1: 'bbb'}})` on the client the screen changes right away, then the method comes back from the server the the update was successful but, this line of code gets run:
https://github.com/meteor/meteor/blob/devel/packages/ddp-client/livedata_connection.js#L1452
which causes field1 to go back to 'aaa', then it switches to the new 'bbb', so the screen does a little flash on every update.

**Comment by theodorDiaconu** [comment]
@jamesgibson14 good find, this is because somehow optimistic UI got broke. will solve this

**Comment by jamesgibson14** [comment]
On Tue, Jan 17, 2017 at 2:57 AM, Theodor Diaconu <notifications@github.com>
wrote:

> find, this is because somehow optimistic UI got broke. will solve this


Awesome, thank you.

**Comment by theodorDiaconu** [comment]
solved in 1.1.7
