### ISSUE TITLE
Issue found when uploading

### ISSUE THREAD

**Issue by ClaudiuRoman** [cult-of-coders/redis-oplog#115]
When I try to upload an image, I receive the following exception:

> I20170119-16:37:58.631(2)? Exception in queued task: TypeError: Cannot read property 'findOne' of undefined
> I20170119-16:37:58.631(2)?     at ObservableCollection.isEligibleByDB (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:84:22)
> I20170119-16:37:58.633(2)?     at handleInsert (packages/cultofcoders:redis-oplog/lib/processors/default.js:30:73)
> I20170119-16:37:58.633(2)?     at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/processors/default.js:12:13)
> I20170119-16:37:58.635(2)?     at Object.task (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:55:28)
> I20170119-16:37:58.635(2)?     at [object Object]._.extend._run (packages/meteor.js:807:18)
> I20170119-16:37:58.635(2)?     at packages/meteor.js:785:14

For uploading, I'm using Dropzone
Meteor version: 1.4.2.3 
Template Engine: Blaze

**Comment by theodorDiaconu** [comment]
@ClaudiuRoman what is the collection are you subscribing to ? It is not related to frontend

**Comment by theodorDiaconu** [comment]
@ClaudiuRoman check with 1.1.7 if you still have issues with this.
