### ISSUE TITLE
Is Redis Cache Mode recommended? 

### ISSUE THREAD

**Issue by nadeemja** [cult-of-coders/redis-oplog#116]
Hi,

Do you recommend enable Cache Mode for Redis when using redis-oplog?

https://help.compose.com/docs/redis-cache-and-storage-modes

**Comment by theodorDiaconu** [comment]
no cache mode, we use pub/sub from redis only, no storage yet.

**Comment by nadeemja** [comment]
So it does not matter which mode it is set to?
