### ISSUE TITLE
How to use with publishComposite without override: true?

### ISSUE THREAD

**Issue by nadeemja** [cult-of-coders/redis-oplog#117]
Hello,

Any way to make a publishComposite publication into publishWithRedis without using the override?

**Comment by theodorDiaconu** [comment]
We override "observeChanges", therefore, it should work.

**Comment by nadeemja** [comment]
I'm sorry, I did not understand you.

Do you mean that I can simply rewrite Meteor.publishComposite({...}) into Meteor.publishWithRedis({...}) without changing whats inside {...} when "override: false" ?
