### ISSUE TITLE
«Exception from task: TypeError: Cannot read property 'selector' of undefined»

### ISSUE THREAD

**Issue by nadeemja** [cult-of-coders/redis-oplog#118]
Hi,

Using the latest version as of now.
This error occurs on localhost, but only if debug: false.

[Main] New incomming subscription for publication: meteor_autoupdate_clientVersions
I20170120-17:01:18.242(1)? Exception from task: TypeError: Cannot read property 'selector' of undefined
I20170120-17:01:18.242(1)?     at PublicationFactory.getPublicationId (packages/cultofcoders:redis-oplog/lib/cache/PublicationFactory.js:52:26)
I20170120-17:01:18.242(1)?     at PublicationFactory.create (packages/cultofcoders:redis-oplog/lib/cache/PublicationFactory.js:21:23)
I20170120-17:01:18.242(1)?     at packages/cultofcoders:redis-oplog/lib/publishWithRedis.js:40:40
I20170120-17:01:18.243(1)?     at Array.forEach (native)
I20170120-17:01:18.243(1)?     at packages/cultofcoders:redis-oplog/lib/publishWithRedis.js:38:21
I20170120-17:01:18.243(1)?     at runWithEnvironment (packages/meteor.js:1176:24)
I20170120-17:01:18.243(1)?     at Object.task (packages/meteor.js:1189:14)
I20170120-17:01:18.243(1)?     at [object Object]._.extend._run (packages/meteor.js:807:18)
I20170120-17:01:18.243(1)?     at packages/meteor.js:785:14
I20170120-17:01:18.459(1)? Exception from sub meteor_autoupdate_clientVersions id rY4SqSm95qNxcDSHq TypeError: Cannot read property 'selector' of undefined
I20170120-17:01:18.460(1)?     at Object.Future.wait (/Users/Nadeem/.meteor/packages/meteor-tool/.1.4.2_3.15jbrmv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20170120-17:01:18.460(1)?     at [object Object]._.extend.runTask (packages/meteor.js:741:9)
I20170120-17:01:18.460(1)?     at Subscription.<anonymous> (packages/cultofcoders:redis-oplog/lib/publishWithRedis.js:37:34)
I20170120-17:01:18.460(1)?     at packages/matb33_collection-hooks.js:307:21
I20170120-17:01:18.461(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170120-17:01:18.461(1)?     at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
I20170120-17:01:18.461(1)?     at packages/check.js:130:16
I20170120-17:01:18.461(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170120-17:01:18.461(1)?     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
I20170120-17:01:18.462(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1708:18)
I20170120-17:01:18.462(1)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
I20170120-17:01:18.462(1)?     at Subscription.subscriptionProto._runHandler (packages/meteorhacks_kadira.js:2781:24)
I20170120-17:01:18.462(1)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20170120-17:01:18.462(1)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20170120-17:01:18.463(1)?     at packages/meteorhacks_kadira.js:2644:34
I20170120-17:01:18.463(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170120-17:01:18.463(1)?     - - - - -
I20170120-17:01:18.463(1)?     at PublicationFactory.getPublicationId (packages/cultofcoders:redis-oplog/lib/cache/PublicationFactory.js:52:26)
I20170120-17:01:18.463(1)?     at PublicationFactory.create (packages/cultofcoders:redis-oplog/lib/cache/PublicationFactory.js:21:23)
I20170120-17:01:18.464(1)?     at packages/cultofcoders:redis-oplog/lib/publishWithRedis.js:40:40
I20170120-17:01:18.464(1)?     at Array.forEach (native)
I20170120-17:01:18.464(1)?     at packages/cultofcoders:redis-oplog/lib/publishWithRedis.js:38:21
I20170120-17:01:18.464(1)?     at runWithEnvironment (packages/meteor.js:1176:24)
I20170120-17:01:18.464(1)?     at Object.task (packages/meteor.js:1189:14)
I20170120-17:01:18.464(1)?     at [object Object]._.extend._run (packages/meteor.js:807:18)
I20170120-17:01:18.464(1)?     at packages/meteor.js:785:14«Exception from task: TypeError: Cannot read property 'selector' of undefined»

**Comment by nadeemja** [comment]
PS.

Just adding this package (properly configured, but override:false) cause the above error.

**Comment by nadeemja** [comment]
Tested with 1.1.5 which works perfectly. Only 1.1.6 is problematic.

**Comment by nadeemja** [comment]
Also getting this client side with 1.1.6
[localhost-1484929790219.txt](https://github.com/cult-of-coders/redis-oplog/files/719899/localhost-1484929790219.txt)

**Comment by theodorDiaconu** [comment]
Thanks! Will take care

**Comment by theodorDiaconu** [comment]
Fixed in 1.1.7
