### ISSUE TITLE
Create a docker container with Redis + MongoDB + Meteor

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#12]

**Comment by hexsprite** [comment]
it would be better if you use docker compose and have separate containers for each one

**Comment by jantrienes** [comment]
I'm interested in working on this issue. Can you provide more info on what exactly you had in mind? As @hexsprite pointed out, a docker-compose file would be nice no have. 

With respect to a meteor docker image, I experienced that [`meteor-launchpad`](https://github.com/jshimko/meteor-launchpad) works quite well. The mongo and redis images should work out of the box.

**Comment by theodorDiaconu** [comment]
@jantrienes I think this task is no longer needed, because this is strictly related to the way you deploy. For example mup, creates another docker container for mongodb, this is how I envisioned it at first.

**Comment by hexsprite** [comment]
it would be really useful for development as well but, true, it's very application specific

**Comment by janat08** [comment]
https://github.com/tozd/docker-meteor already has mongo/meteor/nginx with ssl.

**Comment by theodorDiaconu** [comment]
there are alternatives to this. would not really be that valuable.
