### ISSUE TITLE
 Error: Could not find element with id <> to change

### ISSUE THREAD

**Issue by ramezrafla** [cult-of-coders/redis-oplog#122]
```
I20170126-18:50:03.075(-5)? Exception in queued task: Error: Could not find element with id DRvHgfyEF6HEFBep8 to change
I20170126-18:50:03.076(-5)?     at SessionCollectionView.changed (packages/ddp-server/livedata_server.js:188:13)
I20170126-18:50:03.076(-5)?     at Session.changed (packages/ddp-server/livedata_server.js:400:10)
I20170126-18:50:03.077(-5)?     at Subscription.changed (packages/ddp-server/livedata_server.js:1254:19)
I20170126-18:50:03.077(-5)?     at Object.changed (packages/mongo/collection.js:349:11)
I20170126-18:50:03.077(-5)?     at Object.changed (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:90:26)
I20170126-18:50:03.079(-5)?     at packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:88:13
I20170126-18:50:03.080(-5)?     at Array.forEach (native)
I20170126-18:50:03.080(-5)?     at PublicationEntry.send (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:87:24)
I20170126-18:50:03.080(-5)?     at ObservableCollection.send (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:129:9)
I20170126-18:50:03.080(-5)?     at ObservableCollection.change (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:192:14)
I20170126-18:50:03.080(-5)?     at handleUpdate (packages/cultofcoders:redis-oplog/lib/processors/direct.js:42:34)
I20170126-18:50:03.081(-5)?     at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/processors/direct.js:12:13)
I20170126-18:50:03.081(-5)?     at Object.task (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:53:13)
I20170126-18:50:03.081(-5)?     at [object Object]._.extend._run (packages/meteor.js:807:18)
I20170126-18:50:03.081(-5)?     at packages/meteor.js:785:14
```

Here is what is happening: we have removed the document with id above (DRvHgfyEF6HEFBep8) from the publication cursor - the doc still exists in the collection, but is no longer sent to this client, due to reactive change (using this.autorun in the publication)

**Comment by theodorDiaconu** [comment]
This autorunning gives us a lot of headache :( I think the solution lies in understanding fully how it works. Like I did for publish composite.

**Comment by ramezrafla** [comment]
Feel bad ... I could spend the team to understand it better and we could have a call to brainstorm?

**Comment by theodorDiaconu** [comment]
That would be great, here is what the error means:

It means that somehow by other means, the document has been removed from the publication without that event going through ObservableCollection.

Either that or a race-condition, somehow, I have no idea how:
1. Update -> check if it exists, and returns true
2. Executed Document removal 
3. Change event sent to the publication -> error.

Question is, how can we reproduce this, once we reproduce it, it's easy from that point. If you can find a way that I can reproduce this, then I will solve it very quickly.

**Comment by theodorDiaconu** [comment]
@ramezrafla can you try it again with 1.1.8 I think I may have fixed it while I fixed something for publishComposite which was related to observeChanges which reactive-publish uses intensively. Pls re-open if that's not the case. Cheers!
