### ISSUE TITLE
Request: Detailed example of Synthetic Mutations "(somebody is typing a reply)"

### ISSUE THREAD

**Issue by nadeemja** [cult-of-coders/redis-oplog#123]
Hi,

I love the idea of Synthetics mutation, but I'm not quite sure I see how to use them.

For example, I have two collections: Questions and Comments. A Comments document would have two fields: questionId and body. 

In a list of questions, how would I mark a specific question with "being answered right now"?

**Comment by theodorDiaconu** [comment]
Good idea, we will be doing that soon. Will keep this issue opened and push updates here.

**Comment by nadeemja** [comment]
Awesome, Theodor. I appreciate it very much! :) 

PS. One of our clients are requesting the "somebody is typing" functionality with some sense of urgency. Please let me know if I could pay some fee to push this higher up on your priorities list.

**Comment by theodorDiaconu** [comment]
```
Call a method which does the following:

SyntheticMutator.update(MessagesCollection, messageId, { $addToSet: { typers: userId } });
SyntheticMutator.update(MessagesCollection, messageId, { $pull: { typers: userId } });
```
