### ISSUE TITLE
$unset not working?

### ISSUE THREAD

**Issue by dnish** [cult-of-coders/redis-oplog#131]
I'm having a server side method with the following code:

```
let updateObj = (isTyping) ? {$set: {'profile.isTyping': 1}} : {$unset: {'profile.isTyping': ''}};
Meteor.users.update(Meteor.userId(), updateObj);
```

The problem is that redis-oplog doesn't reflect that change, <code>profile.isTyping</code> is still available on the client side. redis-oplog sets it to null instead of removing it.

So I I do this on the client side:

     Meteor.users.findOne(this.foreignUser()).profile.hasOwnProperty('isTyping')

I will get always true, because the field isn't removed. It works without problems on MongoDB + Oplog.

**Comment by dnish** [comment]
Okay, it seems like the update isn'r reflected on the client. <code>profile.isTyping</code> is set to 1, even if it was unset and the debugger showed an update for this user.

**Comment by theodorDiaconu** [comment]
@dnish what would help me a lot would be a reproduction repo

We already have a passing test for $unset:
https://github.com/cult-of-coders/redis-oplog/blob/master/testing/main.client.js#L964

**Comment by dnish** [comment]
@theodorDiaconu I guess the problem is not <code>$unset</code>. I've tried it by doing <code>$set:{'profile.isTyping':false}</code>. The change isn't reflected at the other user, the user object has still the old value (<code>profile.isTyping:true</code> - checked via console). But redis-oplog logs the change on the server side (debug:true). 

I'll check if I can reproduce it within a new repo, but if I remove redis-oplog, everything is working fine again.

**Comment by dnish** [comment]
@theodorDiaconu I've created a repo here: https://github.com/dnish/redis-oplog-issue


How to reproduce:

1. Open 2 windows (one in private mode to simulate 2 clients)
2. Create a account in each window and connect to the others user id
3. Start typing. You should see a "Is typing" message on the other side.
4. Stop typing, after 5 seconds the timeout should fire and the message will be hidden.
5. Start typing again, the update isn't reflected on the other user. He will not see a "is typing" message.

**Comment by theodorDiaconu** [comment]
@dnish thank you for your detailed information. I have enough information to fix.

**Comment by theodorDiaconu** [comment]
Oh my god. After squeezing my brains for 2 hours on this one I found it. When I'm overriding observeChanges I need to pass in a clone, not an object. Bc if I pass it as reference, publishComposite does not detect any changes here:

https://github.com/englue/meteor-publish-composite/blob/master/lib/subscription.js#L66

Nice bug. 
Solved.
