### ISSUE TITLE
Different behavior with reactive sources

### ISSUE THREAD

**Issue by dnish** [cult-of-coders/redis-oplog#137]
We've recognized a behavior which is different to the normal one with Meteors live data system when we use a reactive source.

We're using ViewModel within our app and defined the following functions:

```
// Reactive source within ViewModel:

profilePicture() {

        if (Meteor.user() && Meteor.user().profile.picture) return "https://files.myapp.com/profile-pictures/" + Meteor.user().profile.picture;

        return null;
    },

// Autoruns
 function () {
            // Sync data with forms
            if (Meteor.user() && Meteor.user().profile) {
                this.gender(Meteor.user().profile.gender);
                this.s_gender(Meteor.user().profile.s_gender);
            }
        },

        function() {
            // Check if ready but user forgot to create a profile picture

            if(this.gender() && this.s_gender() && !this.profilePicture()) {
                this.templateInstance.$(".pp-preview").click();
            }
        }
```

At the same time, we sending a ping to the server every 20 seconds. Now we have the following problem: The last autorun is fired every 20 seconds, when the <code>Meteor.user()</code> object changes (we update the <code>status.lastPing</code> field which is NOT published to the client). So our users will see a modal for taking a profile picture every 20 seconds. This behavior doesn't exists when we deactivate redis-oplog and use the normal live data system of Meteor (dev mode). 

If we remove <code>this.profilePicture()</code> and change the if statement to

```
   if(this.gender() && this.s_gender()) {
                this.templateInstance.$(".pp-preview").click();
    }
```
the modal doesn't show up every 20 seconds. So I try to understand why we have the issue with redis-oplog and not with the normal Meteor system? Is it possible that even unpublished fields will trigger a rerun when using redis-oplog?

**Comment by dnish** [comment]
Just checked it also with a Tracker.autorun within my browser console:

    Tracker.autorun(function() { console.log(Meteor.user());});


Fires every 20 seconds with <code>redis-oplog</code>. Without it, it fires only once.

**Comment by theodorDiaconu** [comment]
@dnish can you do a quick reproduction repo ? Cheers

**Comment by dnish** [comment]
@theodorDiaconu Yeah, I've created a repo:

https://github.com/dnish/redis-oplog-issue-reactivity

Steps:

1. Open browser console. You should just see 1 "received ping" message, because the updated field <code>updatedAt</code> isn't published.
2. Uncomment <code>RedisOplog.init();</code> within server/main.js 
3. Refresh the browser - now you should get every 5 seconds a ping message within console - but this shouldn't happen because <code>uploadedAt</code> isn't published to the client.

**Comment by theodorDiaconu** [comment]
@dnish thank you very much, will solve it.
