### ISSUE TITLE
Expose a way to listen to redis messages (?)

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#140]
That's it only which fields change, that's it, no store.

**Comment by jamesgibson14** [comment]
Is there a way to expose globally some of the main components like RedisSubscriptionManager, RedisClient, etc.?

**Comment by theodorDiaconu** [comment]
@jamesgibson14 we could do that, sure.

**Comment by theodorDiaconu** [comment]
We now export getRedisListener, getRedisPusher so you can hook directly into Redis.
