### ISSUE TITLE
Deploying with MUP while you are on the host.

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#144]
It will start refreshing like crazy. Do not know if redis-oplog related, but it started happening after redis-oplog was installed.

**Comment by rajpa** [comment]
Did you install meteorhacks cluster package? Sometimes happens with that package...

**Comment by theodorDiaconu** [comment]
@rajpa no idea really, if I keep my browser open, and deploy in background, the browser goes crazy, i really have no clue

**Comment by theodorDiaconu** [comment]
This is mup related.
