### ISSUE TITLE
Bug in 1.2.0 [Urgent]: Invalid event specified

### ISSUE THREAD

**Issue by nadeemja** [cult-of-coders/redis-oplog#147]
Hi! 

I'm getting this error:

Error: [Invalid event specified: i]
    at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/processors/direct.js:18:19)
    at RedisSubscriber.processSync (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:65:9)
    at packages/cultofcoders:redis-oplog/lib/mongo/lib/compensateForLatency.js:32:28
    at Array.forEach (native)
    at packages/cultofcoders:redis-oplog/lib/mongo/lib/compensateForLatency.js:31:24
    at Array.forEach (native)
    at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/mongo/lib/compensateForLatency.js:13:14)
    at dispatchInsert (packages/cultofcoders:redis-oplog/lib/mongo/lib/dispatchers.js:62:9)
    at [object Object].insert (packages/cultofcoders:redis-oplog/lib/mongo/Mutator.js:31:13)
    at [object Object]._.extend.insert (packages/cultofcoders:redis-oplog/lib/mongo/collection.extension.js:34:35)
    at [object Object].validatedInsert [as _validatedInsert] (packages/cultofcoders:redis-oplog/lib/mongo/allow-deny/validatedInsert.js:22:10)
    at [object Object].m.(anonymous function) (packages/allow-deny/allow-deny.js:171:46)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)

Check it out at this url:
https://app.sembly.no/joinAnonymously/53M5u9B3qPggFxhZk

**Comment by nadeemja** [comment]
Please see this Kadira log:
https://ui.kadira.io/et/20ec634f-0c45-440e-a4f9-7c6a74b735dc/JZM5Li9QMezk3F9iZ

**Comment by theodorDiaconu** [comment]
@nadeemja this is very weird, because direct processing happens only when you are querying for specific id's, so i ("INSERT") cannot be there, unless either there's a bug somewhere, or you hard-code the id when you enter it ?

Show me your publication please :)

**Comment by nadeemja** [comment]
Hi @theodorDiaconu! 

I have added you to my repo nadeemja/Sembly. The relevant publication is in _server/publications/questionsPublications.js

The relevant publication is this one: 


    Meteor.publishComposite(
      'studentQuestionsForSchedule',
      function pubStudentQuestionsForSchedule(scheduleId, sortOptions) {
        check(scheduleId, String);
        check(sortOptions, {
          order: Number,
          field: String,
        });

        const { field, order } = sortOptions;


        if (!this.userId) {
          return this.ready();
        }

        const user = Users.findOne({ _id: this.userId });

        if (!user) {
          return this.ready();
        }
        const query = {
          schedule_id: scheduleId,
          userType: 'student',
        };
        if (!user.isLecturer(scheduleId)) {
          query.$or = [{
            visibleToOthers: {
              $ne: false,
            },
          }, {
            user_id: this.userId,
          }];
        }

        return {
          find() {
            return Questions.find(query, {
              sort: { [field]: order },
            });
          },
          children: [{
            find(question) {
              return Users.find(question.user_id);
            },
          }],
        };
      });

In our app, a "question" is a regular question if it comes from a student, but a "discussion" that must be manually set to visible if it comes from a lecturer.

Also, the issue seems to be intermittent. Sometimes it comes, sometimes it does not. To (try to) replicate it:

1. Go here: https://app.sembly.no/joinAnonymously/53M5u9B3qPggFxhZk

2. Create anonymous account.

3. "Go to ..."

4. Press the blue Ask-button on the bottom. Write something and press enter.

5. Watch the console.

Other relevant code might be in the server/collectionHooks folder.

**Comment by theodorDiaconu** [comment]
@nadeemja ohh so you're using publishComposite, ok, i will find time in the next 2 days to solve this issue. cheers

**Comment by nadeemja** [comment]
Thank you @theodorDiaconu :)

**Comment by theodorDiaconu** [comment]
@nadeemja solved. check it with my new PR, you can just use that branch, tell me if it's solved, I still want to tackle other things for 1.2.1

**Comment by nadeemja** [comment]
Very nice, man! I'm going to test this in a day or two and let you know :) 

Would love to hear your theory on why this was happening and why publishComposite is part of the explanation.

**Comment by theodorDiaconu** [comment]
@nadeemja it wasn't related to publishComposite. you should follow up on the thread here to see why I thought it was publishComposite: https://github.com/cult-of-coders/redis-oplog/issues/145

**Comment by nadeemja** [comment]
Cool. I'm reading it now. 

For some reason git cloning into /packages is giving me trouble and I don't want to fight it right now.

Do you mind releasing a 1.2.1-beta?

**Comment by theodorDiaconu** [comment]
Published cultofcoders:redis-oplog@1.2.1-beta.

**Comment by nadeemja** [comment]
Thanks. I've pushed to production and everything looks good! :)

**Comment by nadeemja** [comment]
I tested this with the same users as last time, and everything works :)
