### ISSUE TITLE
Optimistic option being overriden

### ISSUE THREAD

**Issue by jamesgibson14** [cult-of-coders/redis-oplog#148]
I tried to do a `Records.update({},{},{optimistic: false})` from the client but I believe it is getting overridden here:
https://github.com/cult-of-coders/redis-oplog/blob/master/lib/mongo/allow-deny/validatedUpdate.js#L120

**Comment by theodorDiaconu** [comment]
@jamesgibson14 isn't that how it would be expected ? Can you tell me your use-case, why would you want it disabled ?

**Comment by jamesgibson14** [comment]
I though the optimistic option was there to toggle it on and off if needed, however line 120 make it always true.
My use case is: I want to use redis oplog, but if I turn off optimitic I get the flashing client screen, if I turn it on I get very very long method wait times, I am not sure what to do?

**Comment by theodorDiaconu** [comment]
@jamesgibson14 you use publishComposites ? If yes, do you use our publish-composite ? https://github.com/cult-of-coders/redis-oplog/blob/master/docs/optimistic_ui.md

Which is publish-composite + 1 line of code to properly identify the subscriber

**Comment by theodorDiaconu** [comment]
@jamesgibson14 in next big release I will eliminate this necessity, I already know how to solve this, without the necessity of a custom publish-composite package. But this will give you much much faster response times.

**Comment by jamesgibson14** [comment]
I dont use the composite package, but i do use hooks and that seems to
affect it. Thank you for all the hard work you are doing on this.

**Comment by theodorDiaconu** [comment]
@jamesgibson14 but your collection hooks are on the client-side ?

**Comment by jamesgibson14** [comment]
No they are only on the server side.  I have some updates that trigger 5-10 other find, update, and insert. When using redis-oplog the original update has to wait for all of those other updates to finish before replying to the client, which isn't the case without redis-oplog

**Comment by theodorDiaconu** [comment]
@jamesgibson14 if they are on server-side, then you can pass optimistic: false, it won't force it. What you saw there in "validatedUpdate" is for isomorphic client-side updates, as in, if you do client-side:

```X.insert/update/remove(args)``` - It will run on the server-side with `optimistic: true`

But I see your point... I could try a different approach to optimistic-ui as-in: make it naive for updates and removes. Then when the redis message will hit the processor it will update it with the correct data from db.

**Comment by theodorDiaconu** [comment]
This has already been solved.
