### ISSUE TITLE
Don't reactive/realtime when use "Direct access of Collection Hook"

### ISSUE THREAD

**Issue by thearabbit** [cult-of-coders/redis-oplog#150]
Don't reactive/realtime, when use `direct access of collection hook`
```js
collection.direct.update({_id: "test"}, {$set: {test: 1}});
```

**Comment by theodorDiaconu** [comment]
@thearabbit , why not ?

**Comment by thearabbit** [comment]
I have `Order Collection: {...., total:1000}`.
And then I update `total field` by `collection.direct.update()`.
On view
```js
// createContainer
........
// Page
render(){
   return (
      <div>
          <Button>Update Total for Testing </Button>
          Total: {order.total}
      </div>
   );
}
```

**Comment by theodorDiaconu** [comment]
But this is not related to this package, why not easily modify the .direct hook and just make it send data with { pushToRedis: false }

**Comment by theodorDiaconu** [comment]
Please do override the .direct function yourself, this package cannot override what other packages do, and it truly feels like a custom need.
