### ISSUE TITLE
Using Meteor.defaultPublish prevents other packages to patch publish used by redis

### ISSUE THREAD

**Issue by mitar** [cult-of-coders/redis-oplog#151]
Hm, you are doing `Meteor.defaultPublish = Meteor.publish` which means that if any other package patches `Meteor.publish` after this package is loaded, that will not be used inside `Meteor.publishWithRedis` because it is using old (unchanged) `Meteor.defaultPublish`.

BTW, I made a [package with a helper to easier extend Meteor.publish](https://github.com/peerlibrary/meteor-extend-publish).

**Comment by mitar** [comment]
Oh, this is in fact not a problem for this package. It is the same as using local variable to remember previous value, you just use a global variable. The only issue is that if anyone else will start using `Meteor.defaultPublish`, that will not be patched with packages coming after this package, but will be patched with packages coming before this package.

**Comment by theodorDiaconu** [comment]
@mitar nice! got it.

**Comment by theodorDiaconu** [comment]
@mitar Meteor.defaultPublish should be an internal variable and not overridable. I'm going to solve the issue like that for now.

**Comment by mitar** [comment]
Maybe rename it to `Meteor._defaultPublish` then?

**Comment by theodorDiaconu** [comment]
I no longer store it inside Meteor object. No need to.

**Comment by mitar** [comment]
Exactly.
