### ISSUE TITLE
Transformations are not working

### ISSUE THREAD

**Issue by dnish** [cult-of-coders/redis-oplog#154]
Hey @theodorDiaconu,
it seems like that transformations doesn't work. We are depending heavily on them, since we need to add some sub documents to an published document. When we initialize Redis-Oplog (in production), every transformation stops working. If we go back to dev, everything is working fine again. 

You can publish some data like this:

      // Publish
      return Meteor.users.find({_id: this.userId}, {fields: {'test':1},transform: test});

    // Transform function

    function test(doc) {
      doc.test = 1;
      return doc;
    }

This won't work with Redis-Oplog. The field "test" won't be available on the client.

BTW: We're using publishComposite.

**Comment by theodorDiaconu** [comment]
@dnish isn't transform function applied client-side only ?

**Comment by dnish** [comment]
@theodorDiaconu  I don't think so, transformations are also added on server side. The only difference I made is to enable/disable Redis-oplog. If it is enabled, transformations are not added to my user doc. If I disable it, they are added again to the doc.  Tested in dev and production.

**Comment by theodorDiaconu** [comment]
@dnish but when you query them client-side, do you use "transform" ?

**Comment by dnish** [comment]
@theodorDiaconu We don't use transform on client side, because the client hasn't the data for the sub documents (we don't publish it to the client). So for example, we publish something like this:

```
function extendUser(doc) {
    doc.subDocs = {};
    doc.subDocs.packageDoc = Packages.findOne({_id: 'new'});
    return doc;
}

Meteor.publish("user",function() {
    return Meteor.users.find({_id: this.userId},{transform: extendUser});
});
```

On client side (React Native application), we only need to call <code>Meteor.user()</code> to receive the object, or we can do <code>Meteor.users.findOne({_id: Meteor.userId()});</code>. And here is the difference between Redis-Oplog and the standard live data system. If we enable Redis-Oplog, we only receive the pure database document, without any modification that was made by the transformation. If we disable it, we get the modified/transformed version on the client.

**Comment by theodorDiaconu** [comment]
@dnish I had no clue meteor behaves like this and I'm very happy you showed me this. Ok will write a test and fix it. It should be quick
