### ISSUE TITLE
$elemMatch projection on fields. Offer support for that?

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#159]

**Comment by theodorDiaconu** [comment]
I have no idea what I meant.

**Comment by theodorDiaconu** [comment]
@evolross I have no idea. Just wrote a test for $elemMatch that passes: 
https://github.com/cult-of-coders/redis-oplog/blob/feature/redis-vent/testing/main.client.js#L1113

**Comment by anschutz** [comment]
Minimongo doesn't support `$elemMatch` and `$` projection operators in queries, thus we can't make use of Mongo Oplog. Can you confirm that both work in Redis Oplog?

**Comment by theodorDiaconu** [comment]
@anschutz can you provide me with a concrete use-case ?

**Comment by anschutz** [comment]
For example, the following two queries will not be able to make use of Mongo Oplog in a regular publication:
`Collection.find(teamId, { fields: { name: true, users: { $elemMatch: { _id: this.userId } } } });`
`AnotherCollection.find({ 'sharedByUrl.hash': hash }, { fields: { title: true, 'sharedByUrl.$': true } });`

**Comment by theodorDiaconu** [comment]
I see, I think it's quite easy to do this.

Basically I need to transform the fields projection (which happens in ObservableCollection) into projecting users: 1 and sharedByUrl: 1

So basically just transforming field: Object, into field: 1, and 'field.$': 1 into field: 1. And storing this special fields somewhere.

Then when the document is changed, figure out these changes, and create another function applySpecialFields which does what Mongo Oplog does. 

It can get tricky though. But all in all it's possible.

**Comment by anschutz** [comment]
Yeah, at least something like that. In my case array projection is more or less a security measure. In the example with `this.userId` I'm trying to filter out the rest of the users in the same array

**Comment by theodorDiaconu** [comment]
@anschutz I see, you know that you can do this by using a transform:
 
Inside publication:
return Something.find({}, { transform(doc) { return doc; } })

**Comment by anschutz** [comment]
Yeah, exactly. But the transform affects the performance significantly, so I'd rather avoid it

**Comment by theodorDiaconu** [comment]
@anschutz they do, indeed... well, it can take some time to properly develop this. Are you interested in doing a PR? I can point you in the right direction. I'm going to create another issue related to this, it's very interesting.

**Comment by anschutz** [comment]
I'm yet to try the package itself. My intention was to use that as an alternative to mongo oplog on the production app. I will see what I can do as soon as I plug it in (maybe in a couple of weeks).

**Comment by theodorDiaconu** [comment]
@anschutz I looked into this issue more carefully, and these type of queries are not that rare, it seems very do-able, you can have reactivity to these reactive fields.
