### ISSUE TITLE
Is server-autorun supported?

### ISSUE THREAD

**Issue by MaxShv** [cult-of-coders/redis-oplog#163]
I am getting the following error:

{ stack: 'TypeError: self.autorun is not a function\n    at [object Object].collection (imports/api/actions/server/publications.js:91:7)\n    at [object Object].<anonymous> (packages/cultofcoders:redis-oplog/lib/publishWithRedis.js:24:23)\

**Comment by theodorDiaconu** [comment]
@MaxShv I know what the issue is here, and will fix it. It will be supported.

**Comment by MaxShv** [comment]
Great!

**Comment by MaxShv** [comment]
Hi @theodorDiaconu - any update on this one?

**Comment by theodorDiaconu** [comment]
https://github.com/cult-of-coders/redis-oplog/issues/143 this is the issue that I have to fix to support this. I will handle it as soon as I get some free time.
