### ISSUE TITLE
Errors after upgrading

### ISSUE THREAD

**Issue by dnish** [cult-of-coders/redis-oplog#164]
Hey,
after upgrading to 

    mongo@1.1.20
    npm-mongo@2.2.30

I get some wrong states on the client side (f.e. the user closes the subscription and still sees some of the old messages). I don't really know if this is related to this package or may be a core problem. Maybe someone has a similar issue?

**Comment by theodorDiaconu** [comment]
@dnish what errors ? can you help us reproduce it ?

**Comment by dnish** [comment]
It's something with the subscription data. For example we have a random chat like Omegle. If the user skips to the next user, all old messages are deleted from the screen (because we are stopping the old subscription). But after upgrading, the messages are still there. I'll try to reproduce in on a local machine and check, if the error occurs only when redis-oplog is enabled.

**Comment by theodorDiaconu** [comment]
@dnish if you provide me with a reproduction repo, then I will be able to fix it. Even something small.

**Comment by dnish** [comment]
Hey @theodorDiaconu,
I've checked it with the latest Meteor updates:

```
ecmascript                 upgraded from 0.8.1 to 0.8.2
ecmascript-runtime-client  upgraded from 0.4.2 to 0.4.3
localstorage               upgraded from 1.1.0 to 1.1.1
manuel:viewmodel           upgraded from 6.3.0 to 6.3.2
meteor                     upgraded from 1.7.0 to 1.7.1
mongo                      upgraded from 1.1.19 to 1.1.22
npm-mongo                  upgraded from 2.2.24 to 2.2.30
```

Couldn't reproduce it. It seems to work fine again :).

**Comment by theodorDiaconu** [comment]
@dnish I feel much much better. I wonder what was the actual issue... oh well let's leave it for now.
