### ISSUE TITLE
About the expected behaviour when changing value of a field

### ISSUE THREAD

**Issue by raphaelarias** [cult-of-coders/redis-oplog#168]
Just a question about a behaviour that I'm not sure if it's the designed one.

For example: We have a list of "clients". When we update a document that makes it appear or disappear from this list (given the PUB query) it works perfectly, but when we change a field, for example, the name of this client, it's not updated in the UI (but the log shows the "u" event was received for this pub).

Does that make sense? Is this correct? I'm asking this because I think I may be missing something.

**Comment by theodorDiaconu** [comment]
@raphaelarias please file a reproduction repo for your use case, something quick, so I can identify the bug. It's definitely not expected :) Thanks!

**Comment by theodorDiaconu** [comment]
@raphaelarias can you help me identify the issue ? Thanks!

**Comment by raphaelarias** [comment]
Oh man, sorry. I think I saw the notification and I thought that I would have answered.

As you said the mission isn’t over, so yes I can. Today I’ll take a look on this again, and possibly implement the tests for the pull request.

**Comment by theodorDiaconu** [comment]
ping @raphaelarias , no rush just don't forget :D

**Comment by raphaelarias** [comment]
I've started the tests.

**Comment by theodorDiaconu** [comment]
@raphaelarias let's kill this bug. help me out with more details.

**Comment by raphaelarias** [comment]
I'm deploying to QA to test it.

**Comment by raphaelarias** [comment]
I'm double checking because I'm having this thrown in the console:

Exception in queued task: TypeError: Cannot use 'in' operator to search for 'lastLogin' in undefined
at process (packages/cultofcoders:redis-oplog/lib/cache/lib/processUndefined.js:9:15)
at process (packages/cultofcoders:redis-oplog/lib/cache/lib/processUndefined.js:14:13)
at fields.forEach.field (packages/cultofcoders:redis-oplog/lib/cache/lib/processUndefined.js:3:9)
at Array.forEach (<anonymous>)
module.exportDefault (packages/cultofcoders:redis-oplog/lib/cache/lib/processUndefined.js:2:12)
at ObservableCollection.change (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:194:9)
at handleUpdate (packages/cultofcoders:redis-oplog/lib/processors/direct.js:43:34)
at packages/cultofcoders:redis-oplog/lib/processors/direct.js:12:13
at Object.queue.queueTask [as task] (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:53:28)
at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:819:16)
at packages/meteor.js:796:12

I can see with the debug flag set to true that it's working, but this one above is failing.

**Comment by theodorDiaconu** [comment]
@raphaelarias always try to show me your publication, how you subscribe and when it happens. I believe I know the issue here.

**Comment by theodorDiaconu** [comment]
@raphaelarias I might have fixed pls clone it locally, and go to release/1.2.3 branch to see if it still occurs.

**Comment by raphaelarias** [comment]
Ok, let me try. In this case I don't "manage" this field. It's probably a package, so I haven't created any pub/sub regarding this directly.

**Comment by theodorDiaconu** [comment]
@raphaelarias can you show me the packages that you use ? I tried to break it with a test, but couldn't.

**Comment by theodorDiaconu** [comment]
@raphaelarias are you using a meteor user status ?
https://github.com/mizzao/meteor-user-status
or 
https://github.com/VeliovGroup/Meteor-user-status

Would be helpful if this continues to tell me all the packages that you use. And also did you put redis-oplog on top ?

**Comment by raphaelarias** [comment]
Yes. I'm using it, from Mizzao. But I think I'll stop using it. It's somewhat expensive and we're not using.

**Comment by theodorDiaconu** [comment]
True they are a bit expensive, constantly sending heart beats...
