### ISSUE TITLE
Is this still being actively developed?

### ISSUE THREAD

**Issue by Pagebakers** [cult-of-coders/redis-oplog#169]
I've had really high hopes for this package, but it's been rather quiet since April.

First tests on our environment are successful, but I'm a bit reluctant te transition this to our production environment due to the inactivity.

Is this still being actively developed?

**Comment by evolross** [comment]
Hopefully he's busy with integration fully into Meteor with MDG! One can hope.

**Comment by theodorDiaconu** [comment]
@Pagebakers @evolross 
It is and I will continue to maintain it.

I'm going to make it LTS in the license. I have been in holidays and super busy, I won't let this baby go to waste. If you find bugs reproduce them and submit issue. Any bug that was critical has been fixed very fast.

**Comment by Pagebakers** [comment]
That's awesome, really appreciate the amazing work!
