### ISSUE TITLE
Write tests for all possible usecases

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#17]
1. Dedicated (insert/update/remove)
2. Limit + Sort (insert/update/remove)
3. Default (insert/update/remove)
4. Channeled
	1 Namespace
	2 Channels

**Comment by ramezrafla** [comment]
+
publishComposite
reactive publishing

**Comment by theodorDiaconu** [comment]
this would be an ever-lasting issue. I will close it and we'll create others as new bugs arise.
