### ISSUE TITLE
User experience suggestions

### ISSUE THREAD

**Issue by msavin** [cult-of-coders/redis-oplog#174]
#1: De-emphasize the issue around the insecure package.

As I understand, Redtail does not work with insecure, which most people do not use anyway. However, simply saying that Redtail does not work with with package X sends a bad signal, because, what other packages might it not work with then? However, I believe this is a rare and unique situation, and so, my suggestion would be to mention it less, and only display a message to people using `insecure` in terminal: 

```javascript
Meteor.startup(function () {
	if (Package['insecure']) {
		console.log("Redtail does not support the insecure package. For more information, view:")
		console.log("https://github.com/cult-of-coders/redis-oplog/blob/master/docs/insecure.md")
	}
});
```

---------------

#2: A bit more feedback

I ran `meteor add cultofcoders:redis-oplog` and `meteor add disable-oplog` but "nothing" happened. I then passed in the default Redis settings into settings.json and began to get a connection error.

Maybe we could improve the messaging here, such as: 

```javascript
Meteor.startup(function () {
	if (!Meteor.settings.server.Redtail) {
		console.log("Redtail is not configured, and as a result, your queries may not be reactive. For more information:")
		console.log("https://github.com/cult-of-coders/redis-oplog/blob/master/docs/setup.md")
	}
})
```
---------------

#3: Sharing a Redis database between multiple apps

I wonder if it would be easy to hack in a way to use Redis in a "shared"  way. For example, maybe someone could define a prefix for every key, and thus use one Redis server for multiple apps. 

It could be handy as a means to save money on low traffic apps (since Redtail could already save you on CPU costs).

It could also be helpful for teams that develop with a production database - or people that do not have Redis set up on their machines - as they could carve out a few megabytes for this on their live Redis server.

**Comment by msavin** [comment]
Also - I noticed a small issue: when I have redis-oplog running but its not set up correctly, my app would reload like every couple of seconds. Removing the package solved the problem.

**Comment by theodorDiaconu** [comment]
@msavin thank you very much. 

#1 added that warning
#2 you can instantiate it without Meteor.settings that's a problem
#3 added a ticket for it that is separate
