### ISSUE TITLE
Licensing Ideas

### ISSUE THREAD

**Issue by ramezrafla** [cult-of-coders/redis-oplog#175]
I know @theodorDiaconu doesn't like the idea of licensing, but I would like to propose we push it further. If someone is using it in production with over 1000 users, then they are likely making money (or should be). We can set a value above which you have to pay licensing.

For corporate customers, not paying is a bad thing. It means there is no one to call on for support and that its maintenance is sporadic.

We can also have a tier with support. @theodorDiaconu and @msavin it could be a commercial avenue for either (or both of you).

MDG is waiting on a blog article from @theodorDiaconu about RedisOplog. Another amazing marketing avenue.

**Comment by theodorDiaconu** [comment]
@ramezrafla you are correct. I will create an offer for corporate people, and they will pay a monthly cost for support. Once we set this project up nicely we are going to publish to the Meteor's blog.
