### ISSUE TITLE
docs: Scaling Redis

### ISSUE THREAD

**Issue by ramezrafla** [cult-of-coders/redis-oplog#176]
We need somewhere an explanation on how we should be scaling Redis for this package to work well with multi-servers. MongoDB we get (sharding, etc.). But Redis? Any special configs? e.g. to avoid race conditions.

**Comment by theodorDiaconu** [comment]
@ramezrafla by the time you need to scale redis, you will afford 10 senior engineers to be on top of it. I think it's really unnecessary at this stage to invest focus in this. Redis scales very easily from my understanding.
