### ISSUE TITLE
Transformed fields included in "changed" events

### ISSUE THREAD

**Issue by simonbelanger** [cult-of-coders/redis-oplog#177]
Transformed fields (assigned in the collection's `transform` function) are mistakenly included in DDP `changed` events :

![2017-10-31 at 15 13](https://user-images.githubusercontent.com/17987029/32244231-43c9e5c6-be4e-11e7-8371-fe0934b7ae7c.png)

Here's the exact `transform` function : 

```
const collection = new Players("players", {
	cursoredFind: true,

	transform(doc) {
		/* eslint-disable no-param-reassign */
		doc.ap = Number(doc.ap) || 0;
		doc.xp = Number(doc.xp) || 0;
		doc.hp = Number(doc.hp) || 1;
		doc.level = Number(doc.level) || 1;
		doc.pp = Number(doc.pp) || 0;
		doc.class = Number(doc.class);
		doc.longClassName = utils.className(doc.class);
		doc.fullName = `${doc.fname} ${doc.lname}`;

		if (Meteor.isClient) {
			const maxVals = utils.getMaxValues(doc.class);

			const maxHP = maxVals.hp;
			const maxAP = maxVals.ap;
			const maxXP = doc.xp_per_level * doc.level;

			const hpPercent = Math.round((doc.hp / maxHP) * 100);
			const apPercent = Math.round((doc.ap / maxAP) * 100);
			const xpPercent = Math.round(((doc.xp % doc.xp_per_level) / doc.xp_per_level) * 100);

			doc.stats = {
				hp: doc.hp,
				ap: doc.ap,
				xp: doc.xp,
				gp: doc.coins,
				hpPercent,
				apPercent,
				xpPercent,
				maxHP,
				maxAP,
				maxXP,
			};

			doc.avatarUrl = cdnUrl(doc.avatarPath);
			doc.headUrl = cdnUrl(doc.headPath);
		}
		/* eslint-enable no-param-reassign */

		return doc;
	},
});
```

Here's the `packages` file :

```
standard-app-packages@1.0.9
jquery@1.11.10
browser-policy@1.1.0
email@1.2.3
browser-policy-content@1.1.0
facts@1.0.9
srp@1.0.10
http@1.2.12
mrgalaxy:stripe
jparker:crypto-md5
rajit:bootstrap3-datepicker
reactive-var@1.0.11
markdown@1.0.12
underscore@1.0.10
mrt:jquery-ui-sortable
meteorhacks:ssr
matb33:collection-hooks
sergeyt:typeahead
raix:ui-dropped-event
meteorhacks:aggregate
jparker:crypto-sha256
jparker:crypto-base64
force-ssl@1.0.14
meteorhacks:unblock
percolate:server-info
tmeasday:publish-counts
meteor-base@1.1.0
mobile-experience@1.0.4
blaze-html-templates@1.0.4
session@1.1.7
tracker@1.1.3
logging@1.1.17
reload@1.1.11
random@1.0.10
ejson@1.0.13
spacebars@1.0.12
check@1.2.5
numeral:numeral
fds:latinize
dburles:mongo-collection-instances
ecmascript@0.8.1
gwendall:body-events
accounts-google@1.2.0
bozhao:link-accounts
percolate:google-api
aldeed:simple-schema
mdg:validated-method
jaywon:meteor-node-uuid
q42:microsoft
standard-minifier-js@2.1.1
harrison:papa-parse
meteorhacks:async
meteorhacks:picker
outatime:jwt-simple
kadira:flow-router
react-template-helper
classcraft:microsoft-graph
wiseguyeh:azure-active-directory
react-meteor-data
gadicc:blaze-react-component
merlin:edmodo
classcraft:edmodo-api
shell-server@0.2.4
percolatestudio:segment.io@=2.0.0_1
stylus@2.513.9
juliancwirko:postcss
minifier-css@1.2.16
facebook-oauth@1.3.2
google-config-ui@1.0.0
twitter-oauth@1.2.0
dynamic-import@0.1.1
mdg:meteor-apm-agent
cultofcoders:redis-oplog
disable-oplog
cultofcoders:publish-composite
meteortoys:allthings
idmontie:migrations
service-configuration@1.0.11
oauth@1.1.13
mongo@1.1.19
accounts-base@1.3.1
accounts-password@1.4.0
```

**Comment by simonbelanger** [comment]
I dug a little deeper and it looks like the problem is coming from this line https://github.com/cult-of-coders/redis-oplog/blob/6f38b0292cfec6b1ccd73b79545552a1415999ae/lib/cache/ObservableCollection.js#L254

Adding `transform: null` to the `options` parameter seems to fix the issue. I don't see why we would need the transformed fields in this context anyway.

**Comment by theodorDiaconu** [comment]
@simonbelanger a very interesting point, some people want these transformed variables like this look: 
https://github.com/cult-of-coders/redis-oplog/issues/154

But it seems they only need it when you pass a transform as an option to the cursor. Interesting.

**Comment by simonbelanger** [comment]
passing `this.options.transform` fixes the issue but since only modified fields are included in the `findOne`, it could lead to extremely erratic behavior in the `transform` function...

**Comment by theodorDiaconu** [comment]
@simonbelanger good catch. I'm going to fix this.

**Comment by theodorDiaconu** [comment]
@simonbelanger fixed, and published 1.2.1_1 very good catch indeed.

**Comment by simonbelanger** [comment]
👌  thx for the fix

**Comment by theodorDiaconu** [comment]
@simonbelanger do you have any metrics for me, how it compares to non-redis-oplog solution ?

**Comment by simonbelanger** [comment]
not yet, I'm still working on the package integration but I'll keep you posted. I'm very eager to put that in production, we have nearly 10 000 concurrent connections on the app and the oplog processing for some collections is completely crazy...

![2017-11-01 at 12 06](https://user-images.githubusercontent.com/17987029/32284327-4a68e008-befd-11e7-8e2b-e569ea618e17.png)

...and that's for a range of 1 hour...

**Comment by theodorDiaconu** [comment]
@simonbelanger my god, nice. Pls consider using namespaces, they could really make a difference.
