### ISSUE TITLE
Redis Events API

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#179]
Unidirectional communication channel that integrates Redis Events and DDP. Opening the world of bringing incredibly scalable reactivity to fine-tuned requirements that works in multi-instance environments.

## Desired API

```js
import {Vent} from 'meteor/cultofcoders:redis-oplog';

// server
Vent.publish({
    'threadMessage'({threadId}) {
        // check permissions, you have access to this.userId, as we are in the known publish context
        
        // registers listeners on redis
        this.on(`messages::${threadId}::new`, ({message}) => {
            this.send({message})
        });
        // Automatically stops the registered redis listeners when subscription is stopped
    }    
})

// Should also work
Vent.publish('threadMessage', function () { ... });

// some other part server
Meteor.methods({
    'messages.add'({threadId, message}) {
        // makes an insert without taking it to redis-oplog
        Messages.insert(message, {
            pushToRedis: false,
        });
        
        // disptaches event to redis
        Vent.emit(`messages::${threadId}::new`, {message});
    }
})

// client
const handler = Vent.subscribe('onNewMessage', {threadId});

handler.listen(function ({message}) {
    // handle it
});

// stops all the listeners and the subscription
handler.ready(); // returns boolean if the subscription has been marked as ready
handler.stop(); 
```

## Proposed Implementation

Create a local collection for each vent subscription and let the current DDP implementation communicate with it using the following strategy:
- On initial sub, send some initial data: 'id', {}
- When you need events dispatched, send "changed" events to 'id'.

Inspiration:
- https://github.com/RocketChat/meteor-streamer/blob/master/packages/rocketchat-streamer/client/client.js#L18
- https://github.com/RocketChat/meteor-streamer/blob/master/packages/rocketchat-streamer/server/server.js#L352

## Careful 

- We need to allow subscribing to the same publication and receive separate events.
- Make sure that when using vents, you won't collide with listeners from the oplog. 
- Make sure that if multiple changed events need to be sent using 'changed' is a good solution and they are all caught
- The mergebox will still store the image of your subscription. Storing just one element per publication (the last event sent) is not that costly unless your events are big. But do analyze @mitar 's https://github.com/peerlibrary/meteor-control-mergebox . More RAM usage is preferred to more CPU usage. (Follow-up: https://github.com/peerlibrary/meteor-control-mergebox/issues/5)

**Comment by theodorDiaconu** [comment]
@mitar you are a master here, is it possible to use DDP in such way, but without keeping track of the data ?

So a sort of what you did, but without mergebox ? 
I was investigating your https://github.com/peerlibrary/meteor-subscription-data 

If you have any ideas let me know, I'll investigate this further.

**Comment by theodorDiaconu** [comment]
Investigate https://arunoda.github.io/meteor-streams/

**Comment by msavin** [comment]
I like it, but we gotta change the name RedisOplog :D it's not an "oplog" and in this case it becomes more than a query sync tool too.

**Comment by mitar** [comment]
Do you know about: https://github.com/peerlibrary/meteor-control-mergebox

But yes, if you want just to send things, then I recommend these days to use https://github.com/RocketChat/meteor-streamer.

You could also do something similar yourself and piggy-back stream yourself.

**Comment by theodorDiaconu** [comment]
@mitar I actually found something that looks very promising:
https://github.com/wojtkowiak/meteor-custom-protocol

**Comment by mitar** [comment]
Yes, I think it uses the same underlying mechanism.

I think since https://github.com/meteor/meteor/pull/7985 this is much easier to implement.

**Comment by theodorDiaconu** [comment]
@mitar I actually like more the API of Streamer.

**Comment by theodorDiaconu** [comment]
Investigate https://github.com/raix/Meteor-EventDDP

**Comment by theodorDiaconu** [comment]
I think the solution would be a mixture of:
DisableMergebox and https://github.com/RocketChat/meteor-streamer/blob/master/packages/rocketchat-streamer/client/client.js#L18

See if I can fork meteor-streamer and transform it based on specified needs.
