### ISSUE TITLE
Collection-level transform in publishComposite

### ISSUE THREAD

**Issue by simonbelanger** [cult-of-coders/redis-oplog#183]
It looks like collection-level `transform` is skipped for the documents passed down to `children`'s `find` functions in `publishComposite`, which is problematic because it's different from the original package's behavior.

Two precisions :
- Transform should be skipped for documents passed to the client
- Transform should be skipped for the documents passed down to `children`'s `find` functions if the `transform: null` options is specified in the the parent find's cursor

**Comment by simonbelanger** [comment]
I did more tests, and it looks like the original behavior is to also apply the collection-level `transform` to documents passed to the client.

**Comment by simonbelanger** [comment]
So... the problem comes from here https://github.com/cult-of-coders/redis-oplog/blob/86e44a25bef4577a3f1c5292708872a137145a2e/lib/mongo/extendObserveChanges.js#L62 and here https://github.com/cult-of-coders/redis-oplog/blob/86e44a25bef4577a3f1c5292708872a137145a2e/lib/mongo/extendObserveChanges.js#L70 and is specific to methods added to the document instance (using `dburles:collection-helpers` in my case). `EJSON.clone` doesn't clone instance methods...

**Comment by theodorDiaconu** [comment]
@simonbelanger the reason I'm cloning them was because publishComposite was failing for a very strange reason. Need to find another way, but can you help me by clearly specifying your case, as in show me how your publishComposite looks like, and how it should behave, so I can write a test for it.

**Comment by theodorDiaconu** [comment]
This is the strange thing, if I don't clone it here:
``` // createObserve
        added(collectionName, docId, doc) {
            if (observer.added) {
                observer.added(EJSON.clone(doc));
            }
        },
```

This test fails: "Should be able to detect updates on parent element"

**Comment by theodorDiaconu** [comment]
Just realized that doing _.extend({}, doc) still works :)

**Comment by simonbelanger** [comment]
Replacing every `EJSON.clone` in the package by `cloneDeep` from `lodash` fixes the issue.

If you want to reproduce the issue you can simply define a helper on a collection using `dburles:collection-helpers` and try to call this helper for a document passed down to a `children`'s find function in a `publishComposite`

**Comment by theodorDiaconu** [comment]
We don't even need cloneDeep, `_.extend({}, doc)` solves it.

**Comment by theodorDiaconu** [comment]
I'm bringing back cloneDeep, and fixing it atm.

**Comment by simonbelanger** [comment]
awesome, thx
