### ISSUE TITLE
Critical - Cache subscribers listening to the same channels.

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#19]
Given 10 users, that subscribe to users in different manners.
We would have 10 redis listeners, and for each modification on users, we would get that modification 10 times, then we need to parse it 10 times.  Parsing may be heavy since we use EJSON to serialize/deserialize messages pushed to redis. And also, we will have 9 unecessary redis subscriptions, which occupy network bandwidth and CPU.

Create a subscription cacher similar to the one for publications.

RedisSubscriptionStore - "channel", apply same principles, with the observers, if the last one is leaving stop listening. 

RedisListener - will do something like
```
RedisSubscriptionStore.attach(this, channel, function(channel, data) {
})
RedisSubscription.detach(this)
```

**Comment by sebakerckhof** [comment]
Also, remember the same message can be send over multiple channels, right?
So, depending on the use case and how heavy parsing the message actually is, it might make sense to give each message a unique ID and keep a small LIFO cache with parsed messages, with a look-up table/hash for the unique ID. So if you have a collection `myCollection` and an object `{_id:'foo',prop:value} which you send over 2 channels `collection::*` and `collection::foo` that both has subscribers on the same server, you give the message a unique id while you send it and parse it only once. Then again, maybe this might be a micro optimization not really worth it.

However, I do think giving each message a unique ID if you send it over multiple channels might have other useful purposes.

**Comment by theodorDiaconu** [comment]
Assuming the redis cacher is done, and we don't usually send the message to more than 2-3 channels. When you work with 'channel' or 'namespace' it won't push it to the main collection channel. You could do that by doing:

// on an update/remove for example:
channels: ['customChannel', 'collectionName']
//  will push to 3 channels
'customChannel', 'collectionName', 'collectionName::id'

Problem is, how do I give that unique id ? Redis accepts a channel and a string when publishing to it, I will still need to deserialize it in order to get the id somehow



Keeping a LIFO cache for messages may

**Comment by theodorDiaconu** [comment]
done.
