### ISSUE TITLE
Redis server capabilities

### ISSUE THREAD

**Issue by simonbelanger** [cult-of-coders/redis-oplog#191]
How can we evaluate the ressources needed on the redis server regarding RAM, storage, concurrent connections, etc?

**Comment by theodorDiaconu** [comment]
@simonbelanger one redis server can handle like 300k ops / s

Check here:
https://redis.io/topics/benchmarks

You don't need much storage, I think 512MB RAM, and 1 good CPU is enough for most applications. (Handles around 300k ops/s)

Just keep Redis in the same network.

**Comment by Floriferous** [comment]
@theodorDiaconu do you know how many concurrent connections redis needs? I'm assuming you open only one connection per server instance? Or does it open more?

**Comment by theodorDiaconu** [comment]
Its two connections. One for pushing msgs another for receiving.

Regards,
Theodor
