### ISSUE TITLE
Redis package options

### ISSUE THREAD

**Issue by simonbelanger** [cult-of-coders/redis-oplog#192]
It would be helpful to reference the `redis` package documentation (https://www.npmjs.com/package/redis#options-object-properties) for the `redis` settings in the readme.

**Comment by theodorDiaconu** [comment]
Yes, true I think I had it at some point, my bad.

**Comment by maxnowack** [comment]
It was removed in e7e14de76d70c9fe30efa375706c88fe88c35878

**Comment by theodorDiaconu** [comment]
@simonbelanger btw, how is integration going? It would be of tremendous help for all Meteor community if you can show us the performance improvements.

**Comment by simonbelanger** [comment]
@theodorDiaconu It's in QA right now, should be deployed by the end of the week. I'll keep you posted.

**Comment by theodorDiaconu** [comment]
@simonbelanger thank you, I'm so curious on how it performs.
