### ISSUE TITLE
[Q] Proper server setup for RedisOplog

### ISSUE THREAD

**Issue by Twisterking** [cult-of-coders/redis-oplog#197]
I am currently running my Meteor App on a [DigitalOcean Droplet with 2 Cores and 2GB RAM](https://www.digitalocean.com/pricing/#droplet) ... I don't have that many concurrent users but lots of reactive queries (lots of searching in collections via RegEx).

My question is:

- Does RedisOplog make proper sense for me? Are there any real performance benefits even if there are only about 30-80 concurrent users on my app?
- Do I have to set up Redis server on a seperate droplet (which size?) or can I run it on the same droplet?

Thanks guys! cheers, P

**Comment by theodorDiaconu** [comment]
@Twisterking 

1. It will have performance benefits for sure, would it be notice-able for 80 users ? Doubt it, unless you have a lot of traffic on the app. If you don't experience performance issues, why bother ?
2. You can run it in the same server, redis doesn't consume much RAM at all.

Cheers!
