### ISSUE TITLE
[1.2.3] Undefined document on insert event processing

### ISSUE THREAD

**Issue by simonbelanger** [cult-of-coders/redis-oplog#200]
@theodorDiaconu First, I want to inform you that we've put the package in production last night and so far we have no stability issue and we're running on nearly half of the containers we are normally running on at this time of day. We were hoping for an important gain, but is is above all our expectations. And there's still a lot of namespace optimizations possible.

Now the regarding the issue... our server logs are filled with this exception:  

![2017-11-09 at 11 01](https://user-images.githubusercontent.com/17987029/32615296-6de2d9a8-c53d-11e7-98e6-3c4e1cb15f63.png)

Any idea?

**Comment by theodorDiaconu** [comment]
@simonbelanger good job!! Man you got me so excited!

First tell me what version you are using, that issue happens when we do an insert and we aren't passing a doc.

**Comment by simonbelanger** [comment]
I'll update to 1.2.4. These exceptions are kinda hard to catch because they happened in asynchronous events fully handled inside the package, but I'll put the source directly in the `packages` folder to add more meaningful log.

**Comment by theodorDiaconu** [comment]
https://github.com/cult-of-coders/redis-oplog/blob/90b0e6afe1e75bcc76c113bb3d12081018153f4c/lib/redis/RedisSubscriptionManager.js#L131

Is there the slight possibility of having a concurrency issue here ? An imediate deletion after an insert ? Do you have such cases inside ?

**Comment by simonbelanger** [comment]
Concurrency issue is definitely a possibility... I'll have more context after tonight's release

**Comment by theodorDiaconu** [comment]
@simonbelanger I will have it fixed by then, releasing now 1.2.4_1 just to be sure if the doc is no longer in the database, don't do any processing.

**Comment by theodorDiaconu** [comment]
Most likely a concurrency issue... hopefully that fixes it.
