### ISSUE TITLE
Default values for "mutationDefaults" settings

### ISSUE THREAD

**Issue by simonbelanger** [cult-of-coders/redis-oplog#204]
If the following setting is specified, `pushToRedis` get falsy :

```
...
    "mutationDefaults": {
        "optimistic": true
    }
...
```

Expected behavior would be for it to keep its default value.

Also, I can see the performance gain in deactivating optimistic UI, but IMO the default here should be to keep it active. I don't expect this package to change any other behaviors than the oplog tailing mechanism.

**Comment by theodorDiaconu** [comment]
Good catch and good argument.
