### ISSUE TITLE
Overwriting OplogHandle

### ISSUE THREAD

**Issue by simonbelanger** [cult-of-coders/redis-oplog#205]
@theodorDiaconu Have you ever considered overwriting OplogHandle class from Meteor's `mongo` package? 

https://github.com/meteor/meteor/blob/d93c021c896029d774ccecc7241ff20ec4045568/packages/mongo/oplog_tailing.js

I had a quick look and it seems like all the logic specific to mongo oplog tailing is already abstracted to this class.

It might be an interesting alternative to make the package smaller and more tightly bound with observer mechanisms in Meteor core.

I'd be interested to hear your thoughts on this matter.

**Comment by theodorDiaconu** [comment]
Initially that's how I wanted to do things, hook into the ObserveMultiplexer and into Meteor Core (https://github.com/meteor/meteor/blob/d93c021c896029d774ccecc7241ff20ec4045568/packages/mongo/observe_multiplex.js) 

But I headed into issues like some parts weren't exported so I can modify the prototype and I had to override some big chunks, and repeat the code from Meteor.

Ultimately I ended up overriding the publish function which gave absolute control to how to handle things. 

I'm not sure if there is any actual need to hook tighter into the Core. What benefits would we have?

**Comment by simonbelanger** [comment]
Ok, I get what you mean.

I think this is exactly the kind of thing that we should address to Meteor development team. They want to make the Meteor core development to be more community-driven and making parts of the core more easily interchangeable is exactly the kind of improvement they're most likely to accept to work on. 

As for the benefits, the main one would be to not re-implement mechanisms that already exists in the core. Our expertise on theses matters is still a couple years behind Meteor's and piggybacking on it as much as possible would most certainly result in an even more stable and performant package.

**Comment by theodorDiaconu** [comment]
Seems that this problem has already been addressed here:
https://github.com/meteorhacks/meteorx

**Comment by simonbelanger** [comment]
Cool, a little old but it might be interesting

**Comment by theodorDiaconu** [comment]
@simonbelanger take a look at: https://github.com/cult-of-coders/redis-oplog/pull/283, also do you use it in production still, do you have some metrics that I can use to show-case them on Meteor Night this 30th may ?

**Comment by theodorDiaconu** [comment]
@simonbelanger yep that is expected since we have a mirror image for every pubsub in the observableCollection, maybe in the future we're gonna resolve that. Very glad it's a success story for you.
