### ISSUE TITLE
Handle 3rd party database operations

### ISSUE THREAD

**Issue by elledienne** [cult-of-coders/redis-oplog#209]
Would it be possible to use this library if all (or most) the write/update operations to Mongo come from a non-Meteor application?

**Comment by theodorDiaconu** [comment]
Yes! But you need some additional code for this. I've actually been asked multiple times by our Premium Support clients. I think it's clear I need to add some documentation around this.

What essentially you have to do, is connect to Redis. And publish messages to channels in the form that Mutator does it.

For example if you want to send an update to "tasks" collection you would do

redisPublish("tasks", JSON.stringify({"e": "u", "d": {"_id": docId}, "f": changedTopLevelFieldsArray}));

And also publish it to "tasks::taskId" if you want to benefit from direct processing and subscriptions that listen by id.

**Comment by theodorDiaconu** [comment]
Added extensive documentation here:
https://github.com/cult-of-coders/redis-oplog/blob/master/docs/outside_mutations.md

**Comment by elledienne** [comment]
Thank you very much! Sounds great!
