### ISSUE TITLE
Redis-Oplog does not detect third-level changes

### ISSUE THREAD

**Issue by ramezrafla** [cult-of-coders/redis-oplog#210]
We have a field `a.b.c` where `c` changes server-side and the change is not propagated to the client.
If we remove redis-oplog (and disable-oplog) the change is propagated.

**Comment by theodorDiaconu** [comment]
@ramezrafla thanks for the issue. Just wrote a test for this and it passes.

Could you show me your publication and the mutation you apply ?

**Comment by theodorDiaconu** [comment]
The passing test: 
```js
it('Should detect 3rd level nesting changes', async function (done) {
            const context = 'deep-level-nesting-' + Random.id();

            let handle = subscribe({
                context,
            });

            await waitForHandleToBeReady(handle);
            const cursor = Collection.find({
                context
            });

            const observer = cursor.observeChanges({
                added(docId, doc) {
                    update(docId, {
                        $set: {
                            'item.profile.name': 'Elena Smith'
                        }
                    })
                },
                changed(docId, doc) {
                    assert.isObject(doc.item);
                    assert.equal('Elena Smith', doc.item.profile.name);
                    done();
                }
            });

            create({
                context,
                item: {
                    profile: {
                        name: 'John Smith'
                    }
                }
            });
        });
```

**Comment by ramezrafla** [comment]
Thanks so much @theodorDiaconu 

It turns out it's our mistake, but with a twist (it actually worked without redis-oplog, which is what misled us).

We forgot to list the field in our publish (it's `profile.locked`), however it seems Meteor publishes `profile` by default. This was no longer the case when using redis-oplog (I guess you need to be more precise with redis-oplog)

Sorry  :(

**Comment by theodorDiaconu** [comment]
@ramezrafla redis-oplog should also publish profile because what it does it creates a universal publication. Interesting... by any chance do you use any rawCollection() updates ?

**Comment by ramezrafla** [comment]
No we don't, not on the user db

**Comment by theodorDiaconu** [comment]
Help me understand Ramez, I'm thinking this issue is not yet solved. When you can give me the subscription you had and the mutation you did.

**Comment by ramezrafla** [comment]
Sorry for delay, for some reason this thread was not emailing me. I'll work on getting you the pubs and subs.
