### ISSUE TITLE
2 applications on 1 server?

### ISSUE THREAD

**Issue by dnish** [cult-of-coders/redis-oplog#211]
Hey,
I'm just wondering if it possible to run 2 applications on the same server. We have 2 chat applications which are pretty much the same (clones - just target another niche) and running them on the same VPS system with redis-oplog enabled. Currently I'm having an issue where some updates aren't reflected and the user state stays wrong. Didn't have this issue with our other applications which use a single server per app. We currently upgraded both clones to Meteor 1.6, so I don't know if that is the issue or redis-oplog.

**Comment by dnish** [comment]
@theodorDiaconu I found that this is caused by another issue - but it is related to redis-oplog. We're having the following autorun function:

```
        function () {

            var chatId = Meteor.users.findOne(Meteor.userId(), {fields: {'profile.chatId': 1}}).profile.chatId;
            if (chatId) {
                this.isSearching(false);

                [...]

            }
        },
```

The problem occurs when the user gets connected again to the same chat user. Without redis-oplog, the autorun is fired again. When we enable redis-oplog, this doesn't happen. So the <code>isSearching</code> method is never called.

**Comment by theodorDiaconu** [comment]
Do you load redis-oplog as the top package?

**Comment by theodorDiaconu** [comment]
Also, can u help me reproduce this issue? Maybe a quick repo, as i need to understand it fully. I need to understand what u mean by user getting connected again.

**Comment by dnish** [comment]
@theodorDiaconu It means that we set the same chatId again. 

```
Meteor.users.update({_id: this.userId}, {
                    $set: {
                        'profile.isSearching': false,
                        'profile.chatId': chatId,
                        'status.online':true
                    }
});
```

This command will be executed. The error occurs when the user get's connected instantly again to the same chatId. So the autoRun function isn't fired, because the chatId value didn't change - but without redis-oplog it fires.

**Comment by theodorDiaconu** [comment]
@dnish thanks for clarification.

Why would Meteor server send again changes that don't actually change the object, this seems like a strange behavior. I'm thinking that there's something else going on here... Meteor's Mergebox would not allow it.

Can you please show me your subscription ? Do you have something like updatedAt at the User level ?

**Comment by dnish** [comment]
@theodorDiaconu Okay, seems to be an issue with our app. Just tried to reproduce it with a new Meteor app, didn't happen there.

**Comment by theodorDiaconu** [comment]
@dnish I don't think it's an issue with your app if it works with oplog but not with redis-oplog. I think there's something else going on. Do you have any hooks on users ?

To be sure, perform an .observeChanges({ changed() }) and see exactly what changes.

**Comment by dnish** [comment]
@theodorDiaconu Possible that this causes the issue? We're using findAndModify to find a new user and reset his values:


```
      Meteor.users.rawCollection().findAndModify({
            '_id': {$nin: [this.userId]},
            'status.online': true,
            'profile.onlyText': true,
            'profile.isSearching': true,
            'profile.inChat': true
        }, [], {$set: {'profile.isSearching': false}}, {}, Meteor.bindEnvironment((err, row) => { ......
```

**Comment by theodorDiaconu** [comment]
@dnish you're right! if you are using rawCollection() you aren't triggering any redis events. This is a normal behavior.

In order to send the event manually, and benefit of redis-oplog, do something like this:
```js
import {getRedisPusher, Events, RedisPipe} from 'meteor/cultofcoders:redis-oplog';

getRedisPusher.publish('users', EJSON.stringify({
    [RedisPipe.DOC]: {_id: userId},
    [RedisPipe.EVENT]: Events.UPDATE,
    [RedisPipe.FIELDS]: ['profile.isSearching']
});
```

If you listen to user by id, you need to push to 'users::userId' channel, instead of 'users', or both!

Read more here: https://github.com/cult-of-coders/redis-oplog/blob/master/docs/outside_mutations.md

**Comment by theodorDiaconu** [comment]
Wouldn't it be better to do a find then update? Or you are afraid of concurrency issues?

**Comment by dnish** [comment]
Yep, it's about the concurrency. When multiple users try to find a new chat partner at the same time, they may get connected to partner A and then suddenly switch over to B because he also requested a new partner.

**Comment by theodorDiaconu** [comment]
@dnish I see and it makes sense. You have to do some manual pushes to redis, to reflect that change. And don't forget to also push it to the direct channels. And if you use namespaces you have to be careful with that also.

Sorry that this isn't too easy or straight forward..

**Comment by theodorDiaconu** [comment]
@dnish I think I did not address your main question. Working with the same redis-server can be problematic for scaling. I suggest you could open 2 redis-servers on the same server but different ports.
