### ISSUE TITLE
Provide mutation and cursor extending abilities at collection level

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#212]
Given the following scenario:

```js
const Tasks = new Mongo.Collection('tasks');
Tasks.configureRedisOplog({
    mutation(options, {event, selector, modifier, doc} = mutationObject) { 
        const userId = Meteor.userId();
        const companyId = getCompany(userId);
        Object.assign(options, {
              namespace: `company::${companyId}`
         });
    },
    cursor(selector, options) {
        Object.assign(options, { namespace, namespaces, channel, channels });
    }
})
```

When performing an insert, if we have mutationDefaults, they will extend the default mutationDefaults in main config, and they will be extended by the new mutations that apply.

The mutation will be hit only with relevant information based on the event. 

Regardless what you use, we will still push to direct channels either way.

**Comment by copleykj** [comment]
Working on the implementation of this now and it looks like namespaces aren't being appended with the collection name. Not sure if this is intended.

**Comment by copleykj** [comment]
You can ignore that last message.. Seems I missed it in the noise of  the rest of the debug messages.
