### ISSUE TITLE
selector._id undefined when collection.update passed string as first param

### ISSUE THREAD

**Issue by copleykj** [cult-of-coders/redis-oplog#214]
Currently you can pass a string to the first param of `Collection.update()` instead of an object containing an `_id` field to update a particular document. When doing this with redis-oplog and using the new collection level configuration, the selector field of the mutationObject will not contain and `_id` field.

**Comment by copleykj** [comment]
Also I haven't confirmed this yet but this may be the case for cursor config when using a findOne with id passed as a string for the first param.

**Comment by theodorDiaconu** [comment]
Oh true:
https://github.com/cult-of-coders/redis-oplog/blob/master/lib/mongo/Mutator.js#L70

This needs to be run first.

**Comment by copleykj** [comment]
:+1:
