### ISSUE TITLE
Idea: data stores setup as LocalCollections

### ISSUE THREAD

**Issue by jamesgibson14** [cult-of-coders/redis-oplog#219]
Then we could query them with minimongo queries.

**Comment by jamesgibson14** [comment]
For example: I have some datasets that I know are being observed for reactivity on the client side, but sometimes I need to query it on the server, If I know it is already in a `store`, it would be great to query the `store` instead of the DB. `store.find({type: 'account'}) //=> cursor`

**Comment by theodorDiaconu** [comment]
@jamesgibson14 interesting thing, I believe we can expose a sort of cursor store finder, but the search can be done with mongo filters by using something like sift()
```
const store = findRedisStore(cursor);
// do search on the store
```
Mongo LocalCollections are very heavy btw, I'd rather keep them in array.

**Comment by theodorDiaconu** [comment]
Proposing API:

Search.findRedisStore(cursor) => { find(), findAll(), store: array }
Search.findInAllStores(siftFilters) => array
Search.findRedisStore(cursor).find(siftFilters) => array
Search.findRedisStore(cursor).findAll() => array

**Comment by jamesgibson14** [comment]
I think that API looks great.
Instead of using sift Filters could you just turn the store itself into a LocalCollection? 
```
this.store = new LocalCollection();
...

find: function(id){
     return this.store.findOne({_id: id})
}
...
add(id, publicationEntry) {
        if (!this.find[id]) {
            throw new Meteor.Error(`You cannot add a publication to this store, because it already exists: ${id}`);
        }

        this.store.insert(publicationEntry);
    }
```
Then you could just query the `store` directly with any minimongo selector without having to return a sift filter.

**Comment by theodorDiaconu** [comment]
@jamesgibson14 the problem is that if I transform it to a LocalCollection:
1. It will ocuppy more memory
2. Slower inserts/updates to the store

We need to opt-in into this somehow.

**Comment by jamesgibson14** [comment]
Okay, if that is the case, don't worry about the LocalCollection, thanks
for all the great work on this.
