### ISSUE TITLE
Collection level configuration cancels out default channels

### ISSUE THREAD

**Issue by copleykj** [cult-of-coders/redis-oplog#220]
Using `Collection.configureRedisOplog` appears to stop publishing to default channels. I wasn't sure if this was intended or not. If so it shouldn't be hard to replicate.

**Comment by theodorDiaconu** [comment]
Thanks for reporting, I'll get back on redis-oplog next week.

**Comment by theodorDiaconu** [comment]
@copleykj this is expected I believe.

It states in the docs:
```
These configurations are applied last, they are the final configuration extension point,
so you have to manage the situation in which you have multiple namespace configurations.
```

So, in theory if you want to also publish to the default channel, you need to check if there are existing channel/namespaces.

Can you show me your code that overrides this ?

**Comment by copleykj** [comment]
I've just looked into this more and found that I had missed removing part of the old implementation where I was passing the namespace as part of the options.

**Comment by theodorDiaconu** [comment]
cool
