### ISSUE TITLE
Feature request: Clear cache

### ISSUE THREAD

**Issue by nadeemja** [cult-of-coders/redis-oplog#223]
Hi,

Sometimes I delete documents manually in MongoDB.

But, the doc is usually cached inside redis.

Anyway to manually "reset" redis?

**Comment by theodorDiaconu** [comment]
The doc is never cached inside redis. And theoretically you can do:
PublicationFactory.reloadAll() which refreshes all the collection views , but it's not exported, so we can transform the task into that, and you can execute it inside a meteor shell or method.

**Comment by theodorDiaconu** [comment]
PublicationFactory is exported so you could do this.

**Comment by boomfly** [comment]
Can't find method reloadAll

Only server restart helps

**Comment by boomfly** [comment]
When i add {limit, sort} to query there are no problem with update doc directly in mongo
