### ISSUE TITLE
Document in server side insert mutations does not contain _id field

### ISSUE THREAD

**Issue by copleykj** [cult-of-coders/redis-oplog#225]
When running an insert on from the server the document passed to the mutation method of configureRedisOplog has no _id field.

```js
Collection.configureRedisOplog({
    mutation(options, {doc}) {
        // doc._id -> undefiend
    }
})
```
reproduction here: https://github.com/copleykj/redis-oplog-issue

Once you've cloned the project and setup redis, open the app in the browser.. You'll see two buttons.. One runs a client side insert, the other calls a method that inserts a document on the server.. After clicking the buttons you'll see logs in the server console.. Client side inserts have _id, Server side do not.

**Comment by theodorDiaconu** [comment]
@copleykj this is by design. As described in the doc: `The mutation() function is called before the actual mutation takes place.`

Tell me your use-case, what you need it for, so we can find a solution.

**Comment by copleykj** [comment]
If this is by design that's fine.. I was debugging an issue and trying to identify which document the mutation was running for and didn't have an _id.

**Comment by theodorDiaconu** [comment]
I understand, appreciate it. 👍
