### ISSUE TITLE
Optimistic UI bug when updating user profile

### ISSUE THREAD

**Issue by maxnowack** [cult-of-coders/redis-oplog#227]
I've discovered a bug with optimistic ui when I update the user profile. The `update` ddp message is sent after the method result message, like in #51.
I've created a reproduction here:
https://github.com/maxnowack/meteor-redisoplog-latencycompensation/tree/user-profile

**Comment by copleykj** [comment]
Think this is what I'm seeing in #202 as well.

**Comment by theodorDiaconu** [comment]
Very strange... I will investigate this as soon as possible. Currently a bit time-constrained.

**Comment by maxnowack** [comment]
I think it has to do with the automatic publication of current user data (https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L721-L735), which didn't use the publication of redis-oplog.

**Comment by theodorDiaconu** [comment]
@maxnowack damn. I think the solution would be to create another publication for this... maybe a null one. But this is weird, is redis-oplog loaded as top package? If yes, then it should use it.

**Comment by maxnowack** [comment]
Yes, redis-oplog is loaded at the very first. Even a new publication doesn't help.

**Comment by copleykj** [comment]
If it helps, I'm seeing this in other publications I have that are using publish-composite. Doesn't seem to happen with the one publication that I have that uses `Meteor.publish`

**Comment by theodorDiaconu** [comment]
This is mind-boggling... I will have a look at it.

**Comment by theodorDiaconu** [comment]
The problem is that it is not properly identified:
`DDP._CurrentPublicationInvocation.get()`

Which has official support since Meteor 1.5, doesn't detect the current publication invokation inside the observeChanges() which we override. Maybe because it runs in a new fiber.

Investigation is ongoing still...

**Comment by theodorDiaconu** [comment]
This https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L722 does not use RedisOplog publish function for a reason I have no clue...

**Comment by theodorDiaconu** [comment]
It is because Meteor loads accounts-base before redis-oplog, even if you put redis-oplog on top, maybe because of a weird dependency tree?
Before actually getting the chance to modify publish, by the time we modify it, the universal publication has already been published. 

After digging I found the culprit: https://github.com/rclai/meteor-collection-extensions/blob/master/package.js#L39

**Comment by theodorDiaconu** [comment]
It seems that I can't find a solution, can't seem to reliably override the constructor of Mongo.Collection, my solution breaks collectionhooks, and now collection hooks will not work on Meteor 1.6.1 because of:
```
https://github.com/meteor/meteor/blob/devel/packages/mongo/collection.js#L30
```

If I do what collection extensions is doing, it will break for Meteor 1.6.1

We have a serious problem

**Comment by maxnowack** [comment]
This way seems to work :)
https://github.com/maxnowack/meteor-extend-collections-test/blob/master/imports/extendCollection.js

**Comment by theodorDiaconu** [comment]
It fails with collection hooks. Try to run the tests.

**Comment by theodorDiaconu** [comment]
@maxnowack can you try now release/1.2.6 see if it's fixed ?

**Comment by maxnowack** [comment]
@theodorDiaconu I had an issue while upgrading to Meteor@1.6.1-rc.9
````
$ meteor update --release=1.6.1-rc.7
=> Errors while initializing project:

While selecting package versions:
error: Conflict: Constraint babel-compiler@6.13.0 is not satisfied by babel-compiler 7.0.0-rc161.9.
Constraints on package "babel-compiler":
* babel-compiler@~7.0.0-rc161.9 <- top level
* babel-compiler@7.0.0-rc161.9 <- ecmascript 0.10.0-rc161.9
* babel-compiler@7.0.0-rc161.9 <- minifier-js 2.3.1-rc161.9 <- standard-minifier-js 2.3.1-rc161.9
* babel-compiler@7.0.0-rc161.9 <- standard-minifier-js 2.3.1-rc161.0
* babel-compiler@6.13.0 <- coffeescript 1.11.1_4 <- peerlibrary:extend-publish 0.4.0 <- peerlibrary:publish-context 0.5.0 <- cultofcoders:redis-oplog 1.2.5_1
* babel-compiler@6.13.0 <- coffeescript 1.11.1_4 <- peerlibrary:publish-context 0.5.0 <- cultofcoders:redis-oplog 1.2.5_1
````
I've tried to upgrade `peerlibrary:publish-context` to 0.6.0 but the error is the same. As I removed the dependency to`peerlibrary:publish-context`, I was able to upgrade (is the package used at all by `redis-oplog`?).

Sadly, the optimistic ui issue still occurs with 1.2.6 :(

**Comment by theodorDiaconu** [comment]
@maxnowack removed dependency of publish-context. I've tested the repo, it now works in 1.2.6

**Comment by maxnowack** [comment]
@theodorDiaconu still doesn't work for me in my reproduction repo (https://github.com/maxnowack/meteor-redisoplog-latencycompensation/tree/user-profile) … :(

**Comment by theodorDiaconu** [comment]
Run redisoplog by settings.json and put it first. And it works.

Regards,
Theodor

**Comment by maxnowack** [comment]
Yes, I can confirm that it works when initializing redisoplog by settings.json.
Sorry, my fault 😬

It's fixed. Thank you! 🎉

**Comment by theodorDiaconu** [comment]
Nice, few more bugs to go, and maybe ObjectId support, and it'll be good for launch!
