### ISSUE TITLE
Error: Unrecognized logical operator: $text

### ISSUE THREAD

**Issue by jasongrishkoff** [cult-of-coders/redis-oplog#229]
Is there support for MongoDB Text Search?  My queries are all bumming out with the following error:

`Error: Unrecognized logical operator: $text`

Here's an example query I'm trying to run:

```
Meteor.publish('campaign-search', function publishFunction(string) {
        var query = {$text:{$search:string}}
        var campaigns = Campaigns.find(query)   
        return campaigns
}) 
```

**Comment by theodorDiaconu** [comment]
@jasongrishkoff $text is not supported by minimongo. Therefore cannot be used inside a publication. To be able to implement it, we need to extend minimongo and copy the logic of `$text` from MongoDB in it.

**Comment by jasongrishkoff** [comment]
Yes that's right. I'm only running this on server side. Does redis-oplog
pass everything through minimongo? Is there a way to exclude this specific
publication?

On Dec 28, 2017 8:56 AM, "Theodor Diaconu" <notifications@github.com> wrote:

@jasongrishkoff <https://github.com/jasongrishkoff> $text is not supported
by minimongo. Therefore cannot be used inside a publication. To be able to
implement it, we need to extend minimongo and copy the logic of $text from
MongoDB in it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cult-of-coders/redis-oplog/issues/229#issuecomment-354239759>,
or mute the thread

**Comment by theodorDiaconu** [comment]
@jasongrishkoff does it work for you without RedisOplog ? I remember that Meteor didn't support $text

**Comment by jasongrishkoff** [comment]
Yes, it works fine as long as I keep it to the server-side.  It doesn't work client side because of minimongo, as you pointed out, so I've always kept it server-only.

**Comment by theodorDiaconu** [comment]
Can you show me the full stacktrace of this: `Error: Unrecognized logical operator: $text` ?

**Comment by jasongrishkoff** [comment]
```
62fp1
2017-12-27 21:09:16+02:00Exception from task: Error: Unrecognized logical operator: $text
62fp1
2017-12-27 21:09:16+02:00 at Object.keys.map.key (packages/minimongo/common.js:579:15)
62fp1
2017-12-27 21:09:16+02:00 at Array.map (<anonymous>)
62fp1
2017-12-27 21:09:16+02:00 at compileDocumentSelector (packages/minimongo/common.js:572:48)
62fp1
2017-12-27 21:09:16+02:00 at selectors.map.subSelector (packages/minimongo/common.js:560:12)
62fp1
2017-12-27 21:09:16+02:00 at Array.map (<anonymous>)
62fp1
2017-12-27 21:09:16+02:00 at compileArrayOfDocumentSelectors (packages/minimongo/common.js:555:20)
62fp1
2017-12-27 21:09:16+02:00 at Object.$and (packages/minimongo/common.js:260:7)
62fp1
2017-12-27 21:09:16+02:00 at Object.keys.map.key (packages/minimongo/common.js:583:14)
62fp1
2017-12-27 21:09:16+02:00 at Array.map (<anonymous>)
62fp1
2017-12-27 21:09:16+02:00 at compileDocumentSelector (packages/minimongo/common.js:572:48)
```

**Comment by theodorDiaconu** [comment]
Thanks,
The logic is like this: I can adapt redis-oplog to work with the initial fetch, but afterwards we'll have a problem with reactivity. Because when a new document has been updated, we have to check if it still matches the filters so we remove it.

We are using Minimongo filter matcher for this.

We previously had a mechanism where we checked eligibility by the database, meaning we did a find with those filters and an `_id` to see if it's still eligible. We had to drop that approach because it lead to many db requests, especially when we had many publications.

If you want to opt-out of RedisOplog and have mongodb oplog, you can either use pollingIntervalMs, or set `overridePublishFunction` to false and use `publishWithRedis` only when you need it. <-- Bad idea because oplog will still hit your instances. 

Another approach would be to be able to opt-in into the verification by db eligibility, but that would take some time to implement, and it is not currently in the roadmap, maybe if you are interested put up a bounty hunt for it and I can help with guiding them to implement this.

**Comment by jasongrishkoff** [comment]
Would this be the right approach to opt-out for that subscription only?
```
Meteor.publish('campaign-search', function publishFunction(string) {
        var query = {$text:{$search:search}}
        return Campaigns.find(query,
                            {   
                                disableOplog: true,
                                pollingIntervalMs: 20000
                            })
})
```
Tried it on my production, but it doesn't seem to actually return anything.

**Comment by theodorDiaconu** [comment]
I will investigate this.

**Comment by jasongrishkoff** [comment]
@theodorDiaconu any luck here?

**Comment by theodorDiaconu** [comment]
@jasongrishkoff sorry, didn't have time to focus at all on it. I will take care of it this week, going on a 6h-8h marathon of redis-oplog.

**Comment by theodorDiaconu** [comment]
@jasongrishkoff I think I nailed it, tests are passing. Sorry for delay.

**Comment by theodorDiaconu** [comment]
@jasongrishkoff it works with polling. And I think it also works without it, but that is outside my scope currently. You can try it out, what I did basically is: if minimongo can't support certain mongodb operators, $text, $geo, etc, it will fallback to checking eligibility of the document by interogating the database using `_id` and its filters. It will still be super performant.

https://github.com/cult-of-coders/redis-oplog/blob/release/1.2.6/testing/polling/client.js
