### ISSUE TITLE
Production deployment question: where to deploy the redis server

### ISSUE THREAD

**Issue by ujwal-setlur** [cult-of-coders/redis-oplog#232]
Hello,

This is not a bug, but a question. I am getting ready to deploy my app on Meteor Galaxy, and my question is basically what options I have on where to host/deploy the redis server. What have people's experiences been? Cost is an issue for me, so I would love to hear suggestions that would work with the app being hosted on Galaxy.

Thanks,

-ujwal

**Comment by jasongrishkoff** [comment]
I was able to run it quite easily on a $15/mo Digital Ocean droplet -- could possibly have gone even smaller.

**Comment by theodorDiaconu** [comment]
@ujwal-setlur galaxy is on AWS. I would buy a instance in the same region, the smallest one (micro) would do for lots of traffic. In my opinion ubuntu 512m is more than enough!

**Comment by ujwal-setlur** [comment]
Thanks for the suggestions!

**Comment by ujwal-setlur** [comment]
One more question. Just redis instance should be fine right? Or do I need sentinel? Do I need to worry about HA for redis?

**Comment by jamesgibson14** [comment]
I use RedisLabs $5 /month memory only, and it works great.

**Comment by evolross** [comment]
I just started a redis deployment on compose.io and it's working great. My settings are 256MB memory for two nodes and 64MB memory for the TCP Portal. It handled about 5000 simultaneous users with absolutely no problem and barely any memory usage.

However, it's $18.50 per month, so maybe I'll consider some of these other options.  Quick question, compose.io has two "modes" for redis: "storage" mode and "cache" mode.  I left it on "storage" mode as that's their default. It says the difference is "storage" mode autoscales as if you're keeping things in redis where "cache" mode automatic scaling and backups are disabled and it's "better tuned to perform better as a cache". I'm assuming "cache" mode may be better.

**Comment by theodorDiaconu** [comment]
I think it's all clear, closing this issue to keep things study.
