### ISSUE TITLE
How to configure without using settings.json file ?

### ISSUE THREAD

**Issue by hems** [cult-of-coders/redis-oplog#233]
- [x] A description of the problem you're trying to solve, including *why* you think this is a problem
 ~> I'm currently deploying my node.js apps to Heroku using [this buildpack](https://github.com/AdmitHub/meteor-buildpack-horse) and i have no settings.json on my project

- [x] An overview of the suggested solution (if you have an idea)
 ~> I'm currently using ENV VARIABLES to setup my application and i prefer to setup my variables this way instead of settings.json

- [x] If the feature changes current behavior, reasons why your solution is better
 ~> I'm not sure if you already have an alternative version for settings.json but considering I already have an "dotenv" for each environment I would prefer to have the settings on my "env" instead of having multiple "env" files and multiple "settings.json" files

Thank you for such amazing work!

**Comment by theodorDiaconu** [comment]
@hems very strange that a deployment solution does not allow you to use settings.json which are incredibly useful.

You have an alternative:
```
// must be the first thing that runs on the server, before anything else.
import {RedisOplog} from 'meteor/cultofcoders:redis-oplog';

RedisOplog.init({ same_options_as_under_redisOplog });
```

This is prone to some errors, especially if you use packages that create publications already, and they are loaded before Meteor gets the chance to initialize RedisOplog, this is why the settings.json file was a better idea.

**Comment by maxnowack** [comment]
You can use the `METEOR_SETTINGS` environment variable on heroku to configure your app: https://docs.meteor.com/environment-variables.html#METEOR-SETTINGS
