### ISSUE TITLE
Meteor Method Find-Update Somehow Populates Clients Subscription With Documents

### ISSUE THREAD

**Issue by evolross** [cult-of-coders/redis-oplog#238]
I have a Meteor Method that "resets" a collection by updating a field in all the documents in the collection. The method is in both client/server code and performs a `find` on the collection and then an `update`. It's very strangely somehow updating all clients' paginated pub-sub subscription to the same documents with _every_ document.  It even happens across various clients/browsers.  This very well may be a gross error in my part in my code - my apologies in advance.  Though, without `redis-oplog` and `disable-oplog` this issue doesn't occur.

The publication is:
```
  Meteor.publish('tasksByPage', function(limit, skip) {
    // Check inputs
    var positiveIntegerCheck = Match.Where(function(x) {
        check(x, Match.Integer);
        return x >= 0;
    });
    check(limit, positiveIntegerCheck);
    check(skip, positiveIntegerCheck);

    console.log("limit: ", limit);
    console.log("skip: ", skip);

    //  Return page-limit of tasks at a time, sorted by their creation date, 
    //  and skipped to the correct page
    return Tasks.find({
      $or: [
        { private: { $ne: true } },
        { owner: this.userId },
      ],
    }, {
      sort: {createdAt: 1},
      limit: limit,
      skip: skip
    });
  });
```
The subscription is:
```
Template.body.onCreated(function bodyOnCreated() {

  //  Set instance reference
  var instance = this;

  instance.state = new ReactiveDict();

  //  Create reactive var to hold page
  instance.page = new ReactiveVar(0);
  instance.tasksPerPage = 5;

  //  Autorun Subscription
  instance.autorun(function() {

    instance.subscriptions = [
      instance.subscribe('tasksByPage', instance.tasksPerPage, instance.tasksPerPage * instance.page.get()),
      instance.subscribe('scorecard')
    ];
  });

});
```

The Meteor Method (and offending code) is:
```
resetTasks: function() {

    var userId = Meteor.userId();

    //  Ensures a user is logged in
    if(!userId) {
      console.log("SERVER ERROR: resetTasks: You need to be logged in to reset tasks."); 
      throw new Meteor.Error(401, 'You need to be logged in to reset tasks.');
    }

    //  Find the tasks       
    var tasks = [];

    tasks = Tasks.find({
      $or: [
        { private: { $ne: true } },
        { owner: this.userId },
      ],
    }).fetch();

    //  THIS IS THE OFFENDING CODE THAT POPULATES THE SUBSCRIPTION
    //  Update all tasks with something arbitrary
    Tasks.update({_id: {$in: _.pluck(tasks, '_id')}}, {$set: {isReset: "Was Reset!"}}, {multi: true}, function(error) {
        if(error) {
            console.log("SERVER ERROR: resetTasks: Server Error resetting all tasks: " + (error.reason ? error.reason : error.message));
            throw new Meteor.Error(500, "Server Error resetting all tasks: " + (error.reason ? error.reason : error.message));                    
        }
    });
  }
```
If I comment out the collection `update` and only do the `find` in the method, it doesn't publish all the documents. But I have no idea why. I even `console.log` the `limit` and `skip` going into the publication but they never get updated with values that would display _all_ the documents.

I've created a fairly simple Meteor 1.5.2 repo based on Meteor's Simple Todos app to reproduce the issue at:

[https://github.com/evolross/redis-oplog-issues](https://github.com/evolross/redis-oplog-issues)

To reproduce, do the following easy steps:
- Download the repo and setup a localhost Redis
- Run `meteor --settings settings.json`
- Create an account in the app
- Click on the "Add Twenty Tasks" button at the bottom to quickly make twenty tasks so pagination can be demonstrated. You will now see only five tasks because your tasks will be paginated in groups of five. Feel free to play with the pagination buttons. **NOTE:** The `taskCount` is hard-coded at twenty in the app, so pagination is based on this. In my real app, I denormalize the `taskCount` to another collection. For the purposes of this repo, it assumes you always have twenty tasks. 
- Click on the "Reset Tasks" button. Now watch the pagination break and the UI fill with all twenty tasks. If you had `msavin:mongol` open (by clicking CTRL-M), you would see that the actual `Tasks` subscription fills up with all twenty documents versus five. If you page forward, backward, or refresh, the subscription starts working correctly again.
- Click the "Remove All Tasks" button to clear the tasks and try it again.
- If you have several different clients open (e.g. Chrome, Firefox, Safari) all logged into the same user, it happens on all clients
- Remove `redis-oplog` and `disable-oplog` and the subscription does not fill up with all twenty documents

**Comment by evolross** [comment]
An interesting update: if you follow the above steps, but click the "Next 5 Tasks" buttons at least once, which skips to the next page of five questions (and sets the `skip` in the publication), the subscription does not get all twenty tasks and the problem doesn't occur. 

Calling the Reset method only causes the problem on the first page of questions where `skip` is zero and `limit` is five` (`limit` never changes).

Is there some issue with having a mongo query's `skip` set to zero?

**Comment by theodorDiaconu** [comment]
@evolross thank you very much for the time spent to make this very clear task description! This is definitely a weird bug. On it.

**Comment by theodorDiaconu** [comment]
Found the culprit and fixed it. Cheers.
