### ISSUE TITLE
Meteor method stack traces contain many duplicate Mongo queries and take much longer to finish

### ISSUE THREAD

**Issue by evolross** [cult-of-coders/redis-oplog#241]
In our app, users can perform transactions by clicking buttons that call a Meteor Method to do an `insert` into a given collection.  Before the `insert`, the Meteor Method does several Mongo `find` queries on various collections in order to validate the incoming set of document `ids` (checking for existence and threshold counts mostly), then it does the `insert`. Additionally, my project uses `matb33:collection-hooks` and there is a collection-hook that fires on the `insert` (and more collection-hooks that fire based on that code - see below).  Lastly, I have an `update` that happens in a nested callback of the final `insert`.  I know there's some possible issues with `redis-oplog` and nested callbacks (perhaps with `matb33:collection-hooks` too).

Using regular `oplog` tailing, looking at Galaxy's Meteor APM stack traces of the Meteor Method, I see a **near** perfect output of Mongo calls in the stack trace that matches my method code.  The only differences are the stack doesn't seem to show any of the collection hooks Mongo calls nor the `AnonymousUsers.update` that happens in the callback of the final `insert`.

Here are all the Mongo queries being made in my method `castMultipleChoiceVote` and all collection-hooks listed out as they are in the code:

```
Questions.findOne({...}, {...});
Answers.find({...}).count();
Experiences.findOne({...}, {...});
AnonymousUsers.findOne({...}, {...});
Votes.find({...}).count();
Polls.findOne({...}, {...});
Votes.insert({...}, function(error) {  // Has a Votes.after.insert collection-hook (see below)
   //  The nested callback update
   AnonymousUsers.update({...});
});
```
My `Votes.after.insert` collection-hook does the following (which is updating a lot of denormalized counters):
```
Answers.update({...});  // Has a Answers.after.update collection-hook but doesn't do any extra Mongo calls
Experiences.findOne({...});
Answers.findOne({...});
Questions.update({...});
Polls.update({...});  //  Has a Polls.before.update collection-hook but doesn't do any extra Mongo calls
Votes.find({...}).count();
Experiences.update({...});
```

Here is the stack trace. It takes **84ms** to complete. It does **not** show any of my collection-hook Mongo calls nor my callback `AnonymousUsers.update`. Notice that a `findOne` from my method calls a Mongo `find` and a `fetch` and that a `count` from my method calls a `find` and a `count`:

![goodoplogstacktrace](https://user-images.githubusercontent.com/7980725/35755711-323e2d9e-081d-11e8-84a6-5e38435ac0cf.png)

When I add `redis-oplog`, the same stack traces now show everything from the above stack trace **and** the collection-hook Mongo calls and the nested update (at the very end) but also a whole lot more additional Mongo calls. This trace took **1227ms**.  The stack trace is so long I had to screen grab it three times and reassemble in Photoshop.  The extra Mongo queries are not a Meteor APM hiccup, the method actually takes _way_ longer to finish and consequently with a lot of users my app grinds to a halt.  Also, any `insert` and `update` calls do not get duplicated, _only_ the `find` and `count` calls, so functionally it works correctly (which made this issue particularly insidious). It seems like there are extra calls that are "echoing" or something. Here's the faulty stack trace with the `insert` and `update` calls highlighted:

![redisopologstacktracebad](https://user-images.githubusercontent.com/7980725/35761144-52a1dca8-083a-11e8-899a-51c68b239e7e.jpg)

If needed, I can make a repo with similar code to my app, but I'm not sure how you'll reproduce/verify the error without uploading to Galaxy. I'm not sure of a way to log the Mongo calls like Meteor APM does. I added lots of `console.log` call in my Method just to see if the code was being fired multiple times and it is not.

**Comment by theodorDiaconu** [comment]
84ms vs 1227ms is huge! 
I see there is something very weird with fetch on experiences, answers:

307 + 386 + 201 = 894ms + some other find & fetches. I think there's something else very weird at play. Since Redis-Oplog does not touch find().fetch() at all!

Things that I find strange is why with redis-oplog you have update on anonymousUsers,polls,questions,answers and without it you don't ? 

As a rule of thumb, `update` and `remove` mutations trigger a find().fetch() . I would really love a reproduction for this.

**Comment by evolross** [comment]
A couple of updates on this:

I was trying to solve another bug I found in `mat3bb:collection-hooks` and was reading the docs and noticed that any `Collection.after.update` hook does an extra `fetch()` on the collection to return something called `this.previous` for use within the hook. I have an `Answers.after.update` that gets fired in the above Method so that may explain _one_ of the extra sets of `find();fetch()` on Answers. This can be disabled and I'm not using `this.previous` in the hook so I will indeed disable this.

As for why I have an update on AnonymousUsers, Polls, Questions, and Answers with `redis-oplog` is because `redis-oplog` is actually showing the mongo updates that the `Votes.after.insert` is running (and the nested callback update of AnonymousUsers).  Why `redis-oplog` shows in the stack trace and by default they are not shown... I don't know.  Perhaps Meteor APM doesn't "bind" collection-hook updates and nested callbacks to the actual Method stack trace. But with the way `redis-oplog` works they do get "bound" to the Method stack trace.

Looks you'll need a repo for this so I'll get to work. This is the biggest showstopper for me and using `redis-oplog` as my app grinds to a halt with a lot of users.

**Comment by theodorDiaconu** [comment]
I found the issue... and it's because of the way callback work. They are usually run in a separate fiber. That's why those weren't caught in the method stacktrace, because they were executed in another fiber after method returned.

What is still worrying me is those large find() fetch(), 300ms is huge! check your indexes. Also I've done an update that executes callbacks in another fiber like Meteor intended to.

**Comment by evolross** [comment]
I was looking into Events instead of callbacks but at first glance I couldn’t figure out how to ensure “order of execution” how you can with callbacks. Unless you have event-1 call event-2 and so on. Is that the approach?

And callbacks are featured all throughout the Meteor docs and guide. Seems like they’re recommended by MDG’s standards.

**Comment by theodorDiaconu** [comment]
@evolross I would avoid them because they are not real callbacks. Because you have to wait for the update to actually run before returning example:

X.update(..., callback)
===
X.update(...)
Meteor.defer(callback);

**Comment by evolross** [comment]
I've went over my indexes so many times over the years trying to diagnose other problems, I'm pretty sure I have them all set correctly. Besides, when I do a `fetch()` on Experiences, it's always via `_id` so an index issue shouldn't exist.

Notice that without `redis-oplog` that very first `fetch()` on Experiences (the one that's actually in my Method code - not a callback or collection hook) only takes 11ms versus 307ms. In both tests, I was just clicking the vote button a few times in a row. Enough to get Galaxy to register a stack trace.  My point is the usage/traffic was the same with and without `redis-oplog`. It wasn't like each of my tests had a different amount of Mongo traffic to deal with... unless `redis-oplog` is adding more and thus causing Mongo to delay.  Probably not the case, but I still have no idea why there's so much extra Mongo calls in the stack trace and why it takes longer.

As far as the callbacks, how you describe them is _why_ I use them. I want the `update` to complete _then_ I want the callback to run. In some cases, need to use the `result` of the update in the callback (just like in the Meteor guide).

It's interesting that the Meteor APM stack trace, without `redis-oplog` isn't showing anything that runs in a callback or collection hook... that may mean that my Method is _actually_ taking as long as the `redis-oplog` stack is saying it does, but the non `redis-oplog` stack trace is just not showing it.  Maybe for these types of heavy use Methods I should move all the code as much as I can into the Method.

The weird thing is if the above paragraph is true, that doesn't explain my horrible performance with `redis-oplog`.  When I did my New Year's Eve project with the huge crowd, because of the response times I saw in Meteor APM with or without `redis-oplog`, I wrote special hot-rod version of the above Method that _only_ did an `insert`, no other Mongo calls.  It ran beautifully with `redis-oplog` and the project was a success.  **But** I left `redis-oplog` enabled on my production server and for every other project/user they used the above version of the Method with all the checks and hooks.  That's when everything ground to a halt and I had angry customers.  I didn't realize the problem because I thought the issues with `redis-oplog` were just from the fact I was doing cloud tests with 5K - 10K users to prepare for the NYE project.  I just assumed with that many simultaneous users, even `redis-oplog` can't handle this Method, hence the hot-rod `insert` only version.  I assumed a normal size crowd of 100 - 1000 users would be fine... **wrong** and that's on me for not testing first. `redis-oplog` was returning response times of 20s, 40s, sometimes 100s on the above method!  Disabling `redis-oplog` immediately fixed the problem. Crowds of 100 to 1000 get less than 1s response time instead of 100s. So the paragraph above this can't be true.  There's actually extra Mongo stuff happening that's taking longer and causing problems.

Once we get this issue solved, I'm sure `redis-oplog` will perform better than regular `oplog` as it did on my hot-rod `insert` only method (and I will cloud-test and document this).  And that's why I want to use it.  As regular `oplog`, while performing well, hit's a limit once you get to a few thousand users.

**Comment by theodorDiaconu** [comment]
@evolross thanks for your detailed feedback. The reason is that callbacks were executed in sync, this is why they appeared in the method callstack. But 301ms vs 20ms for a db query is something very strange and I'm not sure how it can even be impacted by redis-oplog, that thing is not touched.

**Comment by evolross** [comment]
The mongo query time could be impacted if `redis-oplog` is doing lots of extra Mongo stuff and thus causing Mongo to be bogged down with extra queries. It could also be that Meteor APM is returning false results, I've seen that too when the CPU spikes. The CPU isn't spiking here though.  And things are taking how long Meteor APM stack traces are saying they're taking, so...

I'll make a repo and test in Galaxy and then post it.

**Comment by theodorDiaconu** [comment]
@evolross it's doing extra stuff when performing mutations. But you mentioned this order:
```
Questions.findOne({...}, {...});
Answers.find({...}).count();
Experiences.findOne({...}, {...});
AnonymousUsers.findOne({...}, {...});
Votes.find({...}).count();
Polls.findOne({...}, {...});
Votes.insert({...}, function(error) {  // Has a Votes.after.insert collection-hook (see below)
   //  The nested callback update
   AnonymousUsers.update({...});
});
```

So before it reaches Votes.insert, it doesn't do anything. It's like it doesn't exist. This is why it's so strange.

**Comment by evolross** [comment]
I did a Galaxy test using my [redis-oplog-issues](https://github.com/evolross/redis-oplog-issues) repo.  I'm using Meteor 1.5.1 and `redis-oplog@1.2.6_2`.  

There's more Mongo calls happening in the `redis-oplog` version of the app on Galaxy versus the the `oplog` version as expected, but I'm not seeing the dramatic speed differences. And on some stack traces the `redis-oplog` runs faster than the `oplog` version. This could be because the brevity of the Mongo calls doesn't exacerbate the problem enough to show a measurable delay.  

Below are the stack traces.  Here's the Mongo code that's being called when you click the "Toggle Scorecard" button:
```
Scorecards.findOne({...});
Tasks.findOne({...});
Tasks.find({}).count();
Scorecards.update({...}, function(error) {  
   Tasks.update({...}); //  Has a Tasks.before.update collection-hook (see below)
});
```
And the `Tasks.before.update` calls:
```
Scorecards.update({...});
```
Here is the `oplog` stack trace of the above:
![todostoggle_oplog](https://user-images.githubusercontent.com/7980725/36449093-9170afa6-163e-11e8-880e-b5907a87fbe0.png)
Here is the `redis-oplog` stack trace of the above:
![todostoggle_redisoplog](https://user-images.githubusercontent.com/7980725/36449100-9ba73904-163e-11e8-85cd-6fd8b09bba40.png)

One interesting thing to note is that the `oplog` stack trace has two calls of `fetch on scorecards` where the `redis-oplog` stack trace has five calls of `fetch on scorecards`. Even if the `redis-oplog` stack trace is displaying the extra `Scorecards.update` happening in the `Tasks.before.update` collection-hook, I'm not sure why it's three extra `fetch on scorecards` versus one or two extra.

Perhaps you can run this yourself and/or explain the extra calls being made.  To test, the [redis-oplog-issues](https://github.com/evolross/redis-oplog-issues) repo has been updated.  It's ready to go in `redis-oplog` mode right now. Simply update the Mongo URL and Redis URL in ./settings.json.  You can send it up to Galaxy and test. Then to test in `oplog` mode just update the packages and Mongo Oplog URL.

In the app, reset the database, make a user, click "Add Twenty Tasks" button, check the first task to create a scorecard, then click the "Toggle Scorecards" button and increment the score up to 500. This should be enough for Galaxy to register a stack trace.

**Comment by evolross** [comment]
Not sure I understand entirely.  

Instead of having a global `optimistic` flag, would there be a way to pass individual queries an `optimistic: false` flag?  For problematic scenarios like this?

**Comment by theodorDiaconu** [comment]
@evolross so here is the flow:
1. You do an update
2. RO fetches the ids of the items you want to update
2.1 RO checks if optimistic flag is on, if yes it executes updates **in sync** so they are applied before the method returns
3. RO pushes then the updates individually to redis-oplog and to their general channel

Yes, you can use ```{optimistic: false}``` to individual queries. I agree, optimistic true will slow your app down a lot in some scenarios, there wasn't any other way... This is why I suggest you avoid it as much as you can, the changes are going to happen instantly anyway.

**Comment by evolross** [comment]
Just a quick update to this... I'm circling back experimenting with `optimistic: false` on all the updates of my test repo. I added this setting and the stack trace is still exactly the same. Same amount of extra Mongo calls being made. The other thing I noticed is setting `optimistic: false` on an `update` on the client for a field that controls a display element in the template (like a status pill from my other bug) is now jumpy again.  I'm assuming this because `optimistic: false`. I mention it only because I know my changes are in effect.

I thought you were saying if I added `optimistic: false` to my updates, that `redis-oplog` _wouldn't_ do those extra fetches and potentially bog down Mongo with extra calls.  If that's not the case, where do see the performance gain when adding `optimistic: false` to your `updates`?

Here's the trace:

![todos_redis_2](https://user-images.githubusercontent.com/7980725/37544753-5713ed9e-2923-11e8-8847-c1306d1f76f0.png)

**Comment by theodorDiaconu** [comment]
@evolross optimistic: true, does in sync the change processing of changes. Meaning if you update X, it tries to imediatelly update all of your local observers. Those extra fetches are unavoidable with or without optimistic false. What I don't understand is why are those extra fetches this heavy..
