### ISSUE TITLE
Meteor.userId can only be invoked in method calls or publications

### ISSUE THREAD

**Issue by jasongrishkoff** [cult-of-coders/redis-oplog#243]
Hi there!

Testing the new version on Meteor 1.6.1 and am encountering this error:

`Exception in defer callback: Error: Meteor.userId can only be invoked in method calls or publications.`

This seems to happen in methods that have deferred callbacks or Promises, such as this:
```
Meteor.methods({
  saveData(data) {
    Data.insert(data,function(error,response) {
        var to = getEmail(Meteor.user())
        var subj = 'Your data has been saved!'
        var html = 'Good job.'
        Meteor.call('sendEmail',
    })
  }
})
```

Without redis-oplog this works just fine.  However, with redis-oplog this results in the above error.  The above is just example code -- here's the error in my Galaxy logs:
```
Exception in defer callback: Error: Meteor.userId can only be invoked in method calls or publications.
at AccountsServer.userId (packages/accounts-base/accounts_server.js:79:13)
at AccountsServer.user (packages/accounts-base/accounts_common.js:58:23)
Object.Meteor.user (packages/accounts-base/accounts_common.js:282:19)
at ns.Collection.<anonymous> (server/methods/data.jsx:48:60)
at Meteor.defer (packages/cultofcoders:redis-oplog/lib/mongo/Mutator.js:43:29)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
at packages/meteor.js:502:25
at runWithEnvironment (packages/meteor.js:1240:24)
```

It does make sense to me that perhaps I shouldn't be calling Meteor.user() inside these deferred callbacks, but this approach works fine in Meteor -- it only seems to break with redis-oplog enabled.

**Comment by amsinha2** [comment]
Hello, 
Im on redis-oplog@2.0.5 again and am seeing this pop up in my environment.  Could it have been reintroduced?
