### ISSUE TITLE
No data inside redis

### ISSUE THREAD

**Issue by adalidda** [cult-of-coders/redis-oplog#244]
Hi,

I just added redis oplog to my Meteor 1.6.1 + GraphQL + react App. My app works well after adding redis oplog. When I check the log, my app is really connected to redis. However, when I check my redis db, I notice that there are no data inside it.

Is it a problem between GraphQL and redis oplog ? Is that mean my app still use mongodb oplog instead of redis oplog ?

Thank You
Adalidda

**Comment by theodorDiaconu** [comment]
@adalidda how do you check whether data is inside redis ? Grapher uses redis' PubSub, doesn't store anything inside it. Did you check-out `redis-cli monitor` and do some mutations inside the app to see what happens ?

**Comment by theodorDiaconu** [comment]
Closing this.
