### ISSUE TITLE
Setting overridePublishFunction to false still publishes via Redis

### ISSUE THREAD

**Issue by evolross** [cult-of-coders/redis-oplog#245]
In Meteor 1.5.1 in `redis-oplog` 1.2.6, 1.2.6_1, and 1.2.6_2, whenever I set `overridePublishFunction: false`, I'm still seeing all of my app's `Meteor.publish(...)` calls getting published with Redis.

I can see it in the debug output of `redis-oplog` and the publications are visually/functionally reactive in my app.

I was adding some special functionality with `Vent`, which is really cool BTW, and needed to add `redis-oplog` but I don't want any of my publications (or app in general) to use `redis-oplog` (for now) except my `Vent` code.  So I set `overridePublishFunction: false`, yet it's still using `redis-oplog`. I do still have `pushToRedis: true` but I assumed this would be ignored if I have  `overridePublishFunction: false` and use all `Meteor.publish(...)` calls.  

I can make a repo but it's pretty easy to reproduce.  I created two Meteor apps from my [redis-oplog-issues](https://github.com/evolross/redis-oplog-issues) repo, set  `overridePublishFunction: false` on both, made the second app point to the first app's database and ran it on port 3002.  Then when you click add twenty tasks, check one off to create a Scorecard, then click "Toggle Scorecards" it updates instantly in both apps via Redis because the `Meteor.publish(...)` calls are using Redis.

**Comment by evolross** [comment]
Just an update to this, I was looking through the `redis-oplog` code and in /lib/init.js, the following code is working correctly:
```
if (Config.overridePublishFunction) {

     Meteor.publish = Meteor.publishWithRedis;
     Meteor.server.publish = Meteor.publishWithRedis;
}
```
So the `Meteor.publish` does not get overridden. However, in the debug output I'm seeing tons of `[PublicationEntry]` and `[PublicationFactory]` and `[RedisSubscriptionManager]` calls.  It looks like it's still observing publications that get subscribed to.

I tried setting `pushToRedis: false` in the settings, thinking maybe this would turn off the auto-observing of my publications by `redis-oplog` but that broke my app and no buttons or anything worked any longer.

I've been looking at the code trying to figure out what's going on but it's too involved.  I would really like to use Vent but I can't get my publications to _not use_ `redis-oplog`.

**Comment by theodorDiaconu** [comment]
The reason is because of this: `extendMongoCollection();` which overrides the .observeChanges() and .observe()

**Comment by theodorDiaconu** [comment]
There is no way I can make this work without making it prone to many other breaks in the way redis-oplog works. Sorry :( RedisOplog should not live along-side MongoDB Oplog it's not designed for this.

**Comment by evolross** [comment]
Fair enough. I suppose if I wanted to just have Vent-only functionality I could fork `redis-oplog` and try to roll my own solution.  The good news is I rewrote some of my methods in my app without using a lot of callbacks and no collection hooks and I'm getting stack traces with `redis-oplog` that match oplog-tailing now. So I should be able to incorporate `redis-oplog` finally. Doing cloud tests this week.

**Comment by evolross** [comment]
Just for conversation purposes... one reason it would be useful to use Vent without `redis-oplog` is if you make use of a micro-service structure (which I do in my app).

So I may have a particular micro-service that needs to listen for Vent emissions but doesn't need to use `redis-oplog` for pub-sub.

To make use of Vent now, I have to upgrade all my micro-services to `redis-oplog` - which is probably a good thing. But not all of them are overwhelmed by oplog-tailing.
