### ISSUE TITLE
Virtual Mutations

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#25]
You have chat, someone is typing... you don't actually want to save that, it can kill the db, but you can emulate it as if it was written in db, by sending a message to redis. 

Think about this. It can be crucial to interactive apps, games, chats, etc.

**Comment by theodorDiaconu** [comment]
```
import { SyntheticMutation } from 'meteor/cultofcoders:redis-oplog';

SyntheticMutation.insert(channel, data);
SyntheticMutation.update(channel, _id, data);
SyntheticMutation.remove(channel, _id, data);
```

**Comment by ElegantSudo** [comment]
This is a great idea. So basically Redis will publish this as data, even though it's not actually stored in Mongo?

**Comment by theodorDiaconu** [comment]
You are correct!
