### ISSUE TITLE
getFieldsOfInterest incorrect for some combination of queries & fields

### ISSUE THREAD

**Issue by nathan-muir** [cult-of-coders/redis-oplog#250]
**Issue**
Non-reactivity/incorrect publish when a query contains a selector + fields-specifier on the same nested document.

**Breakdown**
Given a query:

```js
Collection.find({
  'prop1.subprop': val
}, {
  fields: {
     prop1: true
  }
});

```

`ObservableCollection#_getFieldsOfInterest` / `getFieldsOfInterestFromAll` would return:

```js
[ 'prop1', 'prop1.subprop' ]   // should only get [ 'prop1' ]
```

`RedisSubscriptionManager#getDoc` seems to return a result only containing `prop1.subprop`, thus preventing any other data from `prop1.otherProp` arriving to subscribers.

**Solution**

(Perhaps) update [cache/lib/extractFieldsFromFilters.js#L13](https://github.com/cult-of-coders/redis-oplog/blob/master/lib/cache/lib/extractFieldsFromFilters.js#L13) from `filterFields.push(field)` to `filterFields.push(field.split('.')[0])`

Or, some other solution involving `getTopLevelFields`

**Comment by theodorDiaconu** [comment]
@nathan-muir nice find, will solve.
