### ISSUE TITLE
ObservableCollection re-use causes $unset fields to appear as undefined

### ISSUE THREAD

**Issue by nathan-muir** [cult-of-coders/redis-oplog#252]
When an observer is re-used, previously `{$unset: {someKey: true}}` fields appear on _new_ clients as `{someKey: undefined}`.

Note: I'm planning on creating a test case to illustrate this, but this may serve as a placeholder until then.

Reproduction for top-level fields:
```js
// shared.js
const collection = new Mongo.Collection();
if (Meteor.isServer){
   Meteor.publish('collection', ()=> collection.find());
} else {
   Meteor.subscribe('collection')
}

// Open browser for User#1
// paste into console
collection.insert({ _id: 'a', field1: 'hello', field2: 'world' })
collection.update({ _id: 'a' }, { $unset: { field2: true } })
collection.find({}).fetch()
// {_id: 'a', field1: 'hello'}


// While User#1 Still connected.
// Open browser for User#2
// Note: redis-oplog debug should say 
//   "Re-using existing publication ..." and then 
//   "Performing initial add..."
// paste into console
collection.find({}).fetch()
// {_id: 'a', field1: 'hello', field2: undefined}
```

----

Tracing the cause:

 - When a field is `$unset` [`processUndefined` sets the key to `undefined`](https://github.com/cult-of-coders/redis-oplog/blob/master/lib/cache/ObservableCollection.js#L217) so that the field is ovewritten when calling `deepExtend`
 - When a new client shares the same subscription, the cached docs with `undefined` on some fields are sent to the client via [`PublicationEntry#_performInitialAddForObserver`](https://github.com/cult-of-coders/redis-oplog/blob/master/lib/cache/PublicationEntry.js#L171)
 - `meteor/ddp-server` handles `undefined` values differently in [`added`](https://github.com/meteor/meteor/blob/devel/packages/ddp-server/livedata_server.js#L183-L196) and [`changed`](https://github.com/meteor/meteor/blob/devel/packages/ddp-server/livedata_server.js#L162-L181) callbacks

Possible Solutions:
 - Update `meteor/ddp-server` to call `docView.clearField` for `undefined` values in `SessionCollectionView#added`
 - Remove `undefined` values from docs during `PublicationEntry#_performInitialAddForObserver`
 - Refactor `ObservableCollection#change` so that unset fields are removed instead of being overwritten with `undefined`.

**Comment by nathan-muir** [comment]
Attempt at a fix here: https://github.com/nathan-muir/redis-oplog/commit/e009efff47c6cd2b9bed310130bb58531a313107

**Comment by theodorDiaconu** [comment]
@nathan-muir another solution would be to get which fields became undefined, send them as undefined through ddp, but remove them from the observable collection's store. What do you think ?

**Comment by theodorDiaconu** [comment]
Solution: processUndefined() should return a list of fields that it made undefined, even nested fields, or top level fields. Then we need to send the 'undefined' change down, but after we do that send to make sure that we remove those fields from the current collection store.

**Comment by nathan-muir** [comment]
@theodorDiaconu I've thought about this a lot, and I think `ObservableCollection#change` needs to be rethought a little.

A few questions came up when reading/refactoring the function:

1. Why extend the stored document? Don't we now fetch the whole document from MongoDB anyway?
2. Why rely on `modifiedFields`? this would clobber changes caused by `this.options.transform`.
3. Why the second call to `projectFieldsOnDoc(changedTopLevelFields)` Meteor shouldn't send any undefined value via `changed`

Ideally, Meteor would implement `Session#replace` so we could skip worrying about the `undefined` top level fields. But we can implement the same thing with `meteor/diff-sequence`

How does this look:
```js
    change(doc, modifiedFields) {
        const docId = doc._id;
        if (!this.store[docId]) {
            return;
        }
        const oldDoc = this.store[docId];
        let newDoc = cloneDeep(doc);
        if (this.fieldsArray) {
            newDoc = this.projectFieldsOnDoc(newDoc);
        }
        if (this.options.transform) {
            newDoc = this.options.transform(newDoc);
        }
        this.store[docId] = newDoc;
        this.send('change', docId, diffDocument(oldDoc, newDoc)
    }
```

`diffDocument` could be implemented with the meteor internal `diff-sequence` package

```js
// Code from meteor/ddp-server/livedata_server.js#144
function diffDocument(oldDoc, newDoc) {
    var self = this;
    var fields = {};
    DiffSequence.diffObjects(oldDoc, newDoc, {
      both: function (key, prev, now) {
        if (!EJSON.equals(prev, now))
          fields[key] = now;
      },
      rightOnly: function (key, now) {
        fields[key] = now;
      },
      leftOnly: function(key, prev) {
        fields[key] = undefined;
      }
    });
}
```

**Comment by theodorDiaconu** [comment]
@nathan-muir first of all, I want to thank you for the level of attention you give to this. Always happy to see developers giving a helping hand. 

Regarding your questions:
1. We do not fetch the whole document from MongoDB. What happens, is that whenever we receive a change on a certain collection, based on all the current observers, we extract the necessary fields from db in 1 request, then we send the document to the processors. Meaning that a certain processor and observable collection may receive fields that are outside of it's scope.

2. I now notice that `modifiedFields` needs to have projection applied to them since the beginning. Otherwise we may head into processUndefined and do unnecessary processing. I do not fully understand the .transform() thingie, maybe a concrete example would help.

3. Meteor does send undefined values, that's how $unset is passed through DDP. This was previously a problem with $unsetting and that's how it was solved.

Your approach seems healthier, since we use logic from Meteor, but my concern is that it may do unnecessary processing. Plus it would not solve the issue we are facing meaning.

**Comment by nathan-muir** [comment]
1. Yes, by "whole document" I did mean "all the necessary fields for this observer". ie a superset of the required fields for the current collection view. ie, nothing is missing.

2. if you have `transform(obj){   return {...obj, extraField: obj.a+obj.b} }` `extraField` is never part of the `modifiedField` set, so changes to it's value are never published.

3. `Session#added` will send undefined values, but `Session#changed` will not. (it's inconsistent!)

The code in https://github.com/cult-of-coders/redis-oplog/issues/252#issuecomment-374794321 solves the `undefined` values on republish, because we skip using `processUndefined` all together.

I think the overhead should be reduced as we're not performing a `deepExtend`, just `EJSON.equals` on the top level fields.

We could perhaps skip the `EJSON.equals` check if `key  in getTopLevelFields(modifiedFields)`.

**Comment by nathan-muir** [comment]
> @nathan-muir first of all, I want to thank you for the level of attention you give to this. Always happy to see developers giving a helping hand.

:+1: All good, thanks for open-sourcing such a great package! 

I'm currently implementing this in a meteor code base with 130k+ LOC; so I'm being very deliberate to understand as many details/implications as possible.

I might also be sending a PR that leverages meteor's optimistic UI internals. ;-P
