### ISSUE TITLE
Subscription readiness callbacks

### ISSUE THREAD

**Issue by simonbelanger** [cult-of-coders/redis-oplog#253]
I've seen a steep increase in some methods throughput after activating this package. I realized those methods are called from subscription readiness callbacks. After deactivating the package, throughput goes back to normal.

![2018-03-19 at 13 00](https://user-images.githubusercontent.com/17987029/37613107-88bf9a44-2b7d-11e8-94d7-c7f3fff94cc0.png)

**Comment by theodorDiaconu** [comment]
@simonbelanger what do you mean, that this package calls those methods ? Why would throughput increase...

**Comment by simonbelanger** [comment]
all those methods are called from the browser in subscription readiness callback, for example:
```
Meteor.subscribe("mySubscription", {
	onReady() {
		Meteor.call("myMethod");
	},
});
```

**Comment by theodorDiaconu** [comment]
And why would adding this package change anything ? Does it get in onReady multiple times ? Could it be that it gets in the onReady() faster ?

**Comment by simonbelanger** [comment]
my guess would be that "ready" events are sent multiple times by the server instead of only once during the subscription lifetime, right now the only link I see with this package is that the behavior started when I added the package and stopped when I removed it

**Comment by copleykj** [comment]
@simonbelanger What exactly is the purpose of calling the method inside onReady? Not that this isn't an issue, but maybe there is a different way to accomplish your intended outcome that will circumvent it.

**Comment by simonbelanger** [comment]
@copleykj the purpose of this pattern is not the point... the package should not change how the ready callback behave (if it does)

**Comment by copleykj** [comment]
You are absolutely right, hence the reason why I noted that it could still be an issue that needs resolution.

**Comment by theodorDiaconu** [comment]
.ready() is sent only once. Help me reproduce this somehow, have you ever checked the client websocket frames ? See if it calls multiple times ?

**Comment by simonbelanger** [comment]
I didn't try to reproduce the issue locally yet, I'll investigate and get back to you

**Comment by simonbelanger** [comment]
It looks like the issue comes from the subscription readiness callbacks behavior and not this package. For subscriptions done in an autorun (like in a `withTracker` HOC), the readiness callback will run every time the autorun is re-executed instead of only once (when the `ready` message is received from the DDP socket) 💩 ...

I'll close the issue. `redis-oplog` somehow amplify the effect but is not the source of the problem.

**Comment by theodorDiaconu** [comment]
@simonbelanger could it be because it can hold more instances on a server, thus increasing throughput / method ?

**Comment by simonbelanger** [comment]
I don't know... Autorun reactivity can cause all kind of highly erratic and unpredictable side effects. I stopped trying to explain them a long time ago 🙈. No such thing as magic I guess.

**Comment by maxnowack** [comment]
@simonbelanger I wrote a package a while ago to reduce reactivity reruns and also to cache subscriptions. We're using it at TeamGrid to have a better control over reactivity. Maybe it's also useful for classcraft 🙂
https://github.com/maxnowack/meteor-reactive-cache

**Comment by simonbelanger** [comment]
Looks like it's working as designed. Well...

https://github.com/meteor/meteor/blob/5fba1fd3e29ae5b16fc9a27c2e6f85a5bf69d7f7/packages/ddp-client/common/livedata_connection.js#L406

**Comment by evolross** [comment]
I try to greatly reduce how much stuff I have in each of my template `autoruns`, that way I can narrow down what is causing re-runs.
