### ISSUE TITLE
Vent Publications Never Die...  They Duplicate.

### ISSUE THREAD

**Issue by evolross** [cult-of-coders/redis-oplog#269]
In integrating Vent into my app, I just noticed through debugging that my Vent publication is duplicating responses to subscriptions and continuing to fire messages after calling `handler.stop()`. When client browsers get refreshed or are HCR'd (Hot Code Reload), you end up getting lots of duplicated publish responses.

I have a publication:
```
Vent.publish({
  'manualReactivity': function(someId) {
    this.on('manualReactivity::' + someId + '::updated', function(response) {
      console.log("manualReactivity PUBLISHER running...");
      return response;
    });
  }
});
```
I have my `Vent.subscribe` call in my parent-most template so it can always be listening for updates. In my `parentTemplate.onCreated` I am subscribing:
```
var instance = this;

instance.manualReactivityListener = Vent.subscribe('manualReactivity', instance.someId);
instance.manualReactivityListener.listen(function(response) {
    // Do stuff...
});
```
In my `parentTemplate.onDestroyed` I am stopping the listener which I thought would tear everything down:
```
var instance = this;

instance.manualReactivityListener.stop();
```
If I open **four** browsers and watch the console on the server after triggering a `Vent.emit('manualReactivity::someId::updated', {someObject});` in my code somewhere, I see the following expected output:
```
manualReactivity PUBLISHER running...
manualReactivity PUBLISHER running...
manualReactivity PUBLISHER running...
manualReactivity PUBLISHER running...
```
If I then refresh all four client browsers, and trigger the `Vent.emit` again, the output is duplicated with the old subscriptions and the new ones created by the refresh:
```
manualReactivity PUBLISHER running...
manualReactivity PUBLISHER running...
manualReactivity PUBLISHER running...
manualReactivity PUBLISHER running...
manualReactivity PUBLISHER running...
manualReactivity PUBLISHER running...
manualReactivity PUBLISHER running...
manualReactivity PUBLISHER running...
```
Same if I an HCR happens.  After lots code updates and HCRs in development, I noticed the output above really growing.

At first I thought the problem was that my `template.onDestroyed` wasn't getting called because of issues with the window closing/refreshing and it not having time to run the `onDestroyed`. I thought maybe it needed to go into a `window.addEventListener('beforeunload')...`  Before doing that, I tried testing `instance.manualReactivityListener.stop();` by moving it to somewhere I can trigger.  After running the line, I do see that the subscription code on my client stops running as expected. But the the above output from the publication code keeps running and duplicating.

What's the Vent policy on ending publications?  Are they not killed when calling `handler.stop()`? Do they die after a certain amount of time? Could this be problematic for the server - with 1000+ clients?

If needed, I can submit a repo, but this is easy to duplicate.

**Comment by evolross** [comment]
I've been looking at the code and I added some debug messages and I can see that when `PubSubManager.unsubscribe(channel, handler)` eventually gets called each time a Vent subscription handle calls `stop()` on the client, `this.channelHandlers[channel].length` never gets reduced and thus the `this._destroyChannel(channel)` never gets called.
```
unsubscribe(channel, handler) {
        this.queue.queueTask(() => {
            if (!this.channelHandlers[channel]) {
                return;
            }

            this.channelHandlers[channel] = this.channelHandlers[channel].filter(_handler => {
                return _handler !== handler;
            });

            if (this.channelHandlers[channel].length === 0) {
                this._destroyChannel(channel);
            }
        })
    }
```
The `filter` directly above looks like it's supposed to reduce `this.channelHandlers[channel]` but in the debug output, `_handler` is the `redisEventHandler` called in the `Vent._extendPublishContext.on` code.  And `handler` is the Vent's `.publish` callback that I defined above.  So they're never equal, which always returns the full length of `this.channelHandlers[channel]`.

**Comment by theodorDiaconu** [comment]
wow, good very good fine, and thanks @nathan-muir for taking charge on this

**Comment by evolross** [comment]
I've verified that @nathan-muir's updates fix the issue.  Thanks so much.  I can see now what the issue was.  

I've also verified that having the `instance.ventListener.stop()` in your parent-most `template.onDestroyed(...)` works great to stop the subscription.  Both on refresh, HCR, and closing the browser window/tab. No need for any `window.addEventListener('beforeunload')` madness.

If you'll humor me, after looking at this code, I have a couple questions about how it works still. Maybe you can give me a quick answer as now I'm curious.

First question:

In Vent.js, each time a client subscribes to a channel, we [call](https://github.com/nathan-muir/redis-oplog/blob/4d083cc60f793738b859c449630497e21795667e/lib/vent/Vent.js#L96) `channelHandlers.push({ channel, handler })`.  Then when the client calls `stop()` it calls `context.onStop(...)`.  Inside of the `context.onStop(...)` callback we're iterating over **all** of `channelHandlers` with `channelHandlers.forEach(({ channel, handler }) => {...});`.  If `channelHandlers` is shared by all subscriptions, wouldn't this call `pubSubManager.unsubscribe(channel, handler)` on every single entry in `channelHandlers` thus unsubscribing that client from all of its Vent subscriptions - and then every other client's Vent subscriptions if it's iterating over all `channelHandlers`?  I know that it doesn't, but I'm confused on why it doesn't.

Second question:

I noticed that if, for example, four clients all subscribe to the same Vent publication with the same `objectId` (e.g. the same exact channel), when a `Vent.emit` triggers, the `this.on` in the `Vent.publish` calls four different times.  I guess it's doing this because there are four subscribed clients and it's firing this callback thus four times.  Is there a more efficient way to do this where the `this.on` callback doesn't fire multiple times for each client subscribed to the same channel?  Seems like a lot of extra overhead.  I barely understand any of this so forgive me, but I was just wondering if there was a deeper way to optimize delivering the data on the same channel.

**Comment by evolross** [comment]
@nathan-muir Thanks for the answers.  I think I get it on the first question: `channelHandlers` is in context and local to each call of `_extendPublishContext`.  That makes sense. I was confused because `channelHandlers` is an array. Does this need to be an array that we iterate through?  Wouldn't each channel only have one handler per client?  Can a client subscribe to a publication of the same channel more than once?  If so, why would they?  Why isn't it just `const channelHandler = callback/handler`.

Apologies for being tenacious.  Just trying to understand this code-base better since my production app is going to be relying on it.

**Comment by nathan-muir** [comment]
@evolross Suppose you wrote something like:

```js
Vent.publish({
    'followThreads'(thread1, thread2, thread3) {
        this.on(`threads::${thread1}::new_message`, ({message}) => {
            return {thread: thread1, message};
        });
        this.on(`threads::${thread2}::new_message`, ({message}) => {
            return {thread: thread2, message};
        });
        this.on(`threads::${thread3}::new_message`, ({message}) => {
            return {thread: thread3, message};
        });
    }    
})
```

(Yes, you would probably use a loop, but we're illustrating that `this.on` could be called multiple times in the one publish handler.

**Comment by evolross** [comment]
Ah... understood.  Thanks!
