### ISSUE TITLE
Expiration date for oplog data

### ISSUE THREAD

**Issue by ElegantSudo** [cult-of-coders/redis-oplog#27]
We don't want to clutter our database with lots of oplog data that remains in our history forever, thus costing us money for storage and slowing other queries down.

It's not a priority right now, but it would be great if we could add an expiration to oplog data (i.e. 24 hours, a week, or a month)

**Comment by theodorDiaconu** [comment]
I don't understand your concern. Please elaborate @ElegantSudo

**Comment by ElegantSudo** [comment]
@theodorDiaconu Found this! http://www.redis.io/commands/expire We should have an expiration timeout for our data in redis.

For example, after a month a key would be deleted because it's no longer needed for reactivity.

**Comment by theodorDiaconu** [comment]
@ElegantSudo we don't store data at all in Redis, we plan on doing something like that for #21 , but for now it's just using it's pub/sub system
