### ISSUE TITLE
Using Vent.subscribe on the server?

### ISSUE THREAD

**Issue by dnish** [cult-of-coders/redis-oplog#275]
Hey @theodorDiaconu,
I'm just wondering it it would be possible to use Vent.subscribe on the server? I want to create a communication channel between each Meteor instance where each instance subscribes to an event. If I try to use Vent.subscribe on the server it seems not available there (client only).

**Comment by theodorDiaconu** [comment]
@dnish basically "Server Vent" is actually listening to redis messages directly. Look at PubSubManager : https://github.com/cult-of-coders/redis-oplog/blob/master/lib/redis/PubSubManager.js

**Comment by dnish** [comment]
Perfect, thank you very much :)

**Comment by dnish** [comment]
Hey @theodorDiaconu,
just ran into an issue. I've creating event handlers like this:

for(var i = 0; i<15;i++) {
    const ps = new PubSubManager();
    ps.subscribe(`test${i}`,handler);
}

while i represents the id of the instance. This gives me the following warning:

      MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit

I'm just wondering about it, because I thought that due to the i within the event it will be handled as another event.

**Comment by theodorDiaconu** [comment]
Where exactly is the leak happening ? Try to manually increase that event emitter's maxLimit

**Comment by dnish** [comment]
Don't get a exactly line, only the warning:

```
(node:11966) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
```
Just read that it is not recommended to increase the limit. I've tried to use another event library,  this one works without warning:

```
var NRP    = require('node-redis-pubsub');
var config = {
    port  : 6379  , // Port of your locally running Redis server
    scope : 'demo'  // Use a scope to prevent two NRPs from sharing messages
};

var nrp = new NRP(config);


setTimeout(() => {
    nrp.emit('say hello', { name: 'Louis' });
},5000);


for(var i = 0;i<15;i++) {
    nrp.on('say hello', function(data){
        console.log('Hello ' + data.name);
    });
}
```
