### ISSUE TITLE
RedisOplog not initialized

### ISSUE THREAD

**Issue by LoriKarikari** [cult-of-coders/redis-oplog#28]
Hi,

I've followed the usage instructions but publishWithRedis throws an error saying "RedisOplog is not initialized".
I've created a redis.js file at /imports/startup/server/redis.js and also tried to add the code directly into the main.js file of the core server folder. I'm using Meteor 1.4.2.1.

**Comment by theodorDiaconu** [comment]
Did you put this code anywhere ? It needs to be initialized, until then it's dormant, it won't affect your app.

```
RedisOplog.init()
```

**Comment by LoriKarikari** [comment]
Yes I followed the instructions provided. 

``
import { RedisOplog } from 'meteor/cultofcoders:redis-oplog';

RedisOplog.init({
  redis: {
    port: 6379,
    host: '127.0.0.1',
  },
  debug: false,
  overridePublishFunction: false,
});

**Comment by ElegantSudo** [comment]
@LoriKarikari Make sure you're actually importing that file before you're dealing with any operations, functions, or methods exposed by the redis-oplog package. It needs to come first.

**Comment by LoriKarikari** [comment]
Yes also doing that I imported the file in /imports/startup/server/index.js.
This is a working app so the structures and imports are working.

**Comment by ElegantSudo** [comment]
@LoriKarikari could you provide us with an example?

**Comment by LoriKarikari** [comment]
/imports/startup/server/index.js content:

`import './redis';
import './fixtures';
import './cron-jobs';
import './api';`

the api import are my methods and publications. 

``
Meteor.publishWithRedis('most.active.channel', function () {
  return MostActiveChannels.find({},{sort: {messages: -1}, limit: 1});
});

That's it nothing more.

**Comment by theodorDiaconu** [comment]
@LoriKarikari I created a new project, added redis-oplog, did as you did, worked for me, tests wouldn't have passed if this wasn't working. Pls provide a reproduction repository for this.
