### ISSUE TITLE
What happens with redis-oplog if the external redis service is interrupted?

### ISSUE THREAD

**Issue by ixdi** [cult-of-coders/redis-oplog#282]
The external redis service (Compose) has notified us that there will be no service for one day.

Forgive ignorance, we know that there's a reconnection timout but do you know how the subscriptions will be affected? 
We are using redis-oplog in a deployed web app.

Thanks

**Comment by theodorDiaconu** [comment]
@ixdi reactivity disappears completely, when it reconnects again, reactivity is resumed.
