### ISSUE TITLE
Missing mutations event if Mongo collection changes while performing initial add

### ISSUE THREAD

**Issue by bolaum** [cult-of-coders/redis-oplog#284]
If updates to the mongo collection occur while adding initial values to the observer, those changes are missed. 

I found out, by reading the debug logs, that the channel subscription is being queued and only runs after the addition of initial values, leading to missed messages from redis.

I was able to fix it with the following changes:
```js
// RedisSubscriptionManager.js
...
    attach(redisSubscriber) {
        this.queue.queueTask(() => {
            _.each(redisSubscriber.channels, channel => {
                if (!this.store[channel]) {
                    this.initializeChannel(channel);
                }

                this.store[channel].push(redisSubscriber);
            });
        });
    }
...
```
to:
```js
// RedisSubscriptionManager.js
...
    attach(redisSubscriber) {
        _.each(redisSubscriber.channels, channel => {
            if (!this.store[channel]) {
                this.initializeChannel(channel);
            }

            this.store[channel].push(redisSubscriber);
        });
    }
...
```

This way, the observer is immediately subscribed to the channel and doesn't miss any updates.

All tests passed. Can I send a PR?

Thanks.

**Comment by theodorDiaconu** [comment]
It should be runTask in this case.
