### ISSUE TITLE
For some reason it keeps saying "Established connection to redis"

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#290]
```
0|worklog  | RedisOplog - Established connection to redis.

0|worklog  | `Meteor.addCollectionExtension` is deprecated, please use `CollectionExtensions.addExtension`

0|worklog  | {"line":"106","file":"percolate_migrations.js","message":"Migrations: Not migrating, already at version 5","time":{"$date":1528810782845},"level":"info"}
```

Have to figure out why, there are no issues with the problem, but it reconnects. Maybe a timeout ? Server-bound or client-config bound. Must investigate.

**Comment by theodorDiaconu** [comment]
Found the culprit it was related to improper config of redis.

If you have this issue. Look into /var/log/redis

My issue was low `ulimit`

root@ip-172-31-38-247:/var/log/redis# ulimit -n 65535
root@ip-172-31-38-247:/var/log/redis# set rlim_fd_max = 166384
root@ip-172-31-38-247:/var/log/redis# set rlim_fd_cur = 8192

**Comment by Floriferous** [comment]
We're using Redis on Cloudfoundry, where we don't have access to raw redis config, and are seeing this error.

We're using this plan:

<img width="191" alt="screen shot 2018-09-13 at 13 08 08" src="https://user-images.githubusercontent.com/10428082/45486527-bc11f300-b75b-11e8-8359-b21705e3a9a2.png">

Do you think the 128 connections is the same as `ulimit`? If so, why is it even exceeding that number? and not "recycling" them?

**Comment by theodorDiaconu** [comment]
@Floriferous do you have any option there regarding connection timeout ? I would try quickly setting up a redis-server near your cloud infrastructure, and see how it behaves. Redis at this scale is easy to maintain, especially since we do not store anything in it, it doesn't act as a database with mission-critical data stored in it. If redis-server fails, reactivity will fail, the rest of the app will function normally.

**Comment by Floriferous** [comment]
Not sure we do. There isn't much to configure.

We thought we could get really great performance, since the apps, mongoDB and finally redis could all be hosted in the same server farm.

**Comment by theodorDiaconu** [comment]
@Floriferous what stops you from keeping it in the same server farm as your servers ? Just spin-up an instance, install redis, configure auth, problem solved.

**Comment by Floriferous** [comment]
Because it's CloudFoundry, you can't just start a VPS. You have to either start an "app" or a "service", and connect them together internally. Redis and mongoDB are among their offered "services", and our meteor apps run on node-buildpack "apps".

It handles most of the devOps for you, and lets you easily scale up and down.

**Comment by theodorDiaconu** [comment]
I'm sorry not very familiar with CloudFoundry, but to me it's ridiculous that it does not allow you to configure the services you do have.

**Comment by Floriferous** [comment]
It's all about tradeoffs. For example, our mongoDB is insanely fast, you can almost type in a react input field connected via reactivity to the DB without noticing any lag!

There might be a way to configure it, it's just a bit obscure.

It's not clear from your initial post if this warning/error actually has any impact? Does it break reactivity?

**Comment by theodorDiaconu** [comment]
Doesn't break reactivity for long and it may cause some regular spikes like this:

1. Connection drops
2. Redis starts retrying connection
3. Connection resumed -> MongoDB bombarded with queries (from all your apps/microservices at once) so all observables get up to speed
4. Reactivity resumes.

It must be a way to config it, maybe the similar to the way you configed auth ?

**Comment by Floriferous** [comment]
Okay, so if we're able to configure it properly, what should we set the timeout to?

Authentication is all handled by CloudFoundry, they make sure the redis has an open port and URL, but that it can only be accessed by internal "apps".
