### ISSUE TITLE
Compatibility with Apollo Package?

### ISSUE THREAD

**Issue by IllusionElements** [cult-of-coders/redis-oplog#293]
Is this package compatible to use with your apolloGraphQL package, if it does does it require any sort of customer. Integration to make it work with with the package?

**Comment by theodorDiaconu** [comment]
@IllusionElements this works with apollo-live-client and apollo-live-server npm packages, you can find more in the docs of https://github.com/cult-of-coders/apollo

Yes, we have scalable reactivity in Apollo with Meteor! Which is super
