### ISSUE TITLE
Running 2 subscriptions on the same collection looses data

### ISSUE THREAD

**Issue by Pagebakers** [cult-of-coders/redis-oplog#300]
I'm running into issues where redis-oplog fails to publish items when you have multiple subscriptions active on the same collection.

I have two collections:

Conversations
  lastItemId -> ConversationItems._id
ConversationItems
  conversationId -> Conversations._id

The lastMessageId is used to display the last message in the conversations list and is updated every time a new item is added to the conversation.

Then there are 2 publications using Meteor.publishComposite

```js
Meteor.publishComposite('conversations', function () {
  return {
    find() {
      return Conversations.find()
    },
    children: [{
      find(conversation) {
        return ConversationItems.find({
          _id: conversation.lastItemId
        })
      }
    }]
  }
})

Meteor.publishComposite('conversation', function(_id) {
  return {
    find() {
      return Conversations.find({
        _id
      })
    },
    children: [{
      find(conversation) {
        return ConversationItems.find({
          conversationId: conversation._id
        })
      }
    }]
  }
})
```

Both publications are subscribed to on the same page, initially it seems to work fine. But after adding a few items and updating lastMessageId the 'conversation' publication stops publishing conversation items and only the lastItemId conversation item is published.

Hope this makes sense :)

Is this a known issue? Let me know if you need more info.

**Comment by ramezrafla** [comment]
Why don't you try ditching publishComposite in favor of manual reactivity? We did that and our app works better and is easier to debug. Your pub looks easy enough to convert.

Check out this post https://forums.meteor.com/t/meteor-scaling-redis-oplog-status-prod-ready/30855/575 and this thread for examples: https://forums.meteor.com/t/reactive-joins-without-using-any-packages/46525

**Comment by Pagebakers** [comment]
Thanks @ramezrafla 

This is a simplified example of our setup. Right now we're just trying to make things work without changing too much of the original code.

The issue seemed to be related to collection2 not passing down options to the insert call on ConversationItems, there are a couple other issues around this.

Running on #283 now and it looks to be running smooth! Closing this for now :)
