### ISSUE TITLE
Which version of Redis should I use?

### ISSUE THREAD

**Issue by SimonSimCity** [cult-of-coders/redis-oplog#303]
I'm quite new to Redis and have the following question:

Which version of Redis would you recommend using or is there a minimum version of Redis this library is compatible to?

On my Mac brew installs Redis in version `5.0.3`, Azure is using `3.2.7` and for Windows (where my app also has to be running on) the latest release is `3.0.503` if I don't take the hassle of adding vagrant or docker to my stack. Are there any known changes between these versions which would affect the usage of this library?

**Comment by theodorDiaconu** [comment]
I don't think it matters as we only use the pubsub from redis.

**Comment by SimonSimCity** [comment]
Sounds good, solves the question for me here.
