### ISSUE TITLE
Question: How do people handle redis master failovers?

### ISSUE THREAD

**Issue by znewsham** [cult-of-coders/redis-oplog#307]
I'm probably missing something obvious here, but how does redis-oplog switch to the new master in the event of a failover? I'm familiar with redis and sentinel and understand how a slave is promoted to a master, but can't figure out how to get redis-oplog to reconnect to the new master in the case of failover.

Do people stick some type of proxy in front of their replication group, or is there an option I've missed like the mongo URL which takes comma separated hosts? Or do you implement it by hand in the error/end event of redis oplig?

**Comment by ramezrafla** [comment]
I can only speak of how we do this. We are using AWS Elasticache. So the uptime is very high. If it goes down, they bring it up almost instantaneously. So that part of the worry is handled for us, and we can focus on MongoDB (3 replicated instances in 3 different zones) and the App (using EBS)

**Comment by ramezrafla** [comment]
Can we close this? To keep things clean and focus on issues.

**Comment by znewsham** [comment]
Ah yes, I'll close it, though for posterity I will just finish by saying that redis-oplog does NOT handle failovers (in case anyone comes looking for an answer)

**Comment by evolross** [comment]
@znewsham I was just looking for this answer about failover... So you can't pass multiple servers to a redis URL for failover (compose.io calls them TCP portals).  I was hoping it would be similar to how you do with mongo like this:
```
url: redis://user:password@aws-us-east-1-portal.01.dblayer.com:26335,aws-us-east-1-portal.02.dblayer.com:26335
```
As compose.io provides multiple TCP portals for the exact reason of failover. You're saying in this thread you have to manage failover more manually?
