### ISSUE TITLE
RedisOplog.stats is not a function

### ISSUE THREAD

**Issue by chrishanyu** [cult-of-coders/redis-oplog#318]
Hello,

Just started to implement redis-oplog and saw this in the readme:

If you are interested in viewing how many observers are registered or memory consumption:

```
meteor shell
import { RedisOplog } from 'meteor/cultofcoders:redis-oplog';

// works only server-side
RedisOplog.stats()
```

However in the 2.0.0 release it seems like `stats` function is no longer exported.

Is there a way for us to observe what redis-oplog is doing on the server?

Thanks.

**Comment by theodorDiaconu** [comment]
@chrishanyu it should be hooked into the observers of Meteor. Meaning Kadira aka Meteor APM can follow it.

**Comment by thearabbit** [comment]
@theodorDiaconu, could you explain?
I have the same problem `RedisOplog.stats` for status testing
```js
// Server startup
import { Meteor } from "meteor/meteor"
import { RedisOplog } from "meteor/cultofcoders:redis-oplog";

Meteor.startup(() => {
 RedisOplog.stats()
});

**Comment by diavrank** [comment]
I got the same problem in Meteor 1.11.1 :( . 

Anyone know how to do it workaround? 

Also, I can't logged in with [simple-ddp](https://github.com/Gregivy/simpleddp) client

**Comment by theodorDiaconu** [comment]
Since RedisOplog v2, the stats are now the official stats from Meteor, no need for a separate .stats() function that's why it is gone. It should be removed from the documentation. Use Kadira APM to follow the observers and the stats of redis oplog.

**Comment by jasongrishkoff** [comment]
Might be good to remove this from the README?
