### ISSUE TITLE
Adopting redis-oplog incrementally

### ISSUE THREAD

**Issue by brg8** [cult-of-coders/redis-oplog#319]
I have multiple production meteor servers and would like to try redis-oplog on one of them in order to test compatibility with several forks we've made of meteor packages.

Since my other meteor servers use the default meteor oplog reactivity, they should not feel any negative effects from the single server that is using redis-oplog. However, the one server that is using redis-oplog will not receive notifications from the other servers, since they are not sending their mutations to redis.

What I would like to do is install redis-oplog on _every_ meteor server, but have a flag where I can tell all of them to send their mutations to redis, but still use the old meteor pub/sub. This would create two reactivity options in parallel, one in mongo and one in redis. Then I will tell one meteor server to use redis-oplog pub/sub. This way, all my servers can maintain full reactive functionality while I incrementally move each server over to redis reactivity.

This feels like something you guys would have thought about previously, so please let me know if I've missed a previous issue or if I glossed over something in the documentation.

**Comment by ramezrafla** [comment]
Try to use it without installing `disable-oplog`

*Ramez Rafla*
*@ClassroomAPP.com*
(m) 514.978.8198 <(514)%20978-8198>
(e) ramez@classroomapp.com
(w) www.classroomapp.com
(in) ca.linked.com/in/ramezrafla <http://ca.linkedin.com/in/ramezrafla>

**Comment by brg8** [comment]
I think you are suggesting that I install redis-oplog on the other meteor servers without also installing disable-oplog. That would indeed allow me to have my regular meteor servers still tail the mongo op log. However, redis-oplog would still patch the publish/subscribe methods to pull from redis rather than mongo.

Am I misunderstanding how redis-oplog changes the default pub/sub functionality?

**Comment by ramezrafla** [comment]
If you don't add disable-oplog, it will still use oplog regardless on top of redis
I haven't tested this scenario in great detail, I am merely suggesting a starting point.

If, however, you include in the options to not push to redis by default you should have identical functionality to regular oplog. Then you slowly test and update your servers until you are 100% on redis-oplog

**Comment by brg8** [comment]
Interesting. If I understand that correctly, a publication will receive mutations from both the mongo op log and redis channels. So and `insert` will be received into the publication twice and sent to every subscription. On the client there will be a duplicate `_id` error (which is fine, that should not harm the application).

Does that match your understanding? If the above is theoretically correct then I'll give it a shot.

**Comment by theodorDiaconu** [comment]
I believe this question has been answered.

**Comment by afrokick** [comment]
It doesn't work for me. I remove disable-oplog, set pushToRedis to false, but pub/sub doesn't produce any notifications to client from server.
