### ISSUE TITLE
Support for RedisOplogObserver on cursors using skip

### ISSUE THREAD

**Issue by SimonSimCity** [cult-of-coders/redis-oplog#330]
I need support for the RedisOplogObserver on a query using `skip`. This currently is disabled using https://github.com/cult-of-coders/redis-oplog/blob/9487742b1aa1ce8942c202ebf5da454607de2983/lib/mongo/RedisOplogObserveDriver.js#L91.

Do you know if there's a technique which could make it usable? I need it mostly for updates which are unrelated to the sorting. If a property of an instance would change, which is used in the sorting, I'd be fine if it would do a full-refetch, as the `PollingObserveDriver` is performing every once in a while.

Do you have any details about how Meteor does it internally?

I'd also like to know how it would affect the performance and the data if I would just disable the line 91 linked above. I've tried it and it updates the elements visible at the source, but I haven't tried adding or removing items which are before or after.

If it at any change would re-query the full stack, I wouldn't be bothered much, because this single collection I need this functionality for is one where I do not expect many documents - but just too many for publishing them all to the client - as a personal opinion.

Could you give me some ideas how to proceed from here @theodorDiaconu ?

**Comment by theodorDiaconu** [comment]
@SimonSimCity That's strange there should already be support for that! We have our processors which, for limit-sort strategy work just fine, they requery all _ids, and refetch only the diffed documents! 

https://github.com/cult-of-coders/redis-oplog/blob/9487742b1aa1ce8942c202ebf5da454607de2983/lib/processors/limit-sort.js#L42

I believe if you remove that, it should work, give it a try.

**Comment by SimonSimCity** [comment]
I tried it and I have to say that it works quite well for updating the individual objects published as long as they remain in the specified range. So the only thing I'd like seeing is some kind of mechanism that reruns the query if an object on screen get's out of range (e.g. by getting beyond or above the sorting property of the last or first item) and likewise if any item receives an update on the sort-property.

Maybe also some kind of balance there that it doesn't update on each and every if 10 documents within a second would trigger such an event, but some kind of combination with the logic of the `PollingObserveDriver`.

Just to say: This already works for the first page because it uses `{ skip: 0 }` which is basically ignored :wink:

**Comment by theodorDiaconu** [comment]
What u are describing is already treated in the limit-sort processor take a look

Regards,
Theodor

**Comment by SimonSimCity** [comment]
As said, it works, but when I'm e.g. on page 2 of 3 and an element is removed, the query is not re-run and I end up having one element less on my grid, which looks a bit ugly on a grid ...

Not that it would happen often in my case, but I want to have this done right if we open it up for everyone.

**Comment by SimonSimCity** [comment]
Was not too hard to track it down. The system correctly reran the query but the problem came when actually adding the new document. For this it used the collections method `addById` which has the following line:

https://github.com/cult-of-coders/redis-oplog/blob/93751c40706411c7b0519ba0964c0e40fa5c4773/lib/cache/ObservableCollection.js#L212

And the `this.options` object looked like following for my page 2:
```json
{ "limit": 88,
  "skip": 88,
  "sort": { "code": 1 }
}
```

But having a `skip` of `88` here would imply that you have multiple, and a `limit` of `88` is also not necessary because we anyways use a `findOne`-call.

I've now changed the line as following and proved it working:

```js
const doc = this.collection.findOne({ _id: docId }, { ...this.options, limit: 0, skip: 0 });
```

Any ideas or stuff I should include in a further investigation? Things that might fail on another end which I should take an eye on? Otherwise I'd just open a PR containing these changes in order for you to merge 😊

**Comment by theodorDiaconu** [comment]
Wow, yes you are right. For limit/skip I think they rely on Polling?

**Comment by SimonSimCity** [comment]
Maybe we should launch an improvement for the Meteor core? 😃

But what was your primary decision not to reuse the methods Meteor uses? Is it because they were private and you therefore could not rely on their existence?

**Comment by SimonSimCity** [comment]
I've looked it up and debugged it - they're just using polling in this case. What I still don't fully comprehend is why they still deliver updates as fast as this option on redis-oplog ...

**Comment by theodorDiaconu** [comment]
Maybe they do polling very frequently?

**Comment by SimonSimCity** [comment]
According to what I could see while debugging, no ... but I couldn't quickly find out how they keep the UI updated.
