### ISSUE TITLE
Cannot connect via SSL

### ISSUE THREAD

**Issue by bohan0** [cult-of-coders/redis-oplog#333]
I tried to connect via SSL using both the port/host/password and url options but could not get it to work.

The type of URL I am using is like this:

redis://:password@rdb-hostname.nodechef.com:2403/0

If I use the 2402 port (which is non-SSL for this nodechef instance) then it works.

**Comment by nathan-muir** [comment]
@bohan0 Can you try making the protocol `rediss://` [1]

[1] https://github.com/NodeRedis/node_redis/blob/master/lib/createClient.js#L35

**Comment by bohan0** [comment]
@nathan-muir didn't - it does not seem to understand rediss :

W20190508-14:45:07.950(10)? (STDERR) node_redis: WARNING: You passed "rediss" as protocol instead of the "redis" protocol!
W20190508-14:45:12.610(10)? (STDERR) RedisOplog - Connection to redis ended
W20190508-14:45:15.776(10)? (STDERR) RedisOplog - There was an error when re-connecting to redis {"delay":3000,"attempt":1,"error":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"139.99.144.38","port":2403},"total_retry_time":0,"times_connected":0}

**Comment by nathan-muir** [comment]
How about adding the `tls` setting to your `redis` block, something like:

`meteor-settings.json` - 
```json
{
  ...
  "redisOplog": {
    "redis": {
       "url": "",
       "tls": {}
    },
}
```

**Comment by bohan0** [comment]
no that did not work either

**Comment by SimonSimCity** [comment]
I can successfully connect via SSL using the following configuration:

```
{
  "redisOplog": {
    "redis": {
      "port": 6380,
      "host": "theHostname",
      "password": "MyPassword",
      "tls": {
        "servername": "theHostname"
      }
    }
  }
}
```

**Comment by bohan0** [comment]
@SimonSimCity that still did not work for me with Nodechef - do you think its because of the way they are implementing SSL over Redis (I read somewhere that Redis does not have SSL builtin and you have to set up tunnels/proxies?).

**Comment by SimonSimCity** [comment]
I don't know about that or a way of how to set up tunneling. I tested the setup with the SSL version of Redis on Azure. Thought it would also work for you this way ...

I'd now start off with trying to connect manually to the Redis cluster - just by using the command line or a small node-script. I haven't worked with Nodechef before, so I don't have any insight on this issue.

**Comment by theodorDiaconu** [comment]
This is either an issue with redis package or with your infrastructure. Closing this ticket.
