### ISSUE TITLE
RedisOplog - Connection to redis ended

### ISSUE THREAD

**Issue by tpmh31292** [cult-of-coders/redis-oplog#334]
Hi, I Just recently added redisoplog to my meteor app following the instruction in README.
I use the default settings.

However, when I run "meteor" to start the app, the log keeps printing this
```
W20190802-10:33:53.676(10)? (STDERR) RedisOplog - Connection to redis ended
W20190802-10:33:58.680(10)? (STDERR) RedisOplog - There was an error when re-connecting to redis {"delay":10000,"attempt":1,"error":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},"total_ retry_time":0,"times_connected":0}
```

App still works fine and when I navigate around, the log prints
```
I20190802-10:39:17.185(10)? [1564706357186] - [RedisSubscriptionManager] Subscribing to channel: notes
I20190802-10:39:17.225(10)? [1564706357226] - [RedisSubscriptionManager] Subscribing to channel: appointments::jzTi2wBHRSZ5aGs8Z
I20190802-10:39:17.234(10)? [1564706357235] - [RedisSubscriptionManager] Subscribing to channel: services::kkjXFrh42BrRX2CEE
I20190802-10:39:17.243(10)? [1564706357243] - [RedisSubscriptionManager] Subscribing to channel: services::ZQSj6SBB65i6rg9Sv
```

So I think the redis-oplog works. However, the log keeps printing the error still.
Is that something we need to worry about?

**Comment by evolross** [comment]
I would say you're not connecting to the Redis server properly. The app would still probably work for _you_ but reactive updates may not be happening for other users. And `redis-oplog` (which looks like you're running in debug mode) is still probably _trying_ to send the messages and thus reporting it.

Open another browser/login and test for reactivity that `redis-oplog` should be doing.

**Comment by tpmh31292** [comment]
Yes I'm running in debug mode.
Here is my init, I have also tried to init in settings.json file like stated in the README. Both give the same result.
```
RedisOplog.init({
    redis: {
      port: 6379, // Redis port
      host: '127.0.0.1', // Redis host
    },
    overridePublishFunction: true,
    debug: true
  });
```
I was just deployed to a remote server, opened 2 browsers and reactive updates happen as expected.

Do I need to `npm install redis` in my project?

**Comment by tpmh31292** [comment]
@evolross so I have set up the Redis server, and it's running on the server (same instance where I deploy my app using meteor-up). However, the issue still presents. Could it be because meteor-up is not compatible with redis-oplog?

**Comment by evolross** [comment]
You have `disable-oplog` added to your project. If not, your oplog could still be running. Test reactivity between a desktop browser and a phone-based browser. Do totally different devices just to make sure you're not just seeing optimistic UI.

Test that an update on one browser reactively updates the data/UI on a different device's browser. Then you can know if Redis is truly running.
