### ISSUE TITLE
Any dependencies that are not available in Meteor 1.2.1?

### ISSUE THREAD

**Issue by gaurav-** [cult-of-coders/redis-oplog#35]
Hi @theodorDiaconu,

Great idea that I'm keen to try out! But unfortunately we are stuck with Meteor 1.2.1 for various reasons, and this package [seems to support only the latest version](https://github.com/cult-of-coders/redis-oplog/blob/master/package.js#L20)? 

Is there any specific dependency that's available only with Meteor 1.4.x? If there's a possibility to support earlier versions, then I have strong reasons to contribute for that. Please let me know.

**Comment by ElegantSudo** [comment]
NPM integration is a key reason why this package works so well. I think that's why it's a `v1.4.x` thing. It'd generally be a hassle and more bloat if it were backwards compatible.

That'd also end up taking away from performance optimizations and the key purpose of this package.

If you're willing to develop it, by all means do it. I think @theodorDiaconu has got his hands full with more pressing issues right now though.

**Comment by theodorDiaconu** [comment]
@ElegantSudo true, we use npm integration, but that is supported since 1.3.x, so we can lower the required version a bit.

@gaurav- please tell me what stops you from updating ? I updated 1.2 apps to 1.4.2 without any change.

**Comment by gaurav-** [comment]
> please tell me what stops you from updating ?

We started with Meteor + React, when Meteor 1.2 just released. Since it didn't have support for NPM nor ES2015 modules, we started using it with Webpack – we first build our code with Webpack,and the resultant bundle is passed to the Meteor build.

This has served us well. But when we tried upgrading to Meteor 1.3, we realized that there are many subtle differences in the ES2015 module loader implementations of Webpack+Babel and Meteor 1.3. 

To cut a long story short , it would need us to make a lot of code changes for the migration, for which we don't have the bandwidth yet.

I checked the codebase and realized the primary blocker would be the use of ES2015 imports/exports by the library. It may not make sense to remove them, just to support previous versions. 

However, if the bulk of the package can be moved to npm, then it will solve the problem at least for us, because we can use NPM packages in our project, they're loaded through Webpack. Meteor 1.3+ users should be able to use it too.

Though I still need to check if there are any Meteor dependencies that may not be available in 1.2.1. E.g., is the lib using any Mongo driver APIs not available in 1.2.1, or any of the Meteor APIs introduced in 1.3+? 

@theodorDiaconu, it would be great if you can help me identify if there are any implicit dependencies like that. Depending on the findings, it might help my case to move the package to NPM, for which I'm willing to contribute too.

**Comment by theodorDiaconu** [comment]
@gaurav- nice, you had a good feel for the future way back. However right now we depend on "dburles:mongo-collection-instances@0.3.5" but this dependency can be removed I guess. Then we need "EJSON" and "Mongo" meteor's packages. Is there a way to write npm packages that can use some pseudo-globals for Meteor ? How would we run tests for that package ?

But why do you think it would require you a lot of bandwidth to switch, can you give me some details ?

**Comment by theodorDiaconu** [comment]
@gaurav-  I'm closing this. Feel free to open it when you have a solution for this. I'm interested for this to be as BC as possible.

**Comment by maxnowack** [comment]
the `tracker-component` npm package is using pseudo globals like this: https://github.com/studiointeract/tracker-component/blob/master/lib/index.jsx#L2-L4

**Comment by gaurav-** [comment]
Sorry for the late response, been stuck with some production issues to miss all the fun here :|

Looks like #52 is the right way to go. I hope it can stay compatible with Meteor 1.2. If not, then that might be the time to reopen this. But I'm quite hopeful, especially since the meteor packages @theodorDiaconu mentioned are already compatible. Thanks.
