### ISSUE TITLE
How to use Vent only

### ISSUE THREAD

**Issue by afrokick** [cult-of-coders/redis-oplog#359]
I want to use only Vent without changes in observeChanges and mongoCollection.

Is it possible without creating a fork?

**Comment by theodorDiaconu** [comment]
Yes. Just make sure you disable oplog by default. Take a look at the docs.

**Comment by afrokick** [comment]
@theodorDiaconu thank you. But could you please give a me a file where it uses? I can't find via GitHub search `overridePublishFunction` in js files (only in config and test).

**Comment by afrokick** [comment]
I found that it was removed in https://github.com/cult-of-coders/redis-oplog/commit/8d6dd336b3e8b65f9e946ec01643368bc074042b#diff-3e18cf2294c02344381d224486ff0d2dL31-L34

**Comment by afrokick** [comment]
Similar to https://github.com/cult-of-coders/redis-oplog/issues/245

**Comment by afrokick** [comment]
https://github.com/cult-of-coders/redis-oplog/issues/323
