### ISSUE TITLE
what exactly happens if you set `pushToRedis: false` on an update?

### ISSUE THREAD

**Issue by macrozone** [cult-of-coders/redis-oplog#364]
We face scaling issues with meteor and had some improvements with redis-oplog, but we have still problems.

i tried to disable reactivity when immediate updates are not needed, so i set `pushToRedis:false` to some updates, but i noticed that clients will then receive old (cached?) data, even after refresh of the browser

So i am a bit confused on whats actually happening if you set this to false ?

**Comment by macrozone** [comment]
@theodorDiaconu why do then clients get wrong data even after refreshing? I need to restart redis to get the right data, which seems  odd as i would think that redis would not cache any data.

**Comment by theodorDiaconu** [comment]
There are few possibilities for that happening:
1) Connection to redis stops?
2) A bug in redis-oplog?

Either way, can you reproduce this?
