### ISSUE TITLE
Initialize RedisOplog automatically if settings for it are configured.

### ISSUE THREAD

**Issue by simonbelanger** [cult-of-coders/redis-oplog#37]
Not exactly an issue, but any call to Meteor.publishWithRedis() before the call to RedisOplog.init() will make the application crash.

Kinda obvious when you know it but might worth mentioning it the doc.

Or even add the possibility to put the init parameters directly in the app settings file and initialize everything automatically.

Awesome package BTW, real game changer IMO.

**Comment by theodorDiaconu** [comment]
@simonbelanger good idea with settings! will do

**Comment by theodorDiaconu** [comment]
After some thinking about this, we won't do it, because RedisOplog must be the last wrapper around the code, and if you add other packages after redis-oplog, it may lead to even weirder bugs.
