### ISSUE TITLE
Check failed: IsFeedbackVector()

### ISSUE THREAD

**Issue by milanzigmond** [cult-of-coders/redis-oplog#370]
Hi guys, I'm getting this in my error log on galaxy, any idea where the problem can be? 
<img width="1154" alt="Screen Shot 2021-02-01 at 9 36 23 PM" src="https://user-images.githubusercontent.com/4190850/106515409-f075dd80-64d5-11eb-8e19-cd7a66fff3c0.png">

**Comment by theodorDiaconu** [comment]
This doesn't seem related to this package.
