### ISSUE TITLE
Specifying SSL/TLS certificates for MongoDB Encrypted connections

### ISSUE THREAD

**Issue by vlasky** [cult-of-coders/redis-oplog#376]
Hello,

I have requireTLS enabled in /etc/mongodb.cnf. Does redis-oplog have a way to specify the SSL/TLS certificate files needed to connect to my MongoDB instance?

**Comment by ramezrafla** [comment]
@vlasky 
redis-oplog (last I checked) does not connect to the DB directly. It overloads pubs and mongo methods only.
