### ISSUE TITLE
SyntheticMutator does not apply globalRedisPrefix setting

### ISSUE THREAD

**Issue by mfen** [cult-of-coders/redis-oplog#379]
We are using `SyntheticMutator` to trigger reactivity for some bulk mutations using `rawCollection` that bypass that normal hooks. e.g.
```js
bulkItems.forEach((item) => SyntheticMutator.insert(Items, item));
```

 We recently set a `globalRedisPrefix` in our `settings.json`:
```json
  "redisOplog": {
    "globalRedisPrefix": "<namespace>::",
    "redis": {
        ...
    }
  }
```
which broke reactivity on these operations as `SyntheticMutator` constructs channel names itself without applying the global prefix, i.e. it published to `items` & `items::<_id>` channels rather than the expected `<namespace>::items` and `<namespace>::items::<_id>`.

I suggest that the `getChannels` & `getDedicatedChannel` helpers are used in `SyntheticMutator` to consistently apply the prefix.

**Comment by StorytellerCZ** [comment]
Fixed in v2.2
