### ISSUE TITLE
Client-side updates are not pushed to Redis.

### ISSUE THREAD

**Issue by simonbelanger** [cult-of-coders/redis-oplog#38]
Calls to insert, update and remove methods on client-side collections doesn't seem to be published reactively...

As good practise, we've been wrapping the calls to client-side collection methods in Meteor methods for some time now. I guess (still not tested it) in those cases everything would work fine because the collection method would eventually be called during the server-side execution of the Meteor method (I wish they would have found another name for that, so confusing).

But we have a very big and old codebase and we still have a lot of calls to client-side collection methods directly in inappropriate places like template event handlers (sorry I feel sick just saying that, I hope your ears are not bleeding) and refactoring the whole thing is not necessarily realistic at this point...

@theodorDiaconu Any thoughts on that?

**Comment by theodorDiaconu** [comment]
@simonbelanger I'll have to see why it behaves differently I always thought doing a Collection.insert() is actually a method call and server-side it does the actual insert. Will dig deeper. I want it to be as BC as possible

**Comment by theodorDiaconu** [comment]
@maxnowack this is a very strange behavior, are you talking about methods that are defined on server-side and clients as well ? Can you give me an example of the update ? Did you properly initialized RedisOplog, can you initialize it with debug: true and show me some logs ? Cheers.

**Comment by theodorDiaconu** [comment]
@simonbelanger @maxnowack follow-up, what packages do you have ? Can you try putting redis-oplog as the last package, and initialize it first before anything else on the server ?

**Comment by theodorDiaconu** [comment]
Pls make sure that if you use *publish* you must have `RedisOplog.init({overridePublishFunction: true})`. Otherwise use publishWithRedis

**Comment by maxnowack** [comment]
The first thing I've noticed is that it seems that there if an incompatibility with the `meteorhacks:unblock` package. I was getting a `Maximum call stack size exceeded` error. After removing the package, it was gone.
I'm still testing. I'll post more information here.

**Comment by maxnowack** [comment]
I get some RangeErrors with the latest version:
````
I20161118-18:39:29.847(1)? [PublicationEntry] Performing initial add for observer
I20161118-18:39:29.847(1)? [RedisSubscriptionManager] Sending event: u to users::JFZCwR6Jqg8Kw7HXu ...
I20161118-18:39:29.848(1)? [RedisSubscriptionManager] Subscribing to channel: tags
I20161118-18:39:29.850(1)? [RedisSubscriptionManager] Subscribing to channel: services
I20161118-18:39:30.017(1)? Exception from task: RangeError: Maximum call stack size exceeded
I20161118-18:39:30.018(1)?     at Object.EJSON.clone (packages/ejson.js:482:24)
I20161118-18:39:30.019(1)?     at packages/ejson.js:521:22
I20161118-18:39:30.021(1)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20161118-18:39:30.022(1)?     at Object.EJSON.clone (packages/ejson.js:520:5)
I20161118-18:39:30.022(1)?     at packages/ejson.js:521:22
I20161118-18:39:30.026(1)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20161118-18:39:30.027(1)?     at Object.EJSON.clone (packages/ejson.js:520:5)
I20161118-18:39:30.027(1)?     at packages/ejson.js:521:22
I20161118-18:39:30.030(1)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20161118-18:39:30.030(1)?     at Object.EJSON.clone (packages/ejson.js:520:5)
````

````
I20161118-18:39:30.042(1)? [RedisSubscriptionManager] Subscribing to channel: lists
I20161118-18:39:30.093(1)? [RedisSubscriptionManager] Sending event: u to users::JFZCwR6Jqg8Kw7HXu ...
I20161118-18:39:30.349(1)? Exception from sub team id DahFyHxy34tmsxZSQ RangeError: Maximum call stack size exceeded
I20161118-18:39:30.352(1)?     at Object.Future.wait (/Users/maxnowack/.meteor/packages/meteor-tool/.1.4.2_3.5bfqo6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20161118-18:39:30.352(1)?     at [object Object]._.extend.runTask (packages/meteor.js:741:9)
I20161118-18:39:30.353(1)?     at Subscription._handler (packages/cultofcoders:redis-oplog/lib/publishWithRedis.js:51:34)
I20161118-18:39:30.355(1)?     at packages/check.js:130:16
I20161118-18:39:30.356(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20161118-18:39:30.356(1)?     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
I20161118-18:39:30.359(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1709:18)
I20161118-18:39:30.359(1)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1027:17)
I20161118-18:39:30.360(1)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20161118-18:39:30.361(1)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20161118-18:39:30.362(1)?     - - - - -
I20161118-18:39:30.362(1)?     at Object.EJSON.clone (packages/ejson.js:482:24)
I20161118-18:39:30.365(1)?     at packages/ejson.js:521:22
I20161118-18:39:30.366(1)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20161118-18:39:30.366(1)?     at Object.EJSON.clone (packages/ejson.js:520:5)
I20161118-18:39:30.369(1)?     at packages/ejson.js:521:22
I20161118-18:39:30.371(1)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20161118-18:39:30.373(1)?     at Object.EJSON.clone (packages/ejson.js:520:5)
I20161118-18:39:30.374(1)?     at packages/ejson.js:521:22
I20161118-18:39:30.374(1)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20161118-18:39:30.377(1)?     at Object.EJSON.clone (packages/ejson.js:520:5)
````

**Comment by theodorDiaconu** [comment]
@maxnowack make sure your version is 1.0.7 we had this infinite recursion bug and it was fixed since 1.0.5 thanks !

**Comment by maxnowack** [comment]
Yes, I have v1.0.7. I don't make an update. The error occurs on subscribing.

**Comment by theodorDiaconu** [comment]
Somehow an update is made to the user and ejson goes into an infinite loop weird.

**Comment by maxnowack** [comment]
I do an method call right after subscribing:
![image](https://cloud.githubusercontent.com/assets/186073/20442679/e1d5368a-adc9-11e6-8c79-b9a86908fc19.png)
the method updates a value in a document, that will be published from the publication. The publication returns multiple cursors.
Do you need more information?

**Comment by theodorDiaconu** [comment]
I need the exact update you do on the user, the contents of that update for some reason trigger the infinite loop

**Comment by maxnowack** [comment]
The method looks like this:
````es6
Meteor.methods({
  'teamgrid/users/updateLastTeamId'(teamId) {
    this.unblock()
    check(teamId, String)
    Meteor.users.update({ _id: this.userId }, { $set: { lastTeamId: teamId } })
  }
})
````
can it be the `this.unblock()` call?

**Comment by theodorDiaconu** [comment]
How does services publication look like?

**Comment by theodorDiaconu** [comment]
It seems that the infinite loop is due to some filters and/or options of some publication, we ejson parse it to identify the unicity of a query.

**Comment by maxnowack** [comment]
I don't have a publication named "services". I assume that you're talking about the "team" publication. "Services" is one of my collections.
The "team" publication returns 7 cursors with filters mainly based on the `teamId` and `this.userId`.  It also checks the users permissions and build the `fields` option of some cursors dynamically.
Additionally I create a "team user session" to track the online status of a particular user inside of a team. I use the `this.onStop` callback to remove this session.

**Comment by maxnowack** [comment]
And what I have forgotten so far: Your support and what you do for the meteor community is awesome! You've done a great job with grapher and you've done it again with this package. That's incredible! Thank you!

**Comment by theodorDiaconu** [comment]
@maxnowack thanks , appreciate it.

Now regarding this bug, the info I know it happens when you subscribe.

> It also checks the users permissions and build the fields option of some cursors dynamically.

Is anything within the cursors' filters or options self-referncing some how, resulting into an infinite loop when we json encode ? 

https://github.com/cult-of-coders/redis-oplog/blob/master/lib/cache/PublicationFactory.js#L60
^ This is how we extract the unicity of a response within a publication. I believe that's where the infinite loop happens. For some super-very weird reason.

**Comment by maxnowack** [comment]
hmm, I commented out everything from the publication and added the code again step by step to see when the error occurs.
I'm not able to return multiple cursors. In my first failing test I was trying to return 2 cursors:
````es6
const options = { fields: { services: 0 } }

const cursors = []
cursors.push(Teams.find({
  _id: teamId,
  'users.userId': this.userId,
  migrating: { $exists: false },
}, options))

cursors.push(Tags.find({
  archived: { $ne: true },
  teamId,
}))

return cursors
````

**Comment by maxnowack** [comment]
Update: It doesn't have anything todo with multiple cursors. The error even occurs if I only return the `Tags` cursor.
I've defined a transform function on `Tags`. It seems that there is some problem with `EJSON.stringify` and the `transform` inside of the cursor options. It works If I explicitly set `transform` to null in the cursor options.

**Comment by theodorDiaconu** [comment]
@maxnowack wow I was just planning to look into it but I think you found it! 

So it seems there's something wrong with transform... very curious why I did not have such an issue. If you clone the package, and put here: 

https://github.com/cult-of-coders/redis-oplog/blob/master/lib/cache/PublicationFactory.js#L65

options.transform = null.

Does it still happen ? Why would you have a transform function in the first place. Superweird.

**Comment by simonbelanger** [comment]
Hey guys, sorry I was out for the weekend.

FYI, I'm not sure my issue is related to @maxnowack 's, since the collection method calls are working perfectly on server, plus I don't see any error stack (client nor server).

I tried to wrap a call to a collection method in a Meteor method stub (executed both client and server-side) and as I expected everything's working fine this way, the data is published reactively.

See below a complete list of the app packages.

Let me know if I can help in any way.

```accounts-base                       1.2.14  A user account system
accounts-google                     1.0.11  Login service for Google accounts
accounts-password                   1.3.2* Password support for accounts
aldeed:simple-schema                1.5.3  A simple schema validation object with reactivity. U...
blaze-html-templates                1.0.5  Compile HTML templates into reactive UI with Meteor ...
bozhao:link-accounts                1.2.9  Meteor external service link system
browser-policy                      1.0.9  Configure security policies enforced by the browser
browser-policy-content              1.0.12  Configure content security policies
check                               1.2.4  Check whether a value matches a pattern
classcraft:edmodo-api               1.0.0+ A Meteor library to interact with Edmodo API (ported...
classcraft:microsoft-graph          1.0.0+ A Meteor library to interact with Microsoft Graph (p...
cultofcoders:redis-oplog            1.0.7  Replacement for Meteor's MongoDB oplog implementation
dburles:mongo-collection-instances  0.3.5  Access your Mongo instances
ecmascript                          0.6.0* Compiler plugin that supports ES2015+ in all .js files
ejson                               1.0.13  Extended and Extensible JSON library
email                               1.1.18  Send email messages
facebook                            1.2.10  Facebook OAuth flow
facts                               1.0.9  Publish internal app statistics
fds:latinize                        0.0.0  Simple library to convert accents (diacritics) from ...
force-ssl                           1.0.13  Require this application to use HTTPS
gadicc:blaze-react-component        1.4.0  <Blaze template="itemsList" items={items} />
gwendall:body-events                0.1.6  Get Template.body.events() working
harrison:papa-parse                 1.1.1  A powerful, in-browser CSV parser for big boys and g...
http                                1.2.10  Make HTTP calls to remote servers
jaywon:meteor-node-uuid             1.0.1  Generate RFC compliant UUIDs using node-uuid.
jparker:crypto-base64               0.1.0  Base64 (en/de)coding for CryptoJS, standard secure c...
jparker:crypto-md5                  0.1.1  MD5 algorithm for CryptoJS, standard secure algorithms
jparker:crypto-sha256               0.1.1  SHA256 algo for CryptoJS, standard secure crypto alg...
jquery                              1.11.10  Manipulate the DOM using CSS selectors
juliancwirko:postcss                1.2.0+ Minifier for Meteor with PostCSS processing - use Au...
kadira:flow-router                  2.12.1  Carefully Designed Client Side Router for Meteor
logging                             1.1.16  Logging facility.
markdown                            1.0.11  Markdown-to-HTML processor
matb33:collection-hooks             0.8.4  Extends Mongo.Collection with before/after hooks for...
mdg:validated-method                1.1.0  A simple wrapper for Meteor.methods
merlin:edmodo                       1.0.7  Edmodo OAuth flow
meteor-base                         1.0.4  Packages that every Meteor app needs
meteorhacks:aggregate               1.3.0  Proper MongoDB aggregations support for Meteor
meteorhacks:async                   1.0.0  Set of async utilities to work with NPM modules and ...
meteorhacks:kadira                  2.30.2  Performance Monitoring for Meteor
meteorhacks:picker                  1.0.3  Server Side Router for Meteor
meteorhacks:ssr                     2.2.0  Server Side Rendering for Meteor with Blaze
meteorhacks:unblock                 1.1.0  a way to use this.unblock inside publications
meteortoys:allthings                3.0.0  Insanely Handy Development Tools
mfpierre:chartist-js                1.6.3  Simple responsive charts
minifier-css                        1.2.15+ CSS minifier
mobile-experience                   1.0.4  Packages for a great mobile user experience
momentjs:moment                     2.16.0  Moment.js (official): parse, validate, manipulate, ...
mongo                               1.1.14  Adaptor for using MongoDB and Minimongo over DDP
mrgalaxy:stripe                     2.2.2  Stripe.js and Node-Stripe brought to Meteor.
mrt:jquery-ui-sortable              1.10.3  Reorder elements in a list or grid using the mouse
mrt:moment-timezone                 0.2.1  Timezone support for moment.js, packaged for Meteor....
numeral:numeral                     1.5.3_1  Numeral.js (official) - A library for formatting a...
oauth                               1.1.12  Common code for OAuth-based services
outatime:jwt-simple                 0.3.0  JWT(JSON Web Token) encode and decode module
percolate:google-api                1.0.3  A Meteor library to interact with Google's API
percolate:server-info               0.2.3  Returns diagnostics info on server internals via a c...
percolatestudio:segment.io          2.0.0_1* Segment.io integration for Meteor (works on both c...
q42:microsoft                       1.0.1  An implementation of the Microsoft OAuth flow.
raix:ui-dropped-event               0.0.7  Add dropped event to Meteor UI Templates
rajit:bootstrap3-datepicker         1.5.1  Meteor packaging of eternicode/bootstrap-datepicker ...
random                              1.0.10  Random number generator and utilities
react-meteor-data                   0.2.9  React mixin for reactively tracking Meteor data
react-template-helper               0.2.9  Use React components in native Meteor templates
reactive-var                        1.0.11  Reactive variable
reload                              1.1.11  Reload the page while preserving application state.
reywood:publish-composite           1.4.2  Publish a set of related documents from multiple col...
sergeyt:typeahead                   0.11.1_9  Autocomplete package for meteor powered by twitte...
service-configuration               1.0.11  Manage the configuration for third-party services
session                             1.1.7  Session variable
shell-server                        0.2.1  Server-side component of the `meteor shell` command.
spacebars                           1.0.13  Handlebars-like template language for Meteor
srp                                 1.0.10  Library for Secure Remote Password (SRP) exchanges
standard-app-packages               1.0.9  Moved to meteor-platform
standard-minifier-js                1.2.1  Standard javascript minifiers used with Meteor apps ...
stylus                              2.513.7* Expressive, dynamic, robust CSS
tmeasday:publish-counts             0.8.0  Publish the count of a cursor, in real time
tracker                             1.1.1  Dependency tracker to allow reactive callbacks
twitter                             1.1.13* Twitter OAuth flow
underscore                          1.0.10  Collection of small helpers: _.map, _.each, ...
wiseguyeh:azure-active-directory    1.0.0+ Azure Active Directory OAuth flow```

**Comment by theodorDiaconu** [comment]
@simonbelanger no probs, this issue gone a bit off-topic, but we made good progress on it. now regarding client-side entries. I will test, I have no idea why this happens. But very good find.

**Comment by maxnowack** [comment]
Just for reference, that's the piece of code where the server side methods are being generated:
https://github.com/meteor/meteor/blob/87681c8f166641c6c3e34958032a5a070aa2d11a/packages/allow-deny/allow-deny.js#L73-L204

**Comment by maxnowack** [comment]
Ok, I've got the point. We have to also extend the prototype of `LocalCollection`.
I'm already working on a PR :)

**Comment by theodorDiaconu** [comment]
@maxnowack I've omitted "transform" for now when creating a publication id, for people that I have defined a general transform. and yes, why would we need transform for publications ? makes no sense.

@maxnowack thank you. amazing! very curious to see it.

**Comment by simonbelanger** [comment]
Good catch @maxnowack , you da man!

**Comment by theodorDiaconu** [comment]
If you guys still need client-side functionality I suggest you create a simple wrapper.

```
clientify = function (Collection) {
         Meteor.methods({
                [Collection._name + '.insert'](...args) { 
                       // if server apply allow/deny rules, deny first.
                } 
         })

         // if client extend insert/update/remove to do the call for you.
})
```

Sorry about this, but investing effort in doing something bad is not good. And I'm sure you understand the decision of not supporting client-side mutations.

**Comment by maxnowack** [comment]
I have done the work: https://github.com/maxnowack/meteor-allowdeny-redisoplog
I've modified the core `allow-deny` package, which is responsible for client side mutations and build a custom package: https://github.com/maxnowack/meteor-allowdeny-redisoplog
This package overrides some functions on the collection prototype (basically it rewrites `this._collection.insertUpdateOrRemove` to `this.insertUpdateOrRemove`).

**Comment by theodorDiaconu** [comment]
@maxnowack you continue to amaze me. good job. I will put this package in the official readme docs.

**Comment by theodorDiaconu** [comment]
@maxnowack added it in the README.md, don't forget to publish it to atmosphere as well

**Comment by simonbelanger** [comment]
@maxnowack Great! I'll give it a try as soon as I can!

**Comment by maxnowack** [comment]
I'll have to do a bit more testing before I publish it ;)
@simonbelanger if you want to try out the package, make sure that allowdeny-redisoplog is loaded before the accounts package if you're using it.

**Comment by simonbelanger** [comment]
@maxnowack and how can I specify package loading order exactly?

**Comment by maxnowack** [comment]
@simonbelanger meteor loads the packages in the order as the `.meteor/packages` file ;)

**Comment by simonbelanger** [comment]
👍

**Comment by ramezrafla** [comment]
@theodorDiaconu, while I perfectly sympathize with your rationale that we want to follow MDG direction and avoid client-side mutations, I would recommend including this. Here is why: we want to easily replace existing functionality for a proper drop-in. As new users come on board they may try client-side updates. Just the mere fact that they have friction, and have to ask questions, means we may lose them or we have to answer their questions. All we need is a warning "Use at your own risk"
