### ISSUE TITLE
redis warning using Mongo bulk insert

### ISSUE THREAD

**Issue by hexsprite** [cult-of-coders/redis-oplog#40]
```
    node_redis: Deprecated: The PUBLISH command contains a "null" argument.
    This is converted to a "null" string now and will return an error from v.3.0 on.
    Please handle this in your code to make sure everything works as you intended it to.
```

Using some code like:

```
    @bulk = ActionsCollection.rawCollection().initializeUnorderedBulkOp()
...
          @bulk.find _id: action._id
            .updateOne $set:
              start: null
              end: null
....
      Meteor.wrapAsync(@bulk.execute, @bulk)()
```

**Comment by hexsprite** [comment]
I think it's to be expected that this would not work but just wonder why I would get this warning at all.

**Comment by theodorDiaconu** [comment]
@hexsprite what what ? I'm trying to understand how would it even reach redis. What we do, we only extend the Mongo.Collection.prototype, since you do rawCollection(), nothing should even affect redis. What you could do in this case. 

Clone this package in your packages folder. Go here:

https://github.com/cult-of-coders/redis-oplog/blob/master/lib/mongo/lib/publish.js#L11

..and do a console.trace() and see how this could have been possibly triggered.

Cheers

**Comment by theodorDiaconu** [comment]
ping @hexsprite

**Comment by hexsprite** [comment]
@theodorDiaconu I tried it and all console output would stop when I added .trace() for some reason. ;( I'll try it again soon and post my results here.

**Comment by theodorDiaconu** [comment]
@hexsprite maybe it stops when it knows it is observed, maybe some quantum thing going on ? :D 

Jokes aside, if you toggle between console.trace() and not the message appears ?

**Comment by hexsprite** [comment]
OK i tried the latest update and it no longer hangs with using `console.trace`. But that doesn't appear to be the issue. I think it's because I am publishing something that has no associated collection. Basically I am creating a collection that lives only on the client and is generated dynamically on the server.

I'm using .added/.changed which updates records on a client-side collection...

**Comment by theodorDiaconu** [comment]
@hexsprite 
https://github.com/cult-of-coders/redis-oplog/blob/master/lib/publishWithRedis.js#L36-L39

If your publication does not return anything, it will default to Meteor.publish behavior. I'm really interested in find up what's going on. Can you show us an example of your publication so we can write a test-case for it ?

**Comment by theodorDiaconu** [comment]
I am going to close this. Please re-open it when you have more information on this.
