### ISSUE TITLE
Changed parameter order on update method

### ISSUE THREAD

**Issue by maxnowack** [cult-of-coders/redis-oplog#42]
As mentioned in #41, the default parameter order of the update method has [changed](https://github.com/cult-of-coders/redis-oplog/blob/2d5834dc4e2945399f9bbe9fd5b6b66979f75a70/lib/mongo/collection.extension.js#L54-L61) from `( ... , options, callback)` to `( ... , callback, options)`. In the [default order](http://docs.meteor.com/api/collections.html#Mongo-Collection-update), the callback is always the last parameter. I haven't tested it yet, but passing custom options (like `multi: true`) to an update method shouldn't work at this moment

**Comment by theodorDiaconu** [comment]
Good point, the getMutationOptions would have been the function to detect it, but for update since we have config "built-in" it's ok. I definitely need to rewrite that function..
