### ISSUE TITLE
Wrong fields published on update

### ISSUE THREAD

**Issue by maxnowack** [cult-of-coders/redis-oplog#43]
There is a bug in [the `handleUpdate` method of the default processing strategy](https://github.com/cult-of-coders/redis-oplog/blob/master/lib/processors/default.js#L40-L44):
````es6
// …
if (observableCollection.contains(doc._id)) {
  observableCollection.change(doc._id, doc);
} else {
  observableCollection.add(doc);
}
// …
````

if the update gets called and the document isn't already in the observable collection, it will be added to it. But only with the fields, that were updated.
This bug is totally messing up my published documents and I'm not sure how to fix it.
Any ideas @theodorDiaconu?

I'm working on a test case for this

**Comment by theodorDiaconu** [comment]
Good find yes, I believe this is a quick fix. Working on it now.

**Comment by theodorDiaconu** [comment]
@maxnowack updated to 1.0.10
