### ISSUE TITLE
Support for collection2 parameters on insert function

### ISSUE THREAD

**Issue by maxnowack** [cult-of-coders/redis-oplog#47]
Exactly the same as #42. The changed parameter order breaks support for `aldeed:collection2` parameters.
See: https://github.com/aldeed/meteor-collection2#passing-options

**Comment by maxnowack** [comment]
@theodorDiaconu yes, exactly like in ed2aefad4f9006f9d8ae581ad685212f479a1aaa

**Comment by maxnowack** [comment]
It looks like b5ab7c8493e889a03eeb8230b814ac0f4742de74 hasn't fixed this issue yet. the options won't be passed down to the original insert/update/remove function.
I can fix this if you like, but it would be great if you have merged #50 before (to avoid unnecessary merge conflicts)

**Comment by maxnowack** [comment]
@theodorDiaconu can you please reopen this issue? I'll open a PR to fix it :)

**Comment by theodorDiaconu** [comment]
@maxnowack thanks!

**Comment by theodorDiaconu** [comment]
in package onTest require collection2 and write a test for it please.
