### ISSUE TITLE
Using fields in a publication and making an update to a nested item on it does not properly update the client-side store.

### ISSUE THREAD

**Issue by willhoyle** [cult-of-coders/redis-oplog#48]
Can I get clarification on this part in the readme?
```
Warning! If your publication contains "fields" options.

{
    fields: { text: 1, typing: 1 }
}
Even if the fields don't actually exist in the db. The reason we do it like this, is to allow control over access in the synthetic events. For some people you may want to see them, others you do not, depending on their role.
```

I have a publication with a cursor such as:
```
Meteor.publish('user.roles', function() {
  if (!this.userId) {
    throw new Meteor.Error('notLoggedIn')
  }
  return Meteor.users.find(this.userId, {fields: {roles: 1}})
})
```
When I replace my Meteor.publish with Meteor.publishWithRedis, I seem to be getting errors in my app.

**Comment by theodorDiaconu** [comment]
@willhoyle that is related to synthetic mutations, unless you use that you don't need to worry about it.

What errors ? Be more descriptive, help us reproduce it.

**Comment by willhoyle** [comment]
In my app my users have a field in their document called roles and it looks like this:
```
{
  "roles": {
    "_groups": [
        "company1",
        "company2",
        "company3"
    ],
    "_main": "company1",
    "_global": {
      "roles": [
        "manage-users",
        "manage-profiles",
        etc...
      ]
    }
  }
}
```

A user such as the one above can navigate the website acting as a different company. I have a dropdown menu with company1, company3, company3. When a new one is clicked, I call a Meteor method:
```
// Only declared on the server
Meteor.call("changeMain", company)
Meteor.methods({
    changeMain: function(company) {
        //validate company, etc
        
        // Update user doc 
        Meteor.users.update(this.userId, {$set: {"roles._main": company}})
    }
})
```

On the client I have a Tracker.autorun reacting to changes in the "roles._main" field.

When I have the fields option {fields:    {roles: 1 }} in my publication cursor, when I change the group it reverts back to the previous group instantly.

Here's the debug output when I change groups:

```
[Main] New incomming subscription for publication: user.roles
[PublicationFactory] Created new subscribers for redis for "user.roles" :: {"_id":"YeyNsLTRQdF7Df7i7  {"fields":{"roles":1}}
[PublicationEntry] Performing initial add for observer
[RedisSubscriptionManager] Subscribing to channel: users::YeyNsLTRQdF7Df7i7
[RedisSubscriptionManager] Sending event: u to users::YeyNsLTRQdF7Df7i7 ... // <---- this is sent when I click another company to change the "_main"
```

Now what's even more interesting is if I click a new company, it won't change but if I refresh the browser, the user's "_main" field will be the new company I clicked. Seems strange. And none of these errors happen when I remove the fields option in the publication.

**Comment by trackchris** [comment]
I've been having similar issues as described above with nested documents too, when I revert to using Mongo's Oplog it then behaves as expected. I haven't had time to investigate it further or build a reproduction yet though unfortunately.

**Comment by theodorDiaconu** [comment]
@willhoyle your example is perfect! I will transform it into an use-case and solve it. I think I know what's going on... it's a very good find!

@trackchris even if you don't have time to track it, it's good to create an issue here I may instantly know what's going on.

**Comment by theodorDiaconu** [comment]
@willhoyle solved written 2 tests that match your exact use case. Thanks for taking time to notify me on this one. Good job.

**Comment by willhoyle** [comment]
@theodorDiaconu wow that was quick! can confirm it works properly now. thanks for the fix
