### ISSUE TITLE
Latency compensation doesn't work properly

### ISSUE THREAD

**Issue by maxnowack** [cult-of-coders/redis-oplog#51]
As mentioned in [this post](https://forums.meteor.com/t/meteor-scaling-redis-oplog-status-1-0-11/30855/207?u=maxnowack), I've noticed an issue with latency compensation / optimistic ui.
The changed documents will be synced to the client, after the result of a method was received. That causes some flickering. The method on the client side will be reverted because the changes were not sent by the server before the method result was received.
The normal behavior is, that the changes were synced, while the client is waiting for the method result. After the result was received, the client compares invalidates the local working copy (minimongo) and takes the current state from the server.

DDP behavior with redis oplog:
![image](https://cloud.githubusercontent.com/assets/186073/20576956/667afe20-b1c0-11e6-8935-4f7ef5b62cd7.png)

Normal DDP behavior:
![image](https://cloud.githubusercontent.com/assets/186073/20576966/73ab3dc6-b1c0-11e6-8108-0bffa4900ef4.png)

**Comment by theodorDiaconu** [comment]
Ok so let me think, I saw that you got most of the code from here:
https://github.com/meteor/meteor/blob/devel/packages/allow-deny/allow-deny.js#L356

And did the inserts on the collection not collection._collection.

Ok I get it so the problem is that it causes flickering, but in the end, the local state is the correct one ?

**Comment by theodorDiaconu** [comment]
@maxnowack just tested this locally and it works for me without a problem. Client-side inserts are updated properly.

**Comment by maxnowack** [comment]
hmm, I got the same issue without my package and normal method calls:
![image](https://cloud.githubusercontent.com/assets/186073/20591304/2976377a-b228-11e6-916b-3419185270e7.png)

**Comment by theodorDiaconu** [comment]
@maxnowack then it is not related to client-side inserts. good we figured that out.

But what is the reason, you do a call, the local side seems to be updated. What's the exact issue ?

**Comment by theodorDiaconu** [comment]
@maxnowack for latency compensation you will need to do Meteor.apply('name', [args], options)

**Comment by maxnowack** [comment]
I think this demo explains the issue:
![redisoplog_lc](https://cloud.githubusercontent.com/assets/186073/20592210/88d62eb0-b22c-11e6-8c29-1688eb6ab57e.gif)
As you can see, the post was added, then removed and then readded.
Here's the code: https://github.com/maxnowack/meteor-redisoplog-latencycompensation

**Comment by maxnowack** [comment]
@theodorDiaconu why do I need to use `Meteor.apply` for latency compensation? It is sufficient, if the method was defined on client and server, isn't it?

**Comment by theodorDiaconu** [comment]
@maxnowack no, that's not how it works. Thing is optimistic ui is very badly documented. I am now cloning the repo and trying with apply :)

**Comment by maxnowack** [comment]
But without the redis oplog package, the latency compensation is working fine:
![image](https://cloud.githubusercontent.com/assets/186073/20592476/0302cfd0-b22e-11e6-8219-442a6292c37e.png)
you can try it in the `without-redisoplog` branch

**Comment by maxnowack** [comment]
Ah, the root of the issue isn't the result of the method, but the `updated` message for the method

**Comment by theodorDiaconu** [comment]
@maxnowack you are correct I am now investigating. this is still not good.

**Comment by theodorDiaconu** [comment]
I'm absolutely baffled, I have no idea why client-side inserts work from my other application without your package..

**Comment by maxnowack** [comment]
That's the piece of code, where the `updated` message is being send: https://github.com/meteor/meteor/blob/devel/packages/ddp-server/livedata_server.js#L643-L656

**Comment by theodorDiaconu** [comment]
was just looking there, it seems that they somehow await other publications to do their thing before returning the result. It means that we need to somehow hook into that fence

**Comment by theodorDiaconu** [comment]
https://github.com/meteor/meteor/blob/devel/packages/mongo/mongo_driver.js#L295-L309

Made progress on this managed to get the change from a client-side insert inside the ObservableCollection now I need to understand how to make it performant.

**Comment by theodorDiaconu** [comment]
So... here is the deal if you are curious:
https://github.com/meteor/meteor/blob/devel/packages/mongo/mongo_driver.js#L363-L366

```
// this is the refresh method.
Meteor.refresh = function (notification) {                                                                           // 8
  DDPServer._InvalidationCrossbar.fire(notification);                                                                // 9
};     
```

So basically all listeners to the _InvalidationCrossbar are fired, before the end-result of a method is pushed to the client. So they can do it in sync and do the updates, before sending that 'update' message we saw.

```
// in RedisSubscriber we could do something like this.
DDPServer._InvalidationCrossbar.listen({ collection: observableCollection.collectionName}, (notification) => {
            const { id } = notification;
            // process the query
            console.log(notification); // looks like { collection: 'X', id: 'Y' }
        })
```

Oh boy what have I gotten myself into...

**Comment by maxnowack** [comment]
@theodorDiaconu this seems to be broken again in 1.1.6 :(

**Comment by theodorDiaconu** [comment]
@maxnowack hmm, I did not actually test, but I kept the compensateLatency from 1.1.5. Will check. Should I look here https://github.com/maxnowack/meteor-redisoplog-latencycompensation ?

**Comment by maxnowack** [comment]
@theodorDiaconu yes, I've just updated the repo to the latest version of redis-oplog

**Comment by maxnowack** [comment]
@theodorDiaconu please reopen this issue. I'll try to write some tests for this case

**Comment by theodorDiaconu** [comment]
it makes sense yes. it was an easy fix, but I have no idea how to test this.
