### ISSUE TITLE
Not all fields being pushed to client after updating a nested document

### ISSUE THREAD

**Issue by trackchris** [cult-of-coders/redis-oplog#53]
I have a collection which contains numerous fields including an array of nested documents comprising of 2 fields, the schema for the nested doc is as follows:

```
  'bom.$.stockId': {
    type: String,
    regEx: SimpleSchema.RegEx.Id,
  },
  'bom.$.quantity': {
    type: Number,
  },
```

When performing an update to a single field (the quantity) in the nested document using a Meteor method, the stockId field is not transmitted back to the client when using Redis Oplog.

Here is a screenshot of the DDP messages when using Redis Oplog:

![image](https://cloud.githubusercontent.com/assets/11329036/20599207/d8e57916-b244-11e6-9927-a4ce8351b38d.png)

And here without Redis Oplog:

![image](https://cloud.githubusercontent.com/assets/11329036/20599223/eace86cc-b244-11e6-9127-fd62f903f63e.png)

The publication code (removed validation etc to keep it relevant and concise):

```
Meteor.publish('Stock.BOM.List', function (stockId, bomList) {
  const fields = {
    _id: 1,
    partNo: 1,
    title: 1,
    location: 1,
    warehouseId: 1,
  };

  return Stock.find({ _id: { $in: bomList }, organisationId }, { fields });
});
```

The collection update within the method is:

`Stock.update({
      _id: stockId,
      organisationId,
      'bom.stockId': bomFormValues.chosenStockItem,
    }, {
      $set: {
        'bom.$.quantity': bomFormValues.quantity,
      },
    });`

It seems as though the first nested field does not get transmitted. I have a slightly more advanced array of nested document with 4 fields that does the same thing (i.e 3 get transmitted and 1 is missing).

Let me know if you need more info, thanks!

**Comment by theodorDiaconu** [comment]
@trackchris confirm that you are using 1.0.11 first please.

**Comment by trackchris** [comment]
Oops forgot to mention that - yes I am using 1.0.11

**Comment by theodorDiaconu** [comment]
@trackchris perfect I will take care of this ASAP. Today I lost almost 4 hours, but I figured out a way to solve the Latency Compensation issue.

**Comment by theodorDiaconu** [comment]
@trackchris your issue is related to the fact that bom is an array. I did not take into account that. Super good find!
