### ISSUE TITLE
Publish Composite replacement with redis oplog observer

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#6]
1. Create an observerCollection for the main element
2. On added/changed/remove recompute the subsequent publications of the next elements in order to update them

Offer ability to an ObservableCollection to "modifyCursor" & reprocess the query. Make performant diffing.

**Comment by theodorDiaconu** [comment]
PubNode
      parent
      find
      children
      eventEmitter
      observableCollection

**Comment by s-devaney** [comment]
+1 I have a highly relational data set, I will struggle to use this without composite publishing

**Comment by theodorDiaconu** [comment]
closing this for https://github.com/cult-of-coders/redis-oplog/issues/30
