### ISSUE TITLE
Can't get SyntheticMutation to work

### ISSUE THREAD

**Issue by ramezrafla** [cult-of-coders/redis-oplog#62]
We have a publication with a custom channel and it's working well without SyntheticMutation, on both server and client.

When we replace this:
```self.collection.update({_id:to},{$push:{messages:message}},{channel:channel});```

With either
```SyntheticMutation(channel).update({_id:to},{$push:{messages:message}})```
Or
```SyntheticMutation(self.collection.update).update({_id:to},{$push:{messages:message}},{channel:channel})```

The client doesn't get the data anymore.

**Comment by theodorDiaconu** [comment]
@ramezrafla I should have mentioned this. SyntheticMutation accepts an object that will deepExtend the current object. No MongoDB modifiers. Though maybe we could use a library to accept them.

So if you want to add another message to the messages array currently it is not possible.

**Comment by theodorDiaconu** [comment]
https://www.npmjs.com/package/mongo-query maybe we could use this one.

**Comment by ramezrafla** [comment]
Beautiful! SyntheticMutation is indeed a game-changer! As a wise man said in the readme: "Bounded by your imagination" :)

**Comment by ramezrafla** [comment]
I think I understand better, as you are bypassing mongo, you are affecting the data directly.

**Comment by theodorDiaconu** [comment]
I will close this @ramezrafla  . If it still does not work re-open it.

**Comment by ramezrafla** [comment]
Thanks @theodorDiaconu 
But it still does not work.

Here is how I publish:
```return self.collection.find({_id:this.userId}, { fields:{messages:1}, channel:channel} );```

And here is how I push:
```SyntheticMutation(channel).update({_id:to},{$push:{messages:message}})```
Or
```SyntheticMutation(self.collection.update).update({_id:to},{$push:{messages:message}},{channel:channel})```

If we remove SyntheticMutation from the second one above, all works as planned.

**Comment by theodorDiaconu** [comment]
```SyntheticMutation(self.collection.update).update({_id:to},{messages:message})```

Because we do not support modifiers in the update from synthetic mutation. We will add support for this in next release.

**Comment by ramezrafla** [comment]
Sorry, misunderstood when you closed this issue. Is there a way right now to add element to an array? I understood from prior message that there is not.
