### ISSUE TITLE
Error with meteorhacks:kadira?

### ISSUE THREAD

**Issue by jamesgibson14** [cult-of-coders/redis-oplog#63]
I just go this error I don't think I changed anything except maybe the update to 1.0.13, any ideas? 

I20161128-12:03:41.641(-7)? [PublicationEntry] Performing initial add for observer
I20161128-12:03:41.643(-7)? [RedisSubscriptionManager] Subscribing to channel: __dummy_coll_kshBrXjZse2XcH2MS
I20161128-12:03:41.785(-7)? [PublicationEntry] Performing initial add for observer
I20161128-12:03:41.795(-7)? [RedisSubscriptionManager] Unsubscribing from channel: __dummy_coll_kshBrXjZse2XcH2MS
I20161128-12:03:41.798(-7)? [RedisSubscriptionManager] Subscribing to channel: __dummy_coll_kshBrXjZse2XcH2MS
I20161128-12:03:41.926(-7)? [PublicationEntry] Performing initial add for observer
I20161128-12:03:41.927(-7)? [RedisSubscriptionManager] Unsubscribing from channel: __dummy_coll_kshBrXjZse2XcH2MS
I20161128-12:03:41.928(-7)? [RedisSubscriptionManager] Subscribing to channel: __dummy_coll_kshBrXjZse2XcH2MS
W20161128-12:03:42.066(-7)? (STDERR) /home/james/.meteor/packages/meteor-tool/.1.4.2_3.ochefg++os.linux.x86_64+web.brows
er+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161128-12:03:42.067(-7)? (STDERR)                                            throw(ex);
W20161128-12:03:42.068(-7)? (STDERR)                                            ^
W20161128-12:03:42.068(-7)? (STDERR)
W20161128-12:03:42.068(-7)? (STDERR) TypeError: Cannot read property 'prototype' of undefined
W20161128-12:03:42.069(-7)? (STDERR)     at setLabels (packages/meteorhacks_kadira.js:3683:45)
W20161128-12:03:42.069(-7)? (STDERR)     at packages/meteorhacks_kadira.js:3194:5
W20161128-12:03:42.069(-7)? (STDERR)     at runWithAFiber (packages/meteorhacks_meteorx.js:192:5)
W20161128-12:03:42.070(-7)? (STDERR)     at packages/meteorhacks_meteorx.js:185:5
W20161128-12:03:42.070(-7)? (STDERR)     at Array.forEach (native)
W20161128-12:03:42.071(-7)? (STDERR)     at packages/meteorhacks_meteorx.js:184:27
W20161128-12:03:42.072(-7)? (STDERR)     at Function.time (/home/james/argus/.meteor/local/build/programs/server/profile
.js:301:28)
W20161128-12:03:42.072(-7)? (STDERR)     at /home/james/argus/.meteor/local/build/programs/server/boot.js:304:13
W20161128-12:03:42.072(-7)? (STDERR)     at /home/james/argus/.meteor/local/build/programs/server/boot.js:345:5
W20161128-12:03:42.073(-7)? (STDERR)     at Function.run (/home/james/argus/.meteor/local/build/programs/server/profile.
js:480:12)
W20161128-12:03:42.073(-7)? (STDERR)     at /home/james/argus/.meteor/local/build/programs/server/boot.js:343:11

**Comment by jamesgibson14** [comment]
I have verified the 1.0.10 works with kadira. I am guessing it is because this file tries to extend the prototype of mongo observers: 
https://github.com/meteorhacks/kadira/blob/384463446f613a4dd32275c732f8be3db761f4b4/lib/hijack/set_labels.js

**Comment by theodorDiaconu** [comment]
@jamesgibson14 good find, will fix.
