### ISSUE TITLE
Don't trigger changes if nothing was actually changed

### ISSUE THREAD

**Issue by Maxpain177** [cult-of-coders/redis-oplog#64]
oldDoc not passing

```javascript
Items.find().observe({
  changed(newDoc, oldDoc) {
    console.log(newDoc, oldDoc) // { foo: "bar" } undefined
  }
})
```

It's possbile fix it?

**Comment by theodorDiaconu** [comment]
@Maxpain177  good find. yes it will be fixed.

**Comment by theodorDiaconu** [comment]
@Maxpain177  a lot of changes are currently required to do such a thing. Basically the current observe() is not a full implementation of the observe() which has support for addedBefore, etc.

Do you really need this functionality ? This is my question. Because if there is no way to work-around this in some scenarios we will implement it.

**Comment by Maxpain177** [comment]
@theodorDiaconu Yes, In my project (which contains several microservices, connected to one mongodb and redis) it is using everywhere.

**Comment by theodorDiaconu** [comment]
@Maxpain177 I understand. Redis-oplog is now ready to go under some restructuring and refactoring, and this will be included :)

**Comment by Maxpain177** [comment]
@theodorDiaconu, Currently, i can't use this package, because i need remake most part of application architecture for working without oldDoc.
Thanks 👍

**Comment by theodorDiaconu** [comment]
@Maxpain177 check it now :)

**Comment by Maxpain177** [comment]
Yes, it works. But, if nothing changed in doc, changed function still fires.

**Comment by theodorDiaconu** [comment]
@Maxpain177  can you give me an example ? What kind of update you do ?

**Comment by Maxpain177** [comment]
Just updating document.
```javascript
Counts.update({  })

**Comment by Maxpain177** [comment]
@theodorDiaconu 
Just updating document.
```javascript
Counts.update({ _id: "users" }, { $set: { count: 0 } })
```

**Comment by theodorDiaconu** [comment]
@maxnowack so if "count" was previously ZERO, it should not fire the change event.

**Comment by Maxpain177** [comment]
[Reproduction](https://github.com/Maxpain177/oplog-observe-issue-64)

**Comment by theodorDiaconu** [comment]
Fixed.
