### ISSUE TITLE
Looks like error with matb33:collection-hooks in 1.0.14

### ISSUE THREAD

**Issue by jamesgibson14** [cult-of-coders/redis-oplog#68]
I20161129-07:14:00.155(-7)? Exception in defer callback: TypeError: Cannot convert undefined or null to object
I20161129-07:14:00.158(-7)?     at keys (native)
I20161129-07:14:00.160(-7)?     at Function.keys (/home/james/.meteor/packages/es5-shim/.4.6.15.5j45wu++os+web.browser+w
eb.cordova/npm/node_modules/es5-shim/es5-shim.js:1103:24)
I20161129-07:14:00.161(-7)?     at DotObject.dot (/home/james/.meteor/packages/cultofcoders_redis-oplog/.1.0.14.s1f2xl++
os+web.browser+web.cordova/npm/node_modules/dot-object/index.js:440:10)
I20161129-07:14:00.162(-7)?     at Function.dot (/home/james/.meteor/packages/cultofcoders_redis-oplog/.1.0.14.s1f2xl++o
s+web.browser+web.cordova/npm/node_modules/dot-object/index.js:62:31)
I20161129-07:14:00.164(-7)?     at SmartObject.getDotObject (packages/cultofcoders:redis-oplog/lib/utils/SmartObject.js:
39:34)
I20161129-07:14:00.165(-7)?     at packages/cultofcoders:redis-oplog/lib/mongo/collection.extension.js:55:77
I20161129-07:14:00.166(-7)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20161129-07:14:00.172(-7)?     at packages/meteor.js:445:45
I20161129-07:14:00.173(-7)?     at runWithEnvironment (packages/meteor.js:1176:24)
I20161129-07:14:00.178(-7)? Exception in callback of async function: TypeError: callback is not a function
I20161129-07:14:00.178(-7)?     at packages/mongo/collection.js:651:5
I20161129-07:14:00.179(-7)?     at args.(anonymous function) (packages/matb33_collection-hooks.js:391:23)
I20161129-07:14:00.180(-7)?     at runWithEnvironment (packages/meteor.js:1176:24)
I20161129-07:14:00.180(-7)?     at packages/meteor.js:1189:14
I20161129-07:14:00.181(-7)?     at packages/mongo/mongo_driver.js:328:7
I20161129-07:14:00.181(-7)?     at runWithEnvironment (packages/meteor.js:1176:24)

**Comment by theodorDiaconu** [comment]
@jamesgibson14 give me a bit of info regarding the update that triggers this. thanks.

**Comment by jamesgibson14** [comment]
Not sure but I do know matb33:collection-hooks wraps the Collection function `.insert`, `.update`, `.remove`; 
I create a hook;
`Records.before.insert(function(userId,doc){
   //do some stuff before insert;
})`
Whenever my insert / update hooks try and run... I get the error above.  this doesn't happen on 1.0.10.
