### ISSUE TITLE
Reactive publishing gets triggered needlessly

### ISSUE THREAD

**Issue by ramezrafla** [cult-of-coders/redis-oplog#71]
We have a reactive publication using peerless's library. It gets triggered every time we have a change in the cursor it's pushing (vs. the cursor(s) it depends in this.autorun)

**Comment by theodorDiaconu** [comment]
1. Why do you use autorun on the server-side, seems like a bad practice ?
2. Isn't that the expected behavior ?

**Comment by ramezrafla** [comment]
1. autorun is how reactive publishing works with [https://github.com/peerlibrary/meteor-reactive-publish](https://github.com/peerlibrary/meteor-reactive-publish)
2. The expected behavior is that if another cursor within the autopublish changes, the function gets re-executed. But not the returned cursor, as that is expected to change. So in the example in the link above:

```Meteor.publish('subscribed-posts', function () {
  this.autorun(function (computation) {
    var user = User.findOne(this.userId, {fields: {subscribedPosts: 1}});

    return Posts.find({_id: {$in: user && user.subscribedPosts || []}});
  });
});

**Comment by maxnowack** [comment]
It's because of the ` find`'s and `findOne`'s used in the functions in (this file)[https://github.com/cult-of-coders/redis-oplog/blob/master/lib/mongo/Mutator.js].
Can probably be fixed easily by passing `reactive: false` to the options of `find` and `findOne`.

**Comment by ramezrafla** [comment]
Thanks @maxnowack 
So to be clear, we should make the returned cursor non-reactive

**Comment by ramezrafla** [comment]
I can confirm that this solves the problem! Thanks @maxnowack

**Comment by ramezrafla** [comment]
With {reactive:false} we lose client-side reactivity (Note: this is unrelated to #73)

**Comment by maxnowack** [comment]
Yes, of course. `reactive: false` has to be added to the options of the cursors inside the overridden mutation functions in this package.

**Comment by ramezrafla** [comment]
Wouldn't that disable reactive push? That's the whole purpose of having these cursors there, is making the cursor watch them and republish based on their changes. What is happening is that, in addition to this, any changes to the cursor being pushed also re-publishes. We tested without redis-oplog and get the normal behavior.

**Comment by theodorDiaconu** [comment]
Is this solved @ramezrafla  ?

**Comment by ramezrafla** [comment]
Can I get back to you shortly, will run some tests.

**Comment by ramezrafla** [comment]
I'll close this issue as it's not really disturbing us (and didn't get the chance to dig deeper). Will reopen if it arises again, thanks @theodorDiaconu !
