### ISSUE TITLE
When pulling from an array, and that array was left empty, the changes were not pushed.

### ISSUE THREAD

**Issue by ramezrafla** [cult-of-coders/redis-oplog#73]
Last working commit 539ac28 onwards client-side observers don't see data changes

When we disable redis-oplog all works as planned. We are using regular subscriptions (not reactive or publishComposite)

Below is the publish function

```
    Meteor.publish("classroom", function() {
        if (!this.userId) return;
        var profile = User.get(['users','isInstructor','login'],this.userId);
        // only instructors can watch their students
        var users = profile.isInstructor ? profile.users || [] : []
        Logger.log('Classroom - publish: ' + profile.login);
        var fields =   {connected:1, type:1, force:1, follow:1, online:1, active:1, forceModel:1, messages:1, autoConnect:1, disconnects:1, selected:1, report:1} 
        return self.collection.find({_id:{$in:users}},{fields:fields});
    });
```

We are seeing a first change, then further changes are no longer pushed to client. Strange!

**Comment by ramezrafla** [comment]
I am available to help debugging, as with reactive publishing, it sporadically works in the commit above.

**Comment by ramezrafla** [comment]
This is very strange - I can see the traffic in redis-cli monitor but client data does not get updated

**Comment by theodorDiaconu** [comment]
@ramezrafla can you write a quick reproduction repo?

**Comment by theodorDiaconu** [comment]
@ramezrafla the tests are passing and they test exactly this, what would help us is to share, what kind of update you do that is not somehow processed by redis-oplog.

**Comment by theodorDiaconu** [comment]
https://github.com/cult-of-coders/redis-oplog/commit/a08dd0accefd40d234e924eb9898d7a76dd5a142#diff-bf204365b06b5ff7a09527e4e8218c56R515

**Comment by ramezrafla** [comment]
Thanks @theodorDiaconu for taking the time to debug this edge case with me. Always a pleasure.
I confirm that this issue is resolved.
