### ISSUE TITLE
SyntheticMutator not interpreting mongo operators

### ISSUE THREAD

**Issue by ramezrafla** [cult-of-coders/redis-oplog#75]
When looking at the Redis logs we see variable $push being sent down, so not interpreted by mongo-query.

```1480630687.683521 [0 127.0.0.1:42830] "publish" "classroom-messages" "{\"e\":\"u\",\"s\":true,\"d\":{\"$push\":{\"messages\":{\"command\":\"SETSESSION\",\"parameters\":{\"name\":\"Applications.instructorEnabled\",\"value\":null},\"requestId\":2,\"createdAt\":{\"$date\":1480630687665},\"from\":\"29oR2JSTTaBKGJKmM\",\"_id\":\"AjJ3fNnmogGcGtDwo\"}},\"_id\":\"dE5mgisYHuLymCQdG\"}}"```

**Comment by theodorDiaconu** [comment]
Just written a test case for this, it seems like another edge-case ?

**Comment by ramezrafla** [comment]
When I tried to debug it, ObservableCollection change method gets isSynthetic and modifier as undefined. I didn't test with a simpler variable.

Also, why don't we just assume that Synthetic.update always expects a mongo modifier? That's the point of BC no? Also, who would mix their code up with Mongo queries and regular variables.

**Comment by ramezrafla** [comment]
Thanks for your support, I can confirm with proper channel this works. We need to update readme for more clarity. I'll see if I can add value with a PR
