### ISSUE TITLE
[Idea] Add collection methods, before and after hooks

### ISSUE THREAD

**Issue by jamesgibson14** [cult-of-coders/redis-oplog#77]
mat3b:collection-hooks is a great package but has some inefficiencies, like query the DB even when not needed. It would be great if RedisOplog could handles hooks where it is already focused on only talking to the DB when needed.

**Comment by ramezrafla** [comment]
I am concerned that it slows things down since you have to check if there are hooks at every DB action. I did see that there is a .direct option, but it requires users to know about this. So adding hooks is technically BC but isn't at the same time as we have to make changes to our code to have max efficiency.

**Comment by theodorDiaconu** [comment]
@jamesgibson14 that kind of a collection-hook-er would be a different package I don't think we could bundle them up in here. They are not the same concerns

**Comment by theodorDiaconu** [comment]
If you think that it's a good idea, pls tell me your arguments. Collection hooks is indeed sometimes inefficient, but heck, it does the job. Maybe you can submit a PR there to make it more efficient ?

**Comment by jamesgibson14** [comment]
I agree that hooks do slow down the process, but since I am going to be using RedisOplog, a simple flag check:
`if(collection.hasHooks)
  Meteor.defer(runHooksFunction)
`
My arguments are that I need to run the hooks anyway, I would rather take advantage of the PublicationStore. Collection-hooks can be improved but it still calls the DB again to get the same doc.
