### ISSUE TITLE
server-side $set fails to update client

### ISSUE THREAD

**Issue by ramezrafla** [cult-of-coders/redis-oplog#79]
Here is the redis log output (which is correct)

``
1480655469.956484 [0 127.0.0.1:35132] "publish" "content" "{\"e\":\"u\",\"f\":[\"meta.parent\"],\"d\":{\"_id\":\"twGNzy3xapkJMvYgi\",\"meta\":{\"parent\":true}}}"
1480655469.956546 [0 127.0.0.1:35132] "publish" "content::twGNzy3xapkJMvYgi" "{\"e\":\"u\",\"f\":[\"meta.parent\"],\"d\":{\"_id\":\"twGNzy3xapkJMvYgi\",\"meta\":{\"parent\":true}}}"
``

But on the client meta.parent remains false. In fact, if it starts out as true, we can switch to false and it works. But we can't switch back to true, stays stuck as false client-side, even though DB changed.

Here is our query, which runs server-side.
``self.collection.update(id,{$set:{meta.parent:false}});``

**Comment by theodorDiaconu** [comment]
@ramezrafla we already have a test-case for deep-nested $sets. Something is again different, when you submit a bug give me the sample publication, because as you've seen it may be related to fields.

**Comment by ramezrafla** [comment]
Here is the publish 

```
    Meteor.publishComposite('content',{
      find: function() {
        if (!this.userId) return;
        return Meteor.users.find({_id:this.userId},{fields:{'profile.users':1,'profile.content':1}});
      },
      children: [
        {
          // users
          find: function(user) {
            if (!user) return;
            var users = user.profile.users;

            // Logger.debug('Content - publish: users = ' + users);
            if (users && users.length) {
              // we need to clean up users to remove ourselve otherwise we may override User publication
              var index = users.indexOf(this.userId);
              if (index != -1) {
                users.splice(index,1)
                Meteor.users.update({_id:this.userId},{$pull:{'profile.users':this.userId}});
              }
              if (users.length == 0) return
              // lastname is published for sorting purposes in different view
              // add all parents to instructor
              if (user.profile.isInstructor) {
                return Meteor.users.find({_id:{$in:users}},{fields:{'profile.fullname':1,'profile.lastname':1,'profile.isInstructor':1,'profile.isStudent':1,'profile.parents':1}});
              }
              return Meteor.users.find({_id:{$in:users}},{fields:{'profile.fullname':1,'profile.lastname':1,'profile.isInstructor':1,'profile.isStudent':1}});
            }
            return;
          }
        },
        {
          // content
          find: function(user) {
            if (!user) return;
            var content = user.profile.content;
            // Logger.debug('Content - publish: content = ' + content);
            if (content) {
              if (user.profile.isStudent) return self.collection.find({_id:{$in:content},'meta.student':true});
              if (user.profile.isParent) return self.collection.find({_id:{$in:content},'meta.parent':true});
              return self.collection.find({_id:{$in:content}});
            }
            return;
          }
        }
      ]
    });```

**Comment by theodorDiaconu** [comment]
should be working now, re-open if still occurs.

**Comment by ramezrafla** [comment]
@theodorDiaconu , thanks!
Just tried and it still does not work.

The behavior now is a bit different. If a client calls a method to make a change, others see it, but it does not get a data update. Likely related to top-level changes only for DDP again?

```
self.collection.update(id,{$set:{meta.student:false}});
```

**Comment by ramezrafla** [comment]
@theodorDiaconu, we got it working by dispensing with the publishComposite and using two reactive publishes instead.

With publishComposite, the publishing works at start (we get the data), but then we get no updates [I have seen sporadic updates, though, but only once and then it stops]. Note that this happens with both top level fields and 2nd-level ones. publishComposite is important for many applications, so I am available to support you to debug it.

**Comment by ramezrafla** [comment]
Some more updates, even with reactive publishing and regular publishing we are still facing this issue. It started out better, but eventually data updates don't reach the client. We are available to debug.

It might relate to how we publish, we send a cursor like this:
```
return self.collection.find({_id:{$in:content}});
```

Maybe channels get somehow confused when we have so many id's (given channels are id-dependent)
