### ISSUE TITLE
Error, object being sent to mongo.insert, should be callback function or null

### ISSUE THREAD

**Issue by jamesgibson14** [cult-of-coders/redis-oplog#83]
Okay I finally found what is causing a "function undefined error". 
On insert 
https://github.com/cult-of-coders/redis-oplog/blob/master/lib/mongo/Mutator.js#L11
passes a config object `{_pushToRedis: true}`
mongo.insert expects the second argument to be a function or nothing:
https://github.com/meteor/meteor/blob/master/packages/mongo/collection.js#L467

**Comment by jamesgibson14** [comment]
It looks like the insert still work, then it just errors out on the callback function.

**Comment by jamesgibson14** [comment]
Also adding callback to an insert don't work:
`Collection.insert({test:true}, function(error, result){
  //do stuff after insert
})`
the callback get overridden by getMutationConfig

**Comment by theodorDiaconu** [comment]
@jamesgibson14 we had some problems with the callbacks before so they are currently not supported. Why do you use callbacks ?

**Comment by theodorDiaconu** [comment]
the problem is that, we cannot really make them async, just emulate the callback somehow. This is why we discourage callbacks to be used. Maybe the thing here would be to display a propper error.

**Comment by jamesgibson14** [comment]
Okay, so maybe just send a null  on Mutator.js instead of the config obj:
`const result = Originals.insert.call(this, data, null);`
I do use callbacks sometimes usually for error management, but I probably don't have to...

**Comment by jamesgibson14** [comment]
Yes, that should work fine. I guess I just didn't understand the callback limitations.

**Comment by theodorDiaconu** [comment]
Thank you.
