### ISSUE TITLE
Should SyntheticMutation keep local copy of data?

### ISSUE THREAD

**Issue by ramezrafla** [cult-of-coders/redis-oplog#88]
We had to stop using SyntheticMutator as the local copy of the data became a problem. When multiple instances of Meteor are running, the instance issuing the data send may not be the same as one managing the receiver. So the sender keeps the data as we have no way of clearing it when the receiver gets it. I hope I am clear :)

Maybe SyntheticMutator should be nothing more than a sender with no storage. If we want some sort of data persistence we should fall back on Mongo. That conflict of functionality (you either want to store or not -- if storing, it has to be DB) may reduce the value of SyntheticMutator in production when multiple instances of Meteor are running by default.

**Comment by theodorDiaconu** [comment]
@ramezrafla I think this should be configurable. If you want to fire and forget. We could do

SyntheticMutator.update(Users, "messages", {}, {noStorage: true})

**Comment by ramezrafla** [comment]
Agreed, I propose it be the other way:

``SyntheticMutator.update(Users, "messages", {}, {storeInMemory: true})``

The default should be non-persistent as in production, most of us would not use memory storage (as mentioned above 1. defeats the purpose of a central DB, 2. wouldn't work when you have many meteor instances)

**Comment by theodorDiaconu** [comment]
If we do that by default it can create a lot of confusion I believe.. because on one client you end-up with some data, on another one that joins in afterwards with other data. I believe specifying it not to store it makes more sense.

**Comment by ramezrafla** [comment]
I expect you will have a problem either way. On the server side, there will not be a consistency of data across the different instances. On the client, you MAY not have an inconsistency as well.

My idea was to make the SyntheticMutator a publish-only tool. Only to be used when you don't care about data persistence. Your example in the Readme relates to showing when someone typing in a chat box, which I agree with 100%.

**Comment by ramezrafla** [comment]
Based on conversation with @theodorDiaconu this does not seem possible as mergebox is in charge of data consistency. Thanks Theo for checking it out! Closing ...
