### ISSUE TITLE
It empty the lists after update/insert

### ISSUE THREAD

**Issue by juvyc** [cult-of-coders/redis-oplog#97]
Hi,

I'm not sure if what's wrong with the integration I did. Right now when I imported the `redis.js` using this path '`../imports/startup/server/redis.js`' in the `main.js` on the `server` I got an empty list on the list view that used publish method. It happens when I added/updated a certain list of data.

I'm using right now the 1.4.x.x of meteor.

Any possible help are very welcome.....

Thanks!

**Comment by juvyc** [comment]
Maybe Is because of this logged error on the server?

```
W20161222-01:15:32.570(0)? (STDERR) events.js:141
W20161222-01:15:32.572(0)? (STDERR)       throw er; // Unhandled 'error' event
W20161222-01:15:32.572(0)? (STDERR)       ^
W20161222-01:15:32.573(0)? (STDERR) 
W20161222-01:15:32.573(0)? (STDERR) Error: Redis connection to 104.197.33.159:3000 failed - connect ETIMEDOUT 104.197.33.159:3000
W20161222-01:15:32.574(0)? (STDERR)     at Object.exports._errnoException (util.js:907:11)
W20161222-01:15:32.574(0)? (STDERR)     at exports._exceptionWithHostPort (util.js:930:20)
W20161222-01:15:32.575(0)? (STDERR)     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
```

Please help how to fix it if this is the reason.

Thanks!

**Comment by theodorDiaconu** [comment]
@juvyc the error states clearly *Error: Redis connection to 104.197.33.159:3000 failed*

you don't have redis opened there :)
